// SPDX-License-Identifier: ISC
//! Replay of frozen RPC auth and request-body vectors generated by an
//! in-package dump test at release-v2.1.5: 9 auth decisions through
//! dcrd's own checkAuth (admin and limited credentials, wrong and
//! garbage headers, the require flag, and the no-credentials TLS
//! mode) and 20 full response bodies through jsonRPCRead running on a
//! real HTTP test server (single and batched requests, Go's exact
//! unmarshal error texts, notification suppression, invalid ids
//! dropping the reply, the empty-batch error, case-insensitive and
//! duplicate JSON keys, and the limited-user gate), each compared
//! byte for byte including the Bitcoin Core compatibility newline.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::http::process_body;
use dcroxide_rpc::server::{Config, RpcBestState, RpcChain, RpcSubsidyParams, Server};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers13_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// The scripted chain over the block 432,100 best state.
struct MockChain13 {
    header: BlockHeader,
}

impl RpcChain for MockChain13 {
    fn best_snapshot(&mut self) -> RpcBestState {
        RpcBestState {
            hash: self.header.block_hash(),
            prev_hash: self.header.prev_block,
            height: 432100,
            bits: self.header.bits,
            next_stake_diff: 14428162590,
            total_subsidy: 1122503888072909,
            block_size: u64::from(self.header.size),
            num_txns: 7,
        }
    }
}

fn new_server(
    header: BlockHeader,
    user: &str,
    pass: &str,
    limit_user: &str,
    limit_pass: &str,
) -> Server<MockChain13> {
    let params = mainnet_params();
    Server::new(Config {
        chain: MockChain13 { header },
        chain_params: params.clone(),
        subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params)),
        min_relay_tx_fee: 10000,
        max_protocol_version: PROTOCOL_VERSION,
        sync_mgr: Box::new(()),
        conn_mgr: Box::new(()),
        tx_mempooler: Box::new(()),
        clock: Box::new(()),
        interfaces: Box::new(NoInterfaces),
        rand_u64: Box::new(|| 7),
        tx_indexer: None,
        db: Box::new(()),
        filterer_v2: Box::new(()),
        exists_addresser: None,
        log_manager: Box::new(()),
        fee_estimator: Box::new(()),
        block_templater: None,
        sanity_checker: Box::new(()),
        time_source: Box::new(()),
        proxy: String::new(),
        test_net: false,
        runtime_version: String::new(),
        cpu_miner: Box::new(()),
        mix_pooler: Box::new(()),
        profiler_mgr: Box::new(()),
        addr_manager: Box::new(()),
        mining_addrs: Vec::new(),
        user_agent_version: String::new(),
        net_info: Vec::new(),
        services: 0,
        request_shutdown: Box::new(|| {}),
        allow_unsynced_mining: false,
        rpc_user: user.to_string(),
        rpc_pass: pass.to_string(),
        rpc_limit_user: limit_user.to_string(),
        rpc_limit_pass: limit_pass.to_string(),
    })
}

#[test]
fn auth_and_body_processing_matches_dcrd() {
    let header = include_str!("data/rpchandlers8_vectors.txt")
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blk").then(|| MsgBlock::from_bytes(&unhex(f[1])).unwrap().0.header)
        })
        .expect("block fixture");

    let mut auth_cases = 0;
    let mut body_cases = 0;
    let mut lines = VECTORS.lines().peekable();
    while let Some(line) = lines.next() {
        let f: Vec<&str> = line.split('|').collect();
        match f[0] {
            "auth" => {
                auth_cases += 1;
                let name = f[2];
                let server = new_server(header, f[3], f[4], f[5], f[6]);
                let header_text = utf8(f[7]);
                let auth_header = (header_text != "-").then_some(header_text.as_str());
                let require = f[8] == "true";

                let verdict = match server.check_auth(auth_header, require) {
                    Ok((authed, is_admin)) => format!("OK:{authed}:{is_admin}"),
                    Err(err) => format!("ERR:{err}"),
                };
                assert_eq!(verdict, f[9], "{name}: verdict");
            }
            "body" => {
                body_cases += 1;
                let name = f[2];
                let is_admin = f[3] == "true";
                let body = utf8(f[4]);

                let result: Vec<&str> = lines.next().expect("bres row").split('|').collect();
                assert_eq!(result[0], "bres");

                let mut server = new_server(header, "", "", "", "");
                let got = process_body(&mut server, &body, is_admin);
                assert_eq!(
                    String::from_utf8_lossy(&got),
                    utf8(result[2]),
                    "{name}: response body"
                );
            }
            _ => {}
        }
    }
    assert_eq!(auth_cases, 9, "unexpected auth case count");
    assert_eq!(body_cases, 20, "unexpected body case count");
}
