// SPDX-License-Identifier: ISC
//! Replay of frozen getwork RPC handler vectors generated by an
//! in-package dump test running inside dcrd's internal/rpcserver
//! package at release-v2.1.5: 21 scenarios whose steps share one
//! server so the work state (the template pool keyed by the merkle
//! and stake roots, and the wait-for-updated-template flag) carries
//! across calls.  Covered: cached template reuse, the tip-change wait
//! that picks up an updated template from the subscription, the
//! known-template timeout falling back to the current template, the
//! chain-reorganization no-template error, submissions (acceptance,
//! bad proof of work, orphans, missing templates, rule and non-rule
//! rejections, the odd-length front padding, and the length/hex
//! gates), the CPU-mining/mining-address/connectivity/sync gates, and
//! the blake3 agenda variants of the work data and pow hash.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use std::collections::VecDeque;

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcBlockTemplater, RpcChain, RpcConnManager, RpcCpuMiner,
    RpcSubsidyParams, RpcSyncManager, RpcTemplateSubscription, Server, SubmitBlockFailure,
    TemplateRecv,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers11_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

fn err_or(field: &str) -> Result<(), String> {
    match field.strip_prefix("ERR:") {
        Some(err) => Err(err.to_string()),
        None => Ok(()),
    }
}

/// The scripted chain: block 432,100 facts with a replaceable tip.
struct MockChain11 {
    header: BlockHeader,
    best_hash: Hash,
    best_height: i64,
    best_header_height: i64,
    is_current: bool,
    header_by_hash: Result<(), String>,
    blake3: bool,
}

impl RpcChain for MockChain11 {
    fn best_snapshot(&mut self) -> RpcBestState {
        RpcBestState {
            hash: self.best_hash,
            prev_hash: self.header.prev_block,
            height: self.best_height,
            bits: self.header.bits,
            next_stake_diff: 14428162590,
            total_subsidy: 1122503888072909,
            block_size: u64::from(self.header.size),
            num_txns: 7,
        }
    }
    fn best_header(&mut self) -> (Hash, i64) {
        (Hash([0u8; 32]), self.best_header_height)
    }
    fn is_current(&mut self) -> bool {
        self.is_current
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        self.header_by_hash.clone().map(|()| self.header)
    }
    fn is_blake3_pow_agenda_active(&mut self, _prev_blk_hash: &Hash) -> Result<bool, String> {
        Ok(self.blake3)
    }
}

/// The scripted templater: subscriptions replay the scenario's
/// notification list (dcrd's mock pre-fills a buffered channel the
/// same way).
struct MockTemplater11 {
    curr: Result<Option<MsgBlock>, String>,
    ntfns: Vec<MsgBlock>,
}

impl RpcBlockTemplater for MockTemplater11 {
    fn current_template(&mut self) -> Result<Option<MsgBlock>, String> {
        self.curr.clone()
    }
    fn subscribe(&mut self) -> Box<dyn RpcTemplateSubscription + Send> {
        Box::new(MockSub11 {
            queue: self.ntfns.clone().into(),
        })
    }
    fn update_block_time(&mut self, _header: &mut BlockHeader) {}
}

struct MockSub11 {
    queue: VecDeque<MsgBlock>,
}

impl RpcTemplateSubscription for MockSub11 {
    fn recv(&mut self) -> TemplateRecv {
        TemplateRecv::Template(Box::new(
            self.queue.pop_front().expect("unbounded recv notification"),
        ))
    }
    fn recv_with_timeout(&mut self) -> TemplateRecv {
        match self.queue.pop_front() {
            Some(block) => TemplateRecv::Template(Box::new(block)),
            None => TemplateRecv::Timeout,
        }
    }
    fn stop(&mut self) {}
}

/// The scripted sync manager (block submission only).
struct MockSyncMgr11 {
    submit: Result<(), SubmitBlockFailure>,
}

impl RpcSyncManager for MockSyncMgr11 {
    fn submit_block(&mut self, _block: &MsgBlock) -> Result<(), SubmitBlockFailure> {
        self.submit.clone()
    }
}

/// The scripted connection manager and CPU miner.
struct MockConnMgr11 {
    count: i32,
}

impl RpcConnManager for MockConnMgr11 {
    fn connected_count(&mut self) -> i32 {
        self.count
    }
}

struct MockMiner11 {
    is_mining: bool,
}

impl RpcCpuMiner for MockMiner11 {
    fn is_mining(&mut self) -> bool {
        self.is_mining
    }
}

#[test]
fn getwork_handler_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // Template A is real block 432,100 (from the slice 8 fixture
    // file); template B flips the first merkle root byte, mirroring
    // the dump's construction.
    let block_a: MsgBlock = include_str!("data/rpchandlers8_vectors.txt")
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blk").then(|| MsgBlock::from_bytes(&unhex(f[1])).unwrap().0)
        })
        .expect("block fixture");
    let mut block_b = block_a.clone();
    block_b.header.merkle_root.0[0] ^= 0xff;

    let template_by_name = |name: &str| -> Result<Option<MsgBlock>, String> {
        match name {
            "A" => Ok(Some(block_a.clone())),
            "B" => Ok(Some(block_b.clone())),
            "NIL" => Ok(None),
            other => panic!("unknown template {other}"),
        }
    };

    let mining_addr =
        dcroxide_txscript::stdaddr::decode_address("DsRah84zx6jdA4nMYboMfLERA5V3KhBr4ru", &params)
            .unwrap();

    // The alternate chain tip used to force template waits.
    let mut alt_tip = [0u8; 32];
    alt_tip[0] = 0xee;
    let alt_tip = Hash(alt_tip);

    // Group the rows into scenarios.
    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("scen|") || l.starts_with("step|") || l.starts_with("sres|"))
        .collect();
    let mut scenarios = 0;
    let mut i = 0;
    while i < lines.len() {
        let scen: Vec<&str> = lines[i].split('|').collect();
        assert_eq!(scen[0], "scen");
        i += 1;
        scenarios += 1;

        let name = scen[2];
        let curr_spec = scen[11];
        let curr_err = scen[12].strip_prefix("ERR:");
        let ntfns: Vec<MsgBlock> = if scen[13] == "-" {
            Vec::new()
        } else {
            scen[13]
                .split(',')
                .map(|n| template_by_name(n).unwrap().expect("ntfn template"))
                .collect()
        };
        let submit = match scen[15] {
            "OK" => Ok(()),
            other => match other.strip_prefix("RULE:") {
                Some(msg) => Err(SubmitBlockFailure {
                    is_rule_error: true,
                    message: msg.to_string(),
                }),
                None => Err(SubmitBlockFailure {
                    is_rule_error: false,
                    message: other.strip_prefix("ERR:").unwrap().to_string(),
                }),
            },
        };

        // The current template, adjusted by per-step overrides.
        let mut curr: Result<Option<MsgBlock>, String> = match curr_err {
            Some(msg) => Err(msg.to_string()),
            None => template_by_name(curr_spec),
        };

        let chain = MockChain11 {
            header: block_a.header,
            best_hash: block_a.header.block_hash(),
            best_height: scen[8].parse().unwrap(),
            best_header_height: scen[7].parse().unwrap(),
            is_current: scen[9] == "true",
            header_by_hash: err_or(scen[14]),
            blake3: scen[10] == "true",
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(MockSyncMgr11 {
                submit: submit.clone(),
            }),
            conn_mgr: Box::new(MockConnMgr11 {
                count: scen[6].parse().unwrap(),
            }),
            tx_mempooler: Box::new(()),
            clock: Box::new(()),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: Some(Box::new(MockTemplater11 {
                curr: curr.clone(),
                ntfns: ntfns.clone(),
            })),
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(MockMiner11 {
                is_mining: scen[3] == "true",
            }),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: vec![mining_addr.clone(); scen[4].parse().unwrap()],
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: scen[5] == "true",
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        // Run the scenario's steps against the shared server.
        while i < lines.len() && lines[i].starts_with("step|") {
            let step: Vec<&str> = lines[i].split('|').collect();
            let result: Vec<&str> = lines[i + 1].split('|').collect();
            assert_eq!(step[0], "step");
            assert_eq!(result[0], "sres");
            i += 2;

            // Apply the per-step overrides.
            if step[4] == "ALT" {
                server.cfg.chain.best_hash = alt_tip;
            }
            if step[5] == "NIL" {
                curr = Ok(None);
            }
            server.cfg.block_templater = Some(Box::new(MockTemplater11 {
                curr: curr.clone(),
                ntfns: ntfns.clone(),
            }));

            // Parse the command through the ported pipeline.
            let params_json = utf8(step[3]);
            let raw_params = split_json_array(&params_json);
            let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
            let cmd_instance = parse_params(&registry, &method("getwork"), &param_refs)
                .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
            let cmd = GoValue::Struct(cmd_instance.fields);

            // Requests marshal a GetWorkResult; submissions a bool.
            let is_submission = matches!(&cmd, GoValue::Struct(fields)
                if matches!(&fields[0], GoValue::String(s) if !s.is_empty()));
            let typ = if is_submission {
                GoType::Bool
            } else {
                results::get_work_result()
            };

            match handlers::handle_get_work(&mut server, &cmd) {
                Ok(value) => {
                    assert_eq!(result[3], "ok", "{name}: expected an error");
                    let got = gojson::encode(&typ, &value);
                    assert_eq!(got, utf8(result[4]), "{name}: result");
                }
                Err(err) => {
                    assert_eq!(result[3], "err", "{name}: unexpected error {err:?}");
                    assert_eq!(
                        i64::from(err.code),
                        result[4].parse::<i64>().unwrap(),
                        "{name}: error code ({})",
                        err.message
                    );
                    assert_eq!(err.message, utf8(result[5]), "{name}: error message");
                }
            }
        }
    }
    assert_eq!(scenarios, 21, "unexpected scenario count");
}
