// SPDX-License-Identifier: ISC
//! Replay of frozen mempool and connection RPC handler vectors
//! generated by an in-package dump test running inside dcrd's
//! internal/rpcserver package at release-v2.1.5: 34 cases across
//! addnode, node, getconnectioncount, getnettotals, ping,
//! getmempoolinfo, getrawmempool, and existsmempooltxs, each carrying
//! the marshalled request params (parsed here through the ported
//! dcrjson pipeline), the mock seam facts, and the marshalled result
//! or the exact error code and message.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcChain, RpcClock, RpcConnManager, RpcMempoolTx, RpcPeerInfo,
    RpcSubsidyParams, RpcTxMempooler, RpcVerboseMempoolTx, Server,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_stake::TxType;
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{MsgTx, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers4_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

fn tx_type_from_name(name: &str) -> TxType {
    match name {
        "regular" => TxType::Regular,
        "sstx" => TxType::SStx,
        "ssgen" => TxType::SSGen,
        "ssrtx" => TxType::SSRtx,
        "tadd" => TxType::TAdd,
        "tspend" => TxType::TSpend,
        "treasurybase" => TxType::TreasuryBase,
        other => panic!("unknown tx type {other}"),
    }
}

fn err_or(field: &str) -> Result<(), String> {
    match field.strip_prefix("ERR:") {
        Some(err) => Err(err.to_string()),
        None => Ok(()),
    }
}

/// The scripted connection manager from a mock4 row.
struct MockConnMgr {
    count: i32,
    recv: u64,
    sent: u64,
    connect: Result<(), String>,
    remove_by_id: Result<(), String>,
    remove_by_addr: Result<(), String>,
    disconnect_by_id: Result<(), String>,
    disconnect_by_addr: Result<(), String>,
    peers: Vec<(i32, String)>,
}

impl RpcConnManager for MockConnMgr {
    fn connected_count(&mut self) -> i32 {
        self.count
    }
    fn net_totals(&mut self) -> (u64, u64) {
        (self.recv, self.sent)
    }
    fn connect(&mut self, _addr: &str, _permanent: bool) -> Result<(), String> {
        self.connect.clone()
    }
    fn remove_by_id(&mut self, _id: i32) -> Result<(), String> {
        self.remove_by_id.clone()
    }
    fn remove_by_addr(&mut self, _addr: &str) -> Result<(), String> {
        self.remove_by_addr.clone()
    }
    fn disconnect_by_id(&mut self, _id: i32) -> Result<(), String> {
        self.disconnect_by_id.clone()
    }
    fn disconnect_by_addr(&mut self, _addr: &str) -> Result<(), String> {
        self.disconnect_by_addr.clone()
    }
    fn connected_peers(&mut self) -> Vec<RpcPeerInfo> {
        self.peers
            .iter()
            .map(|(id, addr)| RpcPeerInfo {
                id: *id,
                addr: addr.clone(),
                local_addr: None,
                services: 0,
                tx_relay_disabled: false,
                last_send_unix: 0,
                last_recv_unix: 0,
                bytes_sent: 0,
                bytes_recv: 0,
                conn_time_unix: 0,
                time_offset: 0,
                version: 0,
                user_agent: String::new(),
                inbound: false,
                starting_height: 0,
                last_block: 0,
                ban_score: 0,
                last_ping_nonce: 0,
                last_ping_time_unix_nanos: 0,
                last_ping_micros: 0,
                connected: true,
            })
            .collect()
    }
    fn broadcast_message(&mut self, _msg: &dcroxide_wire::Message) {}
}

/// The scripted mempool from the fixtures and a mock4 row.
struct MockMempooler {
    descs: Vec<RpcMempoolTx>,
    verbose: Vec<RpcVerboseMempoolTx>,
    have: Vec<bool>,
    empty: bool,
}

impl RpcTxMempooler for MockMempooler {
    fn tx_descs(&mut self) -> Vec<RpcMempoolTx> {
        if self.empty {
            return Vec::new();
        }
        self.descs.clone()
    }
    fn verbose_tx_descs(&mut self) -> Vec<RpcVerboseMempoolTx> {
        if self.empty {
            return Vec::new();
        }
        self.verbose.clone()
    }
    fn have_transactions(&mut self, _hashes: &[Hash]) -> Vec<bool> {
        self.have.clone()
    }
}

/// The scripted clock.
struct MockClock(i64);

impl RpcClock for MockClock {
    fn now_unix_millis(&mut self) -> i64 {
        self.0
    }
}

/// The chain is unused by this slice.
struct StubChain;

impl RpcChain for StubChain {
    fn best_snapshot(&mut self) -> RpcBestState {
        unimplemented!()
    }
}

type MockServer = Server<StubChain>;

fn dispatch(
    server: &mut MockServer,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "addnode" => (handlers::handle_add_node(server, cmd)?, GoType::Int64.ptr()),
        "node" => (handlers::handle_node(server, cmd)?, GoType::Int64.ptr()),
        "getconnectioncount" => (
            handlers::handle_get_connection_count(server, cmd)?,
            GoType::Int32,
        ),
        "getnettotals" => (
            handlers::handle_get_net_totals(server, cmd)?,
            results::get_net_totals_result(),
        ),
        "ping" => (handlers::handle_ping(server, cmd)?, GoType::Int64.ptr()),
        "getmempoolinfo" => (
            handlers::handle_get_mempool_info(server, cmd)?,
            results::get_mempool_info_result(),
        ),
        "getrawmempool" => {
            let value = handlers::handle_get_raw_mempool(server, cmd)?;
            let typ = match &value {
                GoValue::Map(_) => GoType::Map(
                    Box::new(GoType::String),
                    Box::new(results::get_raw_mempool_verbose_result().ptr()),
                ),
                _ => GoType::String.slice(),
            };
            (value, typ)
        }
        "existsmempooltxs" => (
            handlers::handle_exists_mempool_txs(server, cmd)?,
            GoType::String,
        ),
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

#[test]
fn mempool_conn_handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // Fixtures: the mempool descriptors, their dependency lists, and
    // the connected peer.
    let mut descs: Vec<RpcMempoolTx> = Vec::new();
    let mut desc_extras: Vec<(i64, i64, i64)> = Vec::new(); // (added, height, fee)
    let mut vdeps: Vec<Vec<usize>> = Vec::new();
    let mut peer: (i32, String) = (0, String::new());
    for line in VECTORS.lines() {
        let f: Vec<&str> = line.split('|').collect();
        match f[0] {
            "desc" => {
                let (tx, _) = MsgTx::from_bytes(&unhex(f[1])).unwrap();
                descs.push(RpcMempoolTx {
                    tx,
                    tx_type: tx_type_from_name(f[2]),
                    fee: f[5].parse().unwrap(),
                });
                desc_extras.push((
                    f[3].parse().unwrap(),
                    f[4].parse().unwrap(),
                    f[5].parse().unwrap(),
                ));
            }
            "vdeps" => {
                // vdeps|0||1|0|2|0,1 — pairs of (index, deps csv).
                let mut i = 1;
                while i + 1 < f.len() {
                    let idx: usize = f[i].parse().unwrap();
                    let deps: Vec<usize> = f[i + 1]
                        .split(',')
                        .filter(|d| !d.is_empty())
                        .map(|d| d.parse().unwrap())
                        .collect();
                    assert_eq!(idx, vdeps.len(), "vdeps ordering");
                    vdeps.push(deps);
                    i += 2;
                }
            }
            "peer" => {
                peer = (f[1].parse().unwrap(), f[2].to_string());
            }
            _ => {}
        }
    }
    assert_eq!(descs.len(), 3, "desc fixture count");
    let verbose: Vec<RpcVerboseMempoolTx> = descs
        .iter()
        .enumerate()
        .map(|(i, d)| RpcVerboseMempoolTx {
            tx: d.tx.clone(),
            tx_type: d.tx_type,
            added_unix: desc_extras[i].0,
            height: desc_extras[i].1,
            fee: desc_extras[i].2,
            depends: vdeps[i].iter().map(|&j| descs[j].tx.tx_hash()).collect(),
        })
        .collect();

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock4|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock4");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        let conn_mgr = MockConnMgr {
            count: mock[2].parse().unwrap(),
            recv: mock[3].parse().unwrap(),
            sent: mock[4].parse().unwrap(),
            connect: err_or(mock[6]),
            remove_by_id: err_or(mock[7]),
            remove_by_addr: err_or(mock[8]),
            disconnect_by_id: err_or(mock[9]),
            disconnect_by_addr: err_or(mock[10]),
            peers: if mock[12] == "true" {
                vec![peer.clone()]
            } else {
                Vec::new()
            },
        };
        let mempooler = MockMempooler {
            descs: descs.clone(),
            verbose: verbose.clone(),
            have: mock[11]
                .split(',')
                .filter(|b| !b.is_empty())
                .map(|b| b == "true")
                .collect(),
            empty: name.contains("empty"),
        };
        let mut server = Server::new(Config {
            chain: StubChain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(()),
            conn_mgr: Box::new(conn_mgr),
            tx_mempooler: Box::new(mempooler),
            clock: Box::new(MockClock(mock[5].parse().unwrap())),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 34, "unexpected case count");
}
