// SPDX-License-Identifier: ISC
//! Replay of frozen stake-query RPC handler vectors generated by an
//! in-package dump test running inside dcrd's internal/rpcserver
//! package at release-v2.1.5: 41 cases across estimatestakediff,
//! existsliveticket(s), getstakedifficulty, getstakeversioninfo,
//! getstakeversions, getvoteinfo, getticketpoolvalue,
//! gettreasurybalance, and livetickets, each carrying the marshalled
//! request params (parsed here through the ported dcrjson pipeline),
//! the mock chain seam facts, and the marshalled result or the exact
//! error code and message.  The block 432100 header fixture is shared
//! with the chain-query slice vectors.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::{ConsensusDeployment, mainnet_params};
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::threshold::State;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcChain, RpcStakeVersions, RpcSubsidyParams, RpcSyncManager,
    RpcTreasuryBalance, RpcVoteCounts, Server, TreasuryBalanceFailure, VoteInfoFailure,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers3_vectors.txt");
const SLICE2_VECTORS: &str = include_str!("data/rpchandlers2_vectors.txt");

/// The deployment version the vote info cases use (mirrors the dump).
const VOTE_INFO_VERSION: u32 = 9;

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

/// The scripted chain seam from a mock3 row plus the shared fixtures.
struct MockChain3 {
    best: RpcBestState,
    want_height: i64,
    ticket_pool_value: Result<i64, String>,
    live: Result<Vec<Hash>, String>,
    check_live: bool,
    check_lives: Vec<bool>,
    count_vote: Result<u32, String>,
    vote_counts: Result<RpcVoteCounts, String>,
    vote_info: Result<Vec<ConsensusDeployment>, VoteInfoFailure>,
    treasury: Result<RpcTreasuryBalance, TreasuryBalanceFailure>,
    stake_versions: Result<Vec<RpcStakeVersions>, String>,
    block_hash_by_height: Result<Hash, String>,
    header: Result<BlockHeader, String>,
    state: Result<State, String>,
    estimate_err: Option<String>,
}

impl RpcChain for MockChain3 {
    fn best_snapshot(&mut self) -> RpcBestState {
        self.best.clone()
    }
    fn header_by_height(&mut self, _height: i64) -> Result<BlockHeader, String> {
        self.header.clone()
    }
    fn block_hash_by_height(&mut self, _height: i64) -> Result<Hash, String> {
        self.block_hash_by_height.clone()
    }
    fn next_threshold_state(&mut self, _prev: &Hash, _id: &str) -> Result<State, String> {
        self.state.clone()
    }
    fn estimate_next_stake_difficulty(
        &mut self,
        _hash: &Hash,
        new_tickets: i64,
        use_max_tickets: bool,
    ) -> Result<i64, String> {
        if let Some(err) = &self.estimate_err {
            return Err(err.clone());
        }
        // The fixed formula mirrored from the dump's mock.
        let mut v = 14336790201i64 + new_tickets * 7;
        if use_max_tickets {
            v += 1000;
        }
        Ok(v)
    }
    fn check_live_ticket(&mut self, _hash: &Hash) -> bool {
        self.check_live
    }
    fn check_live_tickets(&mut self, _hashes: &[Hash]) -> Vec<bool> {
        self.check_lives.clone()
    }
    fn calc_want_height(&mut self, _interval: i64, _height: i64) -> i64 {
        self.want_height
    }
    fn get_stake_versions(
        &mut self,
        _hash: &Hash,
        _count: i32,
    ) -> Result<Vec<RpcStakeVersions>, String> {
        self.stake_versions.clone()
    }
    fn get_vote_info(
        &mut self,
        _hash: &Hash,
        _version: u32,
    ) -> Result<Vec<ConsensusDeployment>, VoteInfoFailure> {
        self.vote_info.clone()
    }
    fn count_vote_version(&mut self, _version: u32) -> Result<u32, String> {
        self.count_vote.clone()
    }
    fn get_vote_counts(
        &mut self,
        _version: u32,
        _deployment_id: &str,
    ) -> Result<RpcVoteCounts, String> {
        self.vote_counts.clone()
    }
    fn ticket_pool_value(&mut self) -> Result<i64, String> {
        self.ticket_pool_value.clone()
    }
    fn treasury_balance(
        &mut self,
        _hash: &Hash,
    ) -> Result<RpcTreasuryBalance, TreasuryBalanceFailure> {
        self.treasury.clone()
    }
    fn live_tickets(&mut self) -> Result<Vec<Hash>, String> {
        self.live.clone()
    }

    // Unused by the stake query slice.
    fn best_header(&mut self) -> (Hash, i64) {
        unimplemented!()
    }
    fn block_by_hash(&mut self, _hash: &Hash) -> Result<MsgBlock, String> {
        unimplemented!()
    }
    fn chain_tips(&mut self) -> Vec<dcroxide_rpc::server::RpcChainTip> {
        unimplemented!()
    }
    fn chain_work(&mut self, _hash: &Hash) -> Result<dcroxide_uint256::Uint256, String> {
        unimplemented!()
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        unimplemented!()
    }
    fn is_current(&mut self) -> bool {
        unimplemented!()
    }
    fn locate_headers(&mut self, _locators: &[Hash], _stop: &Hash) -> Vec<BlockHeader> {
        unimplemented!()
    }
    fn main_chain_has_block(&mut self, _hash: &Hash) -> bool {
        unimplemented!()
    }
    fn max_block_size(&mut self, _prev: &Hash) -> Result<i64, String> {
        unimplemented!()
    }
    fn median_time_by_hash(&mut self, _hash: &Hash) -> Result<i64, String> {
        unimplemented!()
    }
    fn state_last_changed_height(&mut self, _hash: &Hash, _id: &str) -> Result<i64, String> {
        unimplemented!()
    }
    fn is_blake3_pow_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unimplemented!()
    }
    fn is_treasury_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unimplemented!()
    }
    fn is_subsidy_split_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unimplemented!()
    }
    fn is_subsidy_split_r2_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unimplemented!()
    }
}

/// The sync manager is unused by the stake query slice.
struct StubSyncManager;

impl RpcSyncManager for StubSyncManager {
    fn sync_height(&mut self) -> i64 {
        unimplemented!()
    }
}

fn state_from_name(name: &str) -> State {
    match name {
        "defined" => State::Defined,
        "started" => State::Started,
        "lockedin" => State::LockedIn,
        "active" => State::Active,
        "failed" => State::Failed,
        other => panic!("unknown threshold state {other}"),
    }
}

fn or_err<T>(field: &str, parse: impl Fn(&str) -> T) -> Result<T, String> {
    match field.strip_prefix("ERR:") {
        Some(err) => Err(err.to_string()),
        None => Ok(parse(field)),
    }
}

fn dispatch(
    server: &mut Server<MockChain3>,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "estimatestakediff" => (
            handlers::handle_estimate_stake_diff(server, cmd)?,
            results::estimate_stake_diff_result(),
        ),
        "existsliveticket" => (
            handlers::handle_exists_live_ticket(server, cmd)?,
            GoType::Bool,
        ),
        "existslivetickets" => (
            handlers::handle_exists_live_tickets(server, cmd)?,
            GoType::String,
        ),
        "getstakedifficulty" => (
            handlers::handle_get_stake_difficulty(server, cmd)?,
            results::get_stake_difficulty_result(),
        ),
        "getstakeversioninfo" => (
            handlers::handle_get_stake_version_info(server, cmd)?,
            results::get_stake_version_info_result(),
        ),
        "getstakeversions" => (
            handlers::handle_get_stake_versions(server, cmd)?,
            results::get_stake_versions_result(),
        ),
        "getvoteinfo" => (
            handlers::handle_get_vote_info(server, cmd)?,
            results::get_vote_info_result(),
        ),
        "getticketpoolvalue" => (
            handlers::handle_get_ticket_pool_value(server, cmd)?,
            GoType::Float64,
        ),
        "gettreasurybalance" => (
            handlers::handle_get_treasury_balance(server, cmd)?,
            results::get_treasury_balance_result(),
        ),
        "livetickets" => (
            handlers::handle_live_tickets(server, cmd)?,
            results::live_tickets_result(),
        ),
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

#[test]
fn stake_query_handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // The vote info agendas the dump's mock served.
    let agendas: Vec<ConsensusDeployment> = params
        .deployments
        .iter()
        .find(|(version, _)| *version == VOTE_INFO_VERSION)
        .map(|(_, agendas)| agendas.clone())
        .expect("mainnet deployments for the vote info version");

    // The header fixture shared with the chain-query slice.
    let header_fixture: BlockHeader = SLICE2_VECTORS
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blockfix").then(|| {
                let (block, _) = MsgBlock::from_bytes(&unhex(f[1])).unwrap();
                block.header
            })
        })
        .expect("block fixture");

    // The stake versions fixture list.
    let mut stake_versions: Vec<RpcStakeVersions> = Vec::new();
    for line in VECTORS.lines() {
        let f: Vec<&str> = line.split('|').collect();
        if f[0] != "sver" {
            continue;
        }
        let votes = f[5]
            .split(',')
            .map(|pair| {
                let (v, b) = pair.split_once(':').unwrap();
                (v.parse().unwrap(), b.parse().unwrap())
            })
            .collect();
        stake_versions.push(RpcStakeVersions {
            hash: f[1].parse().unwrap(),
            height: f[2].parse().unwrap(),
            block_version: f[3].parse().unwrap(),
            stake_version: f[4].parse().unwrap(),
            votes,
        });
    }
    assert_eq!(stake_versions.len(), 2, "stake versions fixture");

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock3|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock3");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        // Decode the vote counts field: "choices;...,total,abstain" or
        // an ERR: prefix followed by the unused totals.
        let vc_parts: Vec<&str> = mock[11].splitn(3, ',').collect();
        let vote_counts = match vc_parts[0].strip_prefix("ERR:") {
            Some(err) => Err(err.to_string()),
            None => Ok(RpcVoteCounts {
                total: vc_parts[1].parse().unwrap(),
                total_abstain: vc_parts[2].parse().unwrap(),
                vote_choices: vc_parts[0].split(';').map(|c| c.parse().unwrap()).collect(),
            }),
        };

        let vote_info = match mock[12] {
            "OK" => Ok(agendas.clone()),
            "ERRUV" => Err(VoteInfoFailure {
                is_unknown_deployment_version: true,
                message: String::new(),
            }),
            other => Err(VoteInfoFailure {
                is_unknown_deployment_version: false,
                message: other.strip_prefix("ERR:").unwrap().to_string(),
            }),
        };

        let treasury = match mock[13] {
            "ERRUB" => Err(TreasuryBalanceFailure {
                is_unknown_block: true,
                is_no_treasury_balance: false,
                message: String::new(),
            }),
            "ERRNT" => Err(TreasuryBalanceFailure {
                is_unknown_block: false,
                is_no_treasury_balance: true,
                message: String::new(),
            }),
            other => match other.strip_prefix("ERR:") {
                Some(err) => Err(TreasuryBalanceFailure {
                    is_unknown_block: false,
                    is_no_treasury_balance: false,
                    message: err.to_string(),
                }),
                None => {
                    let ok = other.strip_prefix("OK:").unwrap();
                    let (height, balance) = ok.split_once(',').unwrap();
                    Ok(RpcTreasuryBalance {
                        block_height: height.parse().unwrap(),
                        balance: balance.parse().unwrap(),
                        updates: mock[14]
                            .split(',')
                            .filter(|u| !u.is_empty())
                            .map(|u| u.parse().unwrap())
                            .collect(),
                    })
                }
            },
        };

        // The header and threshold state share a row field; the cases
        // never script both to fail at once.
        let (header, state) = match mock[17].strip_prefix("ERR:") {
            Some(err) => (Err(err.to_string()), Err(err.to_string())),
            None => (Ok(header_fixture), Ok(state_from_name(mock[17]))),
        };

        let chain = MockChain3 {
            best: RpcBestState {
                hash: mock[2].parse().unwrap(),
                prev_hash: Hash([0u8; 32]),
                height: mock[3].parse().unwrap(),
                bits: 0,
                next_stake_diff: mock[4].parse().unwrap(),
                total_subsidy: 0,
                block_size: 0,
                num_txns: 0,
            },
            want_height: mock[5].parse().unwrap(),
            ticket_pool_value: or_err(mock[6], |v| v.parse().unwrap()),
            live: or_err(mock[7], |v| {
                v.split(',')
                    .filter(|h| !h.is_empty())
                    .map(|h| h.parse().unwrap())
                    .collect()
            }),
            check_live: mock[8] == "true",
            check_lives: mock[9]
                .split(',')
                .filter(|b| !b.is_empty())
                .map(|b| b == "true")
                .collect(),
            count_vote: or_err(mock[10], |v| v.parse().unwrap()),
            vote_counts,
            vote_info,
            treasury,
            stake_versions: match mock[15].strip_prefix("ERR:") {
                Some(err) => Err(err.to_string()),
                None => Ok(stake_versions.clone()),
            },
            block_hash_by_height: or_err(mock[16], |v| v.parse().unwrap()),
            header,
            state,
            estimate_err: name
                .contains("estimate err")
                .then(|| "estimate failed".to_string()),
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(StubSyncManager),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(()),
            clock: Box::new(()),
            interfaces: Box::new(dcroxide_rpc::helpers::NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 41, "unexpected case count");
}
