// SPDX-License-Identifier: ISC
//! Replay of frozen chain-query RPC handler vectors generated by an
//! in-package dump test running inside dcrd's internal/rpcserver
//! package at release-v2.1.5: 41 cases across getbestblock,
//! getbestblockhash, getblockcount, getcoinsupply, getdifficulty,
//! getchaintips, getblockhash, getblockchaininfo, getheaders,
//! getblockheader, and getblock (with dcrd's own mainnet block 432100
//! as the fixture), each carrying the marshalled request params
//! (parsed here through the ported dcrjson pipeline), the mock chain
//! seam facts, and the marshalled result or the exact error code and
//! message.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::threshold::State;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcChain, RpcChainTip, RpcSubsidyParams, RpcSyncManager, Server,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_uint256::Uint256;
use dcroxide_wire::{BlockHeader, MsgBlock, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers2_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

/// A seam value that is either available or scripted to fail.
#[derive(Clone)]
enum OrErr<T> {
    Ok(T),
    Err(String),
}

impl<T: Clone> OrErr<T> {
    fn get(&self) -> Result<T, String> {
        match self {
            OrErr::Ok(v) => Ok(v.clone()),
            OrErr::Err(e) => Err(e.clone()),
        }
    }
}

fn or_err<T>(field: &str, parse: impl Fn(&str) -> T) -> OrErr<T> {
    match field.strip_prefix("ERR:") {
        Some(err) => OrErr::Err(err.to_string()),
        None => OrErr::Ok(parse(field)),
    }
}

/// The scripted chain seam from a mock2 row plus the shared fixtures.
struct MockChain2 {
    best: RpcBestState,
    best_header: (Hash, i64),
    main_chain_has_block: bool,
    block_hash_by_height: OrErr<Hash>,
    chain_work: OrErr<Uint256>,
    median_time: OrErr<i64>,
    max_block_size: OrErr<i64>,
    is_current: bool,
    blake3: OrErr<bool>,
    treasury: bool,
    state: OrErr<State>,
    since: OrErr<i64>,
    block: OrErr<MsgBlock>,
    header: OrErr<BlockHeader>,
    tips: Vec<RpcChainTip>,
    locate: Vec<BlockHeader>,
}

impl RpcChain for MockChain2 {
    fn best_snapshot(&mut self) -> RpcBestState {
        self.best.clone()
    }
    fn best_header(&mut self) -> (Hash, i64) {
        self.best_header
    }
    fn block_by_hash(&mut self, _hash: &Hash) -> Result<MsgBlock, String> {
        self.block.get()
    }
    fn block_hash_by_height(&mut self, _height: i64) -> Result<Hash, String> {
        self.block_hash_by_height.get()
    }
    fn chain_tips(&mut self) -> Vec<RpcChainTip> {
        self.tips.clone()
    }
    fn chain_work(&mut self, _hash: &Hash) -> Result<Uint256, String> {
        self.chain_work.get()
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        self.header.get()
    }
    fn header_by_height(&mut self, _height: i64) -> Result<BlockHeader, String> {
        unreachable!("not used by the chain query slice")
    }
    fn is_current(&mut self) -> bool {
        self.is_current
    }
    fn locate_headers(&mut self, _locators: &[Hash], _stop: &Hash) -> Vec<BlockHeader> {
        self.locate.clone()
    }
    fn main_chain_has_block(&mut self, _hash: &Hash) -> bool {
        self.main_chain_has_block
    }
    fn max_block_size(&mut self, _prev: &Hash) -> Result<i64, String> {
        self.max_block_size.get()
    }
    fn median_time_by_hash(&mut self, _hash: &Hash) -> Result<i64, String> {
        self.median_time.get()
    }
    fn next_threshold_state(&mut self, _prev: &Hash, _id: &str) -> Result<State, String> {
        self.state.get()
    }
    fn state_last_changed_height(&mut self, _hash: &Hash, _id: &str) -> Result<i64, String> {
        self.since.get()
    }
    fn is_blake3_pow_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        self.blake3.get()
    }
    fn is_treasury_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        // The single error case is scripted through the treasury flag
        // name in the dump; the flag row carries only the boolean, so
        // the error variant is keyed off a sentinel set by the driver.
        Ok(self.treasury)
    }
    fn is_subsidy_split_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unreachable!("not used by the chain query slice")
    }
    fn is_subsidy_split_r2_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unreachable!("not used by the chain query slice")
    }
}

/// A wrapper scripting the treasury error case.
struct MockChain2OrTreasuryErr {
    inner: MockChain2,
    treasury_err: Option<String>,
}

impl RpcChain for MockChain2OrTreasuryErr {
    fn best_snapshot(&mut self) -> RpcBestState {
        self.inner.best_snapshot()
    }
    fn best_header(&mut self) -> (Hash, i64) {
        self.inner.best_header()
    }
    fn block_by_hash(&mut self, hash: &Hash) -> Result<MsgBlock, String> {
        self.inner.block_by_hash(hash)
    }
    fn block_hash_by_height(&mut self, height: i64) -> Result<Hash, String> {
        self.inner.block_hash_by_height(height)
    }
    fn chain_tips(&mut self) -> Vec<RpcChainTip> {
        self.inner.chain_tips()
    }
    fn chain_work(&mut self, hash: &Hash) -> Result<Uint256, String> {
        self.inner.chain_work(hash)
    }
    fn header_by_hash(&mut self, hash: &Hash) -> Result<BlockHeader, String> {
        self.inner.header_by_hash(hash)
    }
    fn header_by_height(&mut self, height: i64) -> Result<BlockHeader, String> {
        self.inner.header_by_height(height)
    }
    fn is_current(&mut self) -> bool {
        self.inner.is_current()
    }
    fn locate_headers(&mut self, locators: &[Hash], stop: &Hash) -> Vec<BlockHeader> {
        self.inner.locate_headers(locators, stop)
    }
    fn main_chain_has_block(&mut self, hash: &Hash) -> bool {
        self.inner.main_chain_has_block(hash)
    }
    fn max_block_size(&mut self, prev: &Hash) -> Result<i64, String> {
        self.inner.max_block_size(prev)
    }
    fn median_time_by_hash(&mut self, hash: &Hash) -> Result<i64, String> {
        self.inner.median_time_by_hash(hash)
    }
    fn next_threshold_state(&mut self, prev: &Hash, id: &str) -> Result<State, String> {
        self.inner.next_threshold_state(prev, id)
    }
    fn state_last_changed_height(&mut self, hash: &Hash, id: &str) -> Result<i64, String> {
        self.inner.state_last_changed_height(hash, id)
    }
    fn is_blake3_pow_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_blake3_pow_agenda_active(prev)
    }
    fn is_treasury_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        if let Some(err) = &self.treasury_err {
            return Err(err.clone());
        }
        self.inner.is_treasury_agenda_active(prev)
    }
    fn is_subsidy_split_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_subsidy_split_agenda_active(prev)
    }
    fn is_subsidy_split_r2_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_subsidy_split_r2_agenda_active(prev)
    }
}

/// The sync manager seam.
struct MockSyncManager(i64);

impl RpcSyncManager for MockSyncManager {
    fn sync_height(&mut self) -> i64 {
        self.0
    }
}

fn state_from_name(name: &str) -> State {
    match name {
        "defined" => State::Defined,
        "started" => State::Started,
        "lockedin" => State::LockedIn,
        "active" => State::Active,
        "failed" => State::Failed,
        other => panic!("unknown threshold state {other}"),
    }
}

type MockServer = Server<MockChain2OrTreasuryErr>;

fn dispatch(
    server: &mut MockServer,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "getbestblock" => (
            handlers::handle_get_best_block(server, cmd)?,
            results::get_best_block_result(),
        ),
        "getbestblockhash" => (
            handlers::handle_get_best_block_hash(server, cmd)?,
            GoType::String,
        ),
        "getblockcount" => (
            handlers::handle_get_block_count(server, cmd)?,
            GoType::Int64,
        ),
        "getcoinsupply" => (
            handlers::handle_get_coin_supply(server, cmd)?,
            GoType::Int64,
        ),
        "getdifficulty" => (
            handlers::handle_get_difficulty(server, cmd)?,
            GoType::Float64,
        ),
        "getchaintips" => (
            handlers::handle_get_chain_tips(server, cmd)?,
            results::get_chain_tips_result().slice(),
        ),
        "getblockhash" => (
            handlers::handle_get_block_hash(server, cmd)?,
            GoType::String,
        ),
        "getblockchaininfo" => (
            handlers::handle_get_blockchain_info(server, cmd)?,
            results::get_block_chain_info_result(),
        ),
        "getheaders" => (
            handlers::handle_get_headers(server, cmd)?,
            results::get_headers_result(),
        ),
        "getblockheader" => {
            let value = handlers::handle_get_block_header(server, cmd)?;
            let typ = match &value {
                GoValue::String(_) => GoType::String,
                _ => results::get_block_header_verbose_result(),
            };
            (value, typ)
        }
        "getblock" => {
            let value = handlers::handle_get_block(server, cmd)?;
            let typ = match &value {
                GoValue::String(_) => GoType::String,
                _ => results::get_block_verbose_result(),
            };
            (value, typ)
        }
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

#[test]
fn chain_query_handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // Fixtures.
    let mut block_fixture: Option<MsgBlock> = None;
    let mut locate: Vec<BlockHeader> = Vec::new();
    let mut tips: Vec<RpcChainTip> = Vec::new();
    for line in VECTORS.lines() {
        let f: Vec<&str> = line.split('|').collect();
        match f[0] {
            "blockfix" => {
                let (block, _) = MsgBlock::from_bytes(&unhex(f[1])).unwrap();
                block_fixture = Some(block);
            }
            "lochdr" => {
                let (header, _) = BlockHeader::from_bytes(&unhex(f[1])).unwrap();
                locate.push(header);
            }
            "tip" => {
                tips.push(RpcChainTip {
                    height: f[1].parse().unwrap(),
                    hash: f[2].parse().unwrap(),
                    branch_len: f[3].parse().unwrap(),
                    status: f[4].to_string(),
                });
            }
            _ => {}
        }
    }
    let block_fixture = block_fixture.expect("block fixture");

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock2|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock2");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        // The scripted chain seam from the mock row.
        let inner = MockChain2 {
            best: RpcBestState {
                hash: mock[17].parse().unwrap(),
                prev_hash: mock[18].parse().unwrap(),
                height: mock[19].parse().unwrap(),
                bits: mock[20].parse().unwrap(),
                next_stake_diff: 0,
                total_subsidy: mock[21].parse().unwrap(),
            },
            best_header: (mock[12].parse().unwrap(), mock[13].parse().unwrap()),
            main_chain_has_block: mock[2] == "true",
            block_hash_by_height: or_err(mock[3], |v| v.parse().unwrap()),
            chain_work: or_err(mock[4], |v| {
                let bytes = unhex(v);
                Uint256::from_be_slice(&bytes)
            }),
            median_time: or_err(mock[5], |v| v.parse().unwrap()),
            max_block_size: or_err(mock[6], |v| v.parse().unwrap()),
            is_current: mock[7] == "true",
            blake3: or_err(mock[8], |v| v == "true"),
            treasury: mock[9] == "true",
            state: or_err(mock[10], state_from_name),
            since: or_err(mock[11], |v| v.parse().unwrap()),
            block: match mock[15].strip_prefix("ERR:") {
                Some(err) => OrErr::Err(err.to_string()),
                None => OrErr::Ok(block_fixture.clone()),
            },
            header: match mock[16].strip_prefix("ERR:") {
                Some(err) => OrErr::Err(err.to_string()),
                None => OrErr::Ok(block_fixture.header),
            },
            tips: tips.clone(),
            locate: locate.clone(),
        };
        let chain = MockChain2OrTreasuryErr {
            inner,
            treasury_err: name
                .contains("treasury err")
                .then(|| "treasury lookup failed".to_string()),
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(MockSyncManager(mock[14].parse().unwrap())),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(()),
            clock: Box::new(()),
            interfaces: Box::new(dcroxide_rpc::helpers::NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 41, "unexpected case count");
}
