// SPDX-License-Identifier: ISC
//! Replay of frozen fee-info and node-info RPC handler vectors
//! generated by an in-package dump test running inside dcrd's
//! internal/rpcserver package at release-v2.1.5: 39 cases across
//! createrawssrtx (the revocation construction over the ticket utxo
//! minimal outputs, including the P2SH commitment and automatic
//! ticket revocations paths), ticketfeeinfo, txfeeinfo, and
//! ticketvwap (the fee statistics over dcrd's real mainnet block
//! 432,100), verifychain (errors folded into the boolean result),
//! getinfo, and version.  Each case carries the marshalled request
//! params (parsed here through the ported dcrjson pipeline exactly
//! like dcrd's dispatch does, jsonrpcdefaults included), the mock
//! seam facts, and the marshalled result or the exact error code and
//! message.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{
    Config, RpcChain, RpcConnManager, RpcMempoolTx, RpcSanityChecker, RpcSubsidyParams,
    RpcTimeSource, RpcTxMempooler, RpcUtxoEntry, Server,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_stake::{MinimalOutput, TxType};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers8_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

/// The scripted chain seam over the shared block fixture.
struct MockChain8 {
    block: MsgBlock,
    header: BlockHeader,
    best_height: i64,
    block_by_height: Result<(), String>,
    height_range: Result<(), String>,
    header_by_height: Result<(), String>,
    header_by_hash: Result<(), String>,
    utxo: Result<Option<RpcUtxoEntry>, String>,
    auto_rev: Result<bool, String>,
}

impl RpcChain for MockChain8 {
    fn best_snapshot(&mut self) -> dcroxide_rpc::server::RpcBestState {
        dcroxide_rpc::server::RpcBestState {
            hash: self.header.block_hash(),
            prev_hash: self.header.prev_block,
            height: self.best_height,
            bits: self.header.bits,
            next_stake_diff: 14428162590,
            total_subsidy: 1122503888072909,
            block_size: 0,
            num_txns: 0,
        }
    }
    fn block_by_height(&mut self, _height: i64) -> Result<MsgBlock, String> {
        self.block_by_height.clone().map(|()| self.block.clone())
    }
    fn block_by_hash(&mut self, _hash: &Hash) -> Result<MsgBlock, String> {
        Ok(self.block.clone())
    }
    fn height_range(&mut self, _start: i64, _end: i64) -> Result<Vec<Hash>, String> {
        self.height_range
            .clone()
            .map(|()| vec![self.header.block_hash()])
    }
    fn header_by_height(&mut self, _height: i64) -> Result<BlockHeader, String> {
        self.header_by_height.clone().map(|()| self.header)
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        self.header_by_hash.clone().map(|()| self.header)
    }
    fn fetch_utxo_entry(
        &mut self,
        _tx_hash: &Hash,
        _index: u32,
        _tree: i8,
    ) -> Result<Option<RpcUtxoEntry>, String> {
        self.utxo.clone()
    }
    fn is_auto_revocations_agenda_active(&mut self, _prev_blk_hash: &Hash) -> Result<bool, String> {
        self.auto_rev.clone()
    }
}

/// The scripted mempool.
struct MockMempool8 {
    descs: Vec<RpcMempoolTx>,
}

impl RpcTxMempooler for MockMempool8 {
    fn tx_descs(&mut self) -> Vec<RpcMempoolTx> {
        self.descs.clone()
    }
}

/// The scripted sanity checker.
struct MockSanity8 {
    err: Option<String>,
}

impl RpcSanityChecker for MockSanity8 {
    fn check_block_sanity(&mut self, _block: &MsgBlock) -> Result<(), String> {
        match &self.err {
            Some(err) => Err(err.clone()),
            None => Ok(()),
        }
    }
}

/// The scripted time source.
struct MockTime8 {
    nanos: i64,
}

impl RpcTimeSource for MockTime8 {
    fn offset_nanos(&mut self) -> i64 {
        self.nanos
    }
}

/// The scripted connection manager.
struct MockConnMgr8;

impl RpcConnManager for MockConnMgr8 {
    fn connected_count(&mut self) -> i32 {
        4
    }
}

fn dispatch(
    server: &mut Server<MockChain8>,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "createrawssrtx" => (
            handlers::handle_create_raw_ssrtx(server, cmd)?,
            GoType::String,
        ),
        "ticketfeeinfo" => (
            handlers::handle_ticket_fee_info(server, cmd)?,
            results::ticket_fee_info_result(),
        ),
        "ticketvwap" => (handlers::handle_ticket_vwap(server, cmd)?, GoType::Float64),
        "txfeeinfo" => (
            handlers::handle_tx_fee_info(server, cmd)?,
            results::tx_fee_info_result(),
        ),
        "verifychain" => (handlers::handle_verify_chain(server, cmd)?, GoType::Bool),
        "getinfo" => (
            handlers::handle_get_info(server, cmd)?,
            results::info_chain_result(),
        ),
        "version" => (
            handlers::handle_version(server, cmd)?,
            GoType::Map(
                Box::new(GoType::String),
                Box::new(results::version_result()),
            ),
        ),
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

#[test]
fn fee_and_node_info_handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // The shared block fixture.
    let block: MsgBlock = VECTORS
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blk").then(|| {
                let (blk, _) = MsgBlock::from_bytes(&unhex(f[1])).unwrap();
                blk
            })
        })
        .expect("block fixture");

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock8|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock8");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline (the
        // jsonrpcdefault values apply exactly as in dcrd's dispatch).
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        let err_or = |field: &str| -> Result<(), String> {
            match field.strip_prefix("ERR:") {
                Some(err) => Err(err.to_string()),
                None => Ok(()),
            }
        };

        // The ticket utxo fixture.
        let utxo: Result<Option<RpcUtxoEntry>, String> = match mock[7] {
            "NIL" => Ok(None),
            spec => {
                let (tx_type, minimal_outputs) = match spec {
                    "REG" => (TxType::Regular, None),
                    "NOMO" => (TxType::SStx, None),
                    other => {
                        let outs = other
                            .strip_prefix("SSTX:")
                            .unwrap()
                            .split(';')
                            .map(|one| {
                                let parts: Vec<&str> = one.split(':').collect();
                                MinimalOutput {
                                    pk_script: unhex(parts[0]),
                                    value: parts[1].parse().unwrap(),
                                    version: parts[2].parse().unwrap(),
                                }
                            })
                            .collect();
                        (TxType::SStx, Some(outs))
                    }
                };
                Ok(Some(RpcUtxoEntry {
                    amount: 0,
                    script_version: 0,
                    pk_script: Vec::new(),
                    block_height: 100000,
                    is_coinbase: false,
                    is_spent: false,
                    tx_type,
                    ticket_minimal_outputs: minimal_outputs,
                }))
            }
        };

        // The mempool descriptors reference the shared block's
        // transactions by tree and index.
        let descs: Vec<RpcMempoolTx> = if mock[9] == "-" {
            Vec::new()
        } else {
            mock[9]
                .split(',')
                .map(|one| {
                    let parts: Vec<&str> = one.split(':').collect();
                    let idx: usize = parts[0][1..].parse().unwrap();
                    let tx = if parts[0].starts_with('r') {
                        block.transactions[idx].clone()
                    } else {
                        block.stransactions[idx].clone()
                    };
                    let tx_type = match parts[1] {
                        "0" => TxType::Regular,
                        "1" => TxType::SStx,
                        "2" => TxType::SSGen,
                        "3" => TxType::SSRtx,
                        other => panic!("unknown tx type {other}"),
                    };
                    RpcMempoolTx {
                        tx,
                        tx_type,
                        fee: parts[2].parse().unwrap(),
                    }
                })
                .collect()
        };

        let chain = MockChain8 {
            block: block.clone(),
            header: block.header,
            best_height: mock[2].parse().unwrap(),
            block_by_height: err_or(mock[3]),
            height_range: err_or(mock[4]),
            header_by_height: err_or(mock[5]),
            header_by_hash: err_or(mock[6]),
            utxo,
            auto_rev: match mock[8] {
                "true" => Ok(true),
                "false" => Ok(false),
                other => Err(other.strip_prefix("ERR:").unwrap().to_string()),
            },
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(()),
            conn_mgr: Box::new(MockConnMgr8),
            tx_mempooler: Box::new(MockMempool8 { descs }),
            clock: Box::new(()),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: (mock[14] == "true").then(|| Box::new(()) as _),
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(MockSanity8 {
                err: mock[10].strip_prefix("ERR:").map(|e| e.to_string()),
            }),
            time_source: Box::new(MockTime8 {
                nanos: mock[11].parse().unwrap(),
            }),
            proxy: mock[12].to_string(),
            test_net: mock[13] == "true",
            runtime_version: mock[15].to_string(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 39, "unexpected case count");
}
