// SPDX-License-Identifier: ISC
//! Replay of frozen RPC handler vectors generated by an in-package
//! dump test running inside dcrd's internal/rpcserver package at
//! release-v2.1.5: 61 cases across the stateless handler slice
//! (createrawtransaction, createrawsstx, decoderawtransaction,
//! decodescript, estimatefee, getblocksubsidy, getcurrentnet,
//! validateaddress, verifymessage), each carrying the marshalled
//! request params (parsed here through the ported dcrjson pipeline),
//! the mock chain seam facts, and the marshalled result or the exact
//! error code and message.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcChain, RpcChainTip, RpcSubsidyParams, RpcSyncManager, Server,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers_vectors.txt");

/// The sync manager is unused by the stateless slice.
struct StubSyncManager;

impl RpcSyncManager for StubSyncManager {
    fn sync_height(&mut self) -> i64 {
        unreachable!("not used by the stateless slice")
    }
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

/// The scripted chain seam from a mock row.
struct MockChain {
    treasury: bool,
    split: bool,
    split_r2: bool,
    best_hash: Hash,
    best_height: i64,
    hdr_prev: Hash,
    hdr_err: Option<String>,
}

impl RpcChain for MockChain {
    fn best_snapshot(&mut self) -> RpcBestState {
        RpcBestState {
            hash: self.best_hash,
            prev_hash: Hash([0u8; 32]),
            height: self.best_height,
            bits: 0,
            next_stake_diff: 0,
            total_subsidy: 0,
            block_size: 0,
            num_txns: 0,
        }
    }

    fn best_header(&mut self) -> (Hash, i64) {
        unreachable!("not used by the stateless slice")
    }
    fn block_by_hash(&mut self, _hash: &Hash) -> Result<dcroxide_wire::MsgBlock, String> {
        unreachable!("not used by the stateless slice")
    }
    fn block_hash_by_height(&mut self, _height: i64) -> Result<Hash, String> {
        unreachable!("not used by the stateless slice")
    }
    fn chain_tips(&mut self) -> Vec<RpcChainTip> {
        unreachable!("not used by the stateless slice")
    }
    fn chain_work(&mut self, _hash: &Hash) -> Result<dcroxide_uint256::Uint256, String> {
        unreachable!("not used by the stateless slice")
    }
    fn is_current(&mut self) -> bool {
        unreachable!("not used by the stateless slice")
    }
    fn locate_headers(&mut self, _locators: &[Hash], _stop: &Hash) -> Vec<BlockHeader> {
        unreachable!("not used by the stateless slice")
    }
    fn main_chain_has_block(&mut self, _hash: &Hash) -> bool {
        unreachable!("not used by the stateless slice")
    }
    fn max_block_size(&mut self, _prev: &Hash) -> Result<i64, String> {
        unreachable!("not used by the stateless slice")
    }
    fn median_time_by_hash(&mut self, _hash: &Hash) -> Result<i64, String> {
        unreachable!("not used by the stateless slice")
    }
    fn next_threshold_state(
        &mut self,
        _prev: &Hash,
        _id: &str,
    ) -> Result<dcroxide_rpc::helpers::threshold::State, String> {
        unreachable!("not used by the stateless slice")
    }
    fn state_last_changed_height(&mut self, _hash: &Hash, _id: &str) -> Result<i64, String> {
        unreachable!("not used by the stateless slice")
    }
    fn is_blake3_pow_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        unreachable!("not used by the stateless slice")
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        unreachable!("not used by the stateless slice")
    }

    fn header_by_height(&mut self, _height: i64) -> Result<BlockHeader, String> {
        if let Some(err) = &self.hdr_err {
            return Err(err.clone());
        }
        let (mut header, _) = BlockHeader::from_bytes(&[0u8; 180]).unwrap();
        header.version = 9;
        header.prev_block = self.hdr_prev;
        header.height = 432099;
        Ok(header)
    }

    fn is_treasury_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        Ok(self.treasury)
    }

    fn is_subsidy_split_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        Ok(self.split)
    }

    fn is_subsidy_split_r2_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        Ok(self.split_r2)
    }
}

fn dispatch(
    server: &mut Server<FailingOrMock>,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "createrawtransaction" => (
            handlers::handle_create_raw_transaction(server, cmd)?,
            GoType::String,
        ),
        "createrawsstx" => (
            handlers::handle_create_raw_sstx(server, cmd)?,
            GoType::String,
        ),
        "decoderawtransaction" => (
            handlers::handle_decode_raw_transaction(server, cmd)?,
            results::tx_raw_decode_result(),
        ),
        "decodescript" => (
            handlers::handle_decode_script(server, cmd)?,
            results::decode_script_result(),
        ),
        "estimatefee" => (handlers::handle_estimate_fee(server, cmd)?, GoType::Float64),
        "getblocksubsidy" => (
            handlers::handle_get_block_subsidy(server, cmd)?,
            results::get_block_subsidy_result(),
        ),
        "getcurrentnet" => (
            handlers::handle_get_current_net(server, cmd)?,
            GoType::Uint32,
        ),
        "validateaddress" => (
            handlers::handle_validate_address(server, cmd)?,
            results::validate_address_chain_result(),
        ),
        "verifymessage" => (handlers::handle_verify_message(server, cmd)?, GoType::Bool),
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

/// A chain that fails treasury lookups only when scripted to.
struct FailingOrMock {
    inner: MockChain,
    treasury_err: Option<String>,
}

impl RpcChain for FailingOrMock {
    fn best_snapshot(&mut self) -> RpcBestState {
        self.inner.best_snapshot()
    }
    fn best_header(&mut self) -> (Hash, i64) {
        self.inner.best_header()
    }
    fn block_by_hash(&mut self, hash: &Hash) -> Result<dcroxide_wire::MsgBlock, String> {
        self.inner.block_by_hash(hash)
    }
    fn block_hash_by_height(&mut self, height: i64) -> Result<Hash, String> {
        self.inner.block_hash_by_height(height)
    }
    fn chain_tips(&mut self) -> Vec<RpcChainTip> {
        self.inner.chain_tips()
    }
    fn chain_work(&mut self, hash: &Hash) -> Result<dcroxide_uint256::Uint256, String> {
        self.inner.chain_work(hash)
    }
    fn is_current(&mut self) -> bool {
        self.inner.is_current()
    }
    fn locate_headers(&mut self, locators: &[Hash], stop: &Hash) -> Vec<BlockHeader> {
        self.inner.locate_headers(locators, stop)
    }
    fn main_chain_has_block(&mut self, hash: &Hash) -> bool {
        self.inner.main_chain_has_block(hash)
    }
    fn max_block_size(&mut self, prev: &Hash) -> Result<i64, String> {
        self.inner.max_block_size(prev)
    }
    fn median_time_by_hash(&mut self, hash: &Hash) -> Result<i64, String> {
        self.inner.median_time_by_hash(hash)
    }
    fn next_threshold_state(
        &mut self,
        prev: &Hash,
        id: &str,
    ) -> Result<dcroxide_rpc::helpers::threshold::State, String> {
        self.inner.next_threshold_state(prev, id)
    }
    fn state_last_changed_height(&mut self, hash: &Hash, id: &str) -> Result<i64, String> {
        self.inner.state_last_changed_height(hash, id)
    }
    fn is_blake3_pow_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_blake3_pow_agenda_active(prev)
    }
    fn header_by_hash(&mut self, hash: &Hash) -> Result<BlockHeader, String> {
        self.inner.header_by_hash(hash)
    }
    fn header_by_height(&mut self, height: i64) -> Result<BlockHeader, String> {
        self.inner.header_by_height(height)
    }
    fn is_treasury_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        if let Some(err) = &self.treasury_err {
            return Err(err.clone());
        }
        self.inner.is_treasury_agenda_active(prev)
    }
    fn is_subsidy_split_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_subsidy_split_agenda_active(prev)
    }
    fn is_subsidy_split_r2_agenda_active(&mut self, prev: &Hash) -> Result<bool, String> {
        self.inner.is_subsidy_split_r2_agenda_active(prev)
    }
}

#[test]
fn handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    let lines: Vec<&str> = VECTORS.lines().collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        assert_eq!(case[0], "case", "unexpected row {}", lines[i]);
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(mock[0], "mock");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        // The scripted chain seam.  The "treasury err" case is the
        // only one whose mock error is not expressible in the row
        // flags; it is keyed off its name.
        let chain = FailingOrMock {
            inner: MockChain {
                treasury: mock[2] == "true",
                split: mock[3] == "true",
                split_r2: mock[4] == "true",
                best_hash: mock[5].parse().unwrap(),
                best_height: mock[6].parse().unwrap(),
                hdr_prev: mock[7].parse().unwrap(),
                hdr_err: (mock[8] != "-").then(|| mock[8].to_string()),
            },
            treasury_err: name
                .contains("treasury err")
                .then(|| "treasury lookup failed".to_string()),
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(StubSyncManager),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(()),
            clock: Box::new(()),
            interfaces: Box::new(dcroxide_rpc::helpers::NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 61, "unexpected case count");
}
