// SPDX-License-Identifier: ISC
//! Replay of frozen RPC help vectors generated by an in-package dump
//! test running inside dcrd's internal/rpcserver package at
//! release-v2.1.5.
//!
//! Every row exercises the full stack: the chain server type
//! descriptors feed dcrjson's usage and help generation through the
//! ported description map, and the output is compared byte for byte
//! against what dcrd's help cacher produces.

use std::collections::HashMap;

use dcroxide_dcrjson::Registry;
use dcroxide_rpc::{HelpCacher, RPC_HANDLER_METHODS, WS_HANDLER_METHODS};
use dcroxide_rpctypes::register_all;
use dcroxide_testutil::unhex;

const VECTORS: &str = include_str!("data/rpchelp_vectors.txt");

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).expect("utf8 payload")
}

#[test]
fn rpchelp_vectors() {
    let mut registry = Registry::new();
    register_all(&mut registry);

    // Separate cachers mirror the dump: one serves the method help
    // rows and the non-websocket usage (later poisoning the websocket
    // request), the other serves the websocket usage.
    let mut cacher = HelpCacher::new();
    let mut cacher2 = HelpCacher::new();

    let mut counts: HashMap<&str, usize> = HashMap::new();
    let mut rpc_handlers = Vec::new();
    let mut ws_handlers = Vec::new();

    for line in VECTORS.lines() {
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('|').collect();
        *counts.entry(parts[0]).or_insert(0) += 1;
        match parts[0] {
            "rpchandler" => rpc_handlers.push(parts[1].to_string()),
            "wshandler" => ws_handlers.push(parts[1].to_string()),
            "methodhelp" => {
                let help = cacher
                    .rpc_method_help(&registry, parts[1])
                    .unwrap_or_else(|e| panic!("{line}: {e}"));
                assert_eq!(help, utf8(parts[2]), "{line}");
                // A second call must serve the identical cached text.
                let cached = cacher.rpc_method_help(&registry, parts[1]).unwrap();
                assert_eq!(cached, help, "cached help for {line}");
            }
            "methodhelp-err" => {
                let err = cacher
                    .rpc_method_help(&registry, parts[1])
                    .expect_err("expected error");
                assert_eq!(err, utf8(parts[2]), "{line}");
            }
            "usage" => {
                let usage = match parts[1] {
                    "nows" => cacher.rpc_usage(&registry, false),
                    "ws" => cacher2.rpc_usage(&registry, true),
                    // QK-0005: the cacher holds one usage string, so
                    // the websocket request on the non-websocket
                    // cacher returns the poisoned cached text.
                    "poisoned" => cacher.rpc_usage(&registry, true),
                    other => panic!("unknown usage row {other}"),
                }
                .unwrap_or_else(|e| panic!("{line}: {e}"));
                assert_eq!(usage, utf8(parts[2]), "{line}");
            }
            other => panic!("unknown vector op {other}"),
        }
    }

    // The handler method lists must match the ported tables exactly.
    let want_rpc: Vec<String> = RPC_HANDLER_METHODS.iter().map(|m| m.to_string()).collect();
    let want_ws: Vec<String> = WS_HANDLER_METHODS.iter().map(|m| m.to_string()).collect();
    assert_eq!(rpc_handlers, want_rpc);
    assert_eq!(ws_handlers, want_ws);

    let expected: &[(&str, usize)] = &[
        ("rpchandler", 77),
        ("wshandler", 17),
        ("methodhelp", 93),
        ("methodhelp-err", 2),
        ("usage", 3),
    ];
    for (op, want) in expected {
        assert_eq!(counts.get(op), Some(want), "row count for {op}");
    }
}
