// SPDX-License-Identifier: ISC
//! Replay of frozen tx/utxo lookup RPC handler vectors generated by
//! an in-package dump test running inside dcrd's internal/rpcserver
//! package at release-v2.1.5: 28 cases across getrawtransaction
//! (mempool and tx-index paths with the sync gauntlet), gettxout
//! (mempool and utxo paths including the JSON null results),
//! gettxoutsetinfo, and getcfilterv2, each carrying the marshalled
//! request params (parsed here through the ported dcrjson pipeline),
//! the mock seam facts, and the marshalled result or the exact error
//! code and message.  The block 432100 header fixture is shared with
//! the chain-query slice vectors.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoType, GoValue, RPCError, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{
    Config, FilterFailure, RpcBestState, RpcChain, RpcDb, RpcFilterProof, RpcFiltererV2,
    RpcSubsidyParams, RpcTxIndexEntry, RpcTxIndexer, RpcTxMempooler, RpcUtxoEntry, RpcUtxoStats,
    Server,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, MsgTx, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers5_vectors.txt");
const SLICE2_VECTORS: &str = include_str!("data/rpchandlers2_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

/// The scripted chain seam.
struct MockChain5 {
    best: RpcBestState,
    block_height_by_hash: i64,
    header: BlockHeader,
    utxo: Result<Option<RpcUtxoEntry>, String>,
    stats: RpcUtxoStats,
    treasury: bool,
}

impl RpcChain for MockChain5 {
    fn best_snapshot(&mut self) -> RpcBestState {
        self.best.clone()
    }
    fn block_height_by_hash(&mut self, _hash: &Hash) -> Result<i64, String> {
        Ok(self.block_height_by_hash)
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        Ok(self.header)
    }
    fn fetch_utxo_entry(
        &mut self,
        _tx_hash: &Hash,
        _index: u32,
        _tree: i8,
    ) -> Result<Option<RpcUtxoEntry>, String> {
        self.utxo.clone()
    }
    fn fetch_utxo_stats(&mut self) -> Result<RpcUtxoStats, String> {
        Ok(self.stats.clone())
    }
    fn is_treasury_agenda_active(&mut self, _prev: &Hash) -> Result<bool, String> {
        Ok(self.treasury)
    }
}

/// The scripted mempool.
struct MockMempooler5 {
    fetch: Result<(MsgTx, i8), String>,
}

impl RpcTxMempooler for MockMempooler5 {
    fn fetch_transaction(&mut self, _tx_hash: &Hash) -> Result<(MsgTx, i8), String> {
        self.fetch.clone()
    }
}

/// The scripted transaction index.
struct MockTxIndexer {
    tip: Result<(i64, Hash), String>,
    signal_on_wait: bool,
    entry: Result<Option<RpcTxIndexEntry>, String>,
}

impl RpcTxIndexer for MockTxIndexer {
    fn name(&mut self) -> String {
        "testTxIndexer".to_string()
    }
    fn tip(&mut self) -> Result<(i64, Hash), String> {
        self.tip.clone()
    }
    fn entry(&mut self, _tx_hash: &Hash) -> Result<Option<RpcTxIndexEntry>, String> {
        self.entry.clone()
    }
    fn wait_for_sync(&mut self) -> bool {
        self.signal_on_wait
    }
}

/// The scripted database.
struct MockDb {
    region: Result<Vec<u8>, String>,
}

impl RpcDb for MockDb {
    fn fetch_block_region(
        &mut self,
        _block_hash: &Hash,
        _offset: u32,
        _len: u32,
    ) -> Result<Vec<u8>, String> {
        self.region.clone()
    }
}

/// The scripted filterer.
struct MockFilterer {
    result: Result<RpcFilterProof, FilterFailure>,
}

impl RpcFiltererV2 for MockFilterer {
    fn filter_by_block_hash(&mut self, _hash: &Hash) -> Result<RpcFilterProof, FilterFailure> {
        self.result.clone()
    }
}

fn dispatch(
    server: &mut Server<MockChain5>,
    method_name: &str,
    cmd: &GoValue,
) -> Result<(GoValue, GoType), RPCError> {
    let (result, typ) = match method_name {
        "getrawtransaction" => {
            let value = handlers::handle_get_raw_transaction(server, cmd)?;
            let typ = match &value {
                GoValue::String(_) => GoType::String,
                _ => results::tx_raw_result(),
            };
            (value, typ)
        }
        "gettxout" => (
            handlers::handle_get_tx_out(server, cmd)?,
            results::get_tx_out_result().ptr(),
        ),
        "gettxoutsetinfo" => (
            handlers::handle_get_tx_out_set_info(server, cmd)?,
            results::get_tx_out_set_info_result(),
        ),
        "getcfilterv2" => (
            handlers::handle_get_cfilter_v2(server, cmd)?,
            results::get_cfilter_v2_result(),
        ),
        other => panic!("unknown method {other}"),
    };
    Ok((result, typ))
}

#[test]
fn tx_utxo_handler_slice_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // Fixtures.
    let mut tx_fixture: Option<MsgTx> = None;
    let mut filter_bytes: Vec<u8> = Vec::new();
    let mut proof_index: u32 = 0;
    for line in VECTORS.lines() {
        let f: Vec<&str> = line.split('|').collect();
        match f[0] {
            "txfix" => {
                let (tx, _) = MsgTx::from_bytes(&unhex(f[1])).unwrap();
                tx_fixture = Some(tx);
            }
            "filterfix" => filter_bytes = unhex(f[1]),
            "prooffix" => proof_index = f[1].parse().unwrap(),
            _ => {}
        }
    }
    let tx_fixture = tx_fixture.expect("tx fixture");
    let tx_bytes = tx_fixture.serialize();
    let utxo_script = tx_fixture.tx_out[0].pk_script.clone();

    // The block 432100 header fixture shared with the chain query
    // slice.
    let header_fixture: BlockHeader = SLICE2_VECTORS
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blockfix").then(|| {
                let (block, _) = MsgBlock::from_bytes(&unhex(f[1])).unwrap();
                block.header
            })
        })
        .expect("block fixture");

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock5|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock5");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        // The indexer part of the row is either the single "NONE"
        // field or five inline fields.
        let (tx_indexer, rest): (Option<Box<dyn RpcTxIndexer>>, &[&str]) = if mock[3] == "NONE" {
            (None, &mock[4..])
        } else {
            let tip = match mock[3].strip_prefix("ERR:") {
                Some(err) => Err(err.to_string()),
                None => Ok((mock[4].parse().unwrap(), mock[5].parse().unwrap())),
            };
            let entry = match mock[7] {
                "NIL" => Ok(None),
                other => match other.strip_prefix("ERR:") {
                    Some(err) => Err(err.to_string()),
                    None => {
                        let ok = other.strip_prefix("OK:").unwrap();
                        let parts: Vec<&str> = ok.split(',').collect();
                        Ok(Some(RpcTxIndexEntry {
                            block_hash: parts[0].parse().unwrap(),
                            offset: parts[1].parse().unwrap(),
                            len: parts[2].parse().unwrap(),
                            block_index: parts[3].parse().unwrap(),
                        }))
                    }
                },
            };
            (
                Some(Box::new(MockTxIndexer {
                    tip,
                    signal_on_wait: mock[6] == "true",
                    entry,
                })),
                &mock[8..],
            )
        };
        // rest: [bestheight, blockHeightByHash, db, utxo, filt,
        // besthash, treasury]
        let utxo = match rest[3] {
            "NIL" => Ok(None),
            other => match other.strip_prefix("ERR:") {
                Some(err) => Err(err.to_string()),
                None => {
                    let ok = other.strip_prefix("OK:").unwrap();
                    let parts: Vec<&str> = ok.split(',').collect();
                    Ok(Some(RpcUtxoEntry {
                        amount: parts[0].parse().unwrap(),
                        script_version: parts[1].parse().unwrap(),
                        pk_script: utxo_script.clone(),
                        block_height: parts[2].parse().unwrap(),
                        is_coinbase: parts[3] == "true",
                        is_spent: parts[4] == "true",
                        tx_type: dcroxide_stake::TxType::Regular,
                        ticket_minimal_outputs: None,
                    }))
                }
            },
        };
        let best_hash: Hash = rest[5].parse().unwrap();
        let chain = MockChain5 {
            best: RpcBestState {
                hash: best_hash,
                prev_hash: header_fixture.prev_block,
                height: rest[0].parse().unwrap(),
                bits: 0,
                next_stake_diff: 0,
                total_subsidy: 0,
                block_size: 0,
                num_txns: 0,
            },
            block_height_by_hash: rest[1].parse().unwrap(),
            header: header_fixture,
            utxo,
            stats: RpcUtxoStats {
                utxos: 1593879,
                transactions: 689819,
                size: 36441617,
                total: 1154067750680149,
                serialized_hash: best_hash,
            },
            treasury: rest[6] == "true",
        };
        let mempooler = MockMempooler5 {
            fetch: match mock[2].strip_prefix("OK:") {
                Some(tree) => Ok((tx_fixture.clone(), tree.parse().unwrap())),
                None => Err("tx is not in mempool".to_string()),
            },
        };
        let db = MockDb {
            region: match rest[2].strip_prefix("ERR:") {
                Some(err) => Err(err.to_string()),
                None => Ok(tx_bytes.clone()),
            },
        };
        let filterer = MockFilterer {
            result: match rest[4] {
                "OK" => Ok(RpcFilterProof {
                    filter_bytes: filter_bytes.clone(),
                    proof_index,
                    proof_hashes: Vec::new(),
                }),
                "ERRNF" => Err(FilterFailure {
                    is_no_filter: true,
                    message: String::new(),
                }),
                other => Err(FilterFailure {
                    is_no_filter: false,
                    message: other.strip_prefix("ERR:").unwrap().to_string(),
                }),
            },
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(()),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(mempooler),
            clock: Box::new(()),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer,
            db: Box::new(db),
            filterer_v2: Box::new(filterer),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        match dispatch(&mut server, method_name, &cmd) {
            Ok((value, typ)) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&typ, &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 28, "unexpected case count");
}
