// SPDX-License-Identifier: ISC
//! Replay of frozen treasury spend votes RPC handler vectors
//! generated by an in-package dump test running inside dcrd's
//! internal/rpcserver package at release-v2.1.5: 19 cases across
//! gettreasuryspendvotes covering the mempool tally, client-specified
//! tspends resolved from the mempool and from mined blocks (with the
//! main-chain end-block walk that stops the count at the block before
//! the tspend was mined), the outside-window zero tallies, and the
//! full error ladder from hash decoding through the vote count
//! classifications.  Each case carries the marshalled request params
//! (parsed here through the ported dcrjson pipeline exactly like
//! dcrd's dispatch does), the mock seam facts, and the marshalled
//! result or the exact error code and message.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoValue, Registry, gojson, parse_params};
use dcroxide_rpc::handlers;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{
    Config, RpcBestState, RpcChain, RpcSubsidyParams, RpcTxMempooler, Server,
    TSpendCountVotesFailure,
};
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::{method, register_all};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{BlockHeader, MsgBlock, MsgTx, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/rpchandlers10_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// Split a JSON array into the raw JSON text of its elements.
fn split_json_array(data: &str) -> Vec<String> {
    let bytes = data.as_bytes();
    assert_eq!(bytes.first(), Some(&b'['), "params must be an array");
    let mut elems = Vec::new();
    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut start = None;
    for (i, &b) in bytes.iter().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => {
                in_string = true;
                if start.is_none() {
                    start = Some(i);
                }
            }
            b'[' | b'{' => {
                if depth > 0 && start.is_none() {
                    start = Some(i);
                }
                depth += 1;
            }
            b']' | b'}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(s) = start {
                        elems.push(data[s..i].trim().to_string());
                    }
                    break;
                }
            }
            b',' if depth == 1 => {
                if let Some(s) = start {
                    elems.push(data[s..i].trim().to_string());
                }
                start = None;
            }
            b' ' | b'\t' | b'\n' | b'\r' => {}
            _ => {
                if depth == 1 && start.is_none() {
                    start = Some(i);
                }
            }
        }
    }
    elems
}

fn err_or(field: &str) -> Result<(), String> {
    match field.strip_prefix("ERR:") {
        Some(err) => Err(err.to_string()),
        None => Ok(()),
    }
}

/// The scripted chain over the block 432,100 best state and the mined
/// tspend block fixture.
struct MockChain10 {
    best_header: BlockHeader,
    mined_block: MsgBlock,
    best_height: i64,
    header_height: u32,
    header_by_hash: Result<(), String>,
    main_chain: bool,
    fetch_tspend_mined: bool,
    block_by_hash: Result<(), String>,
    votes: Result<(u32, u32), TSpendCountVotesFailure>,
}

impl RpcChain for MockChain10 {
    fn best_snapshot(&mut self) -> RpcBestState {
        RpcBestState {
            hash: self.best_header.block_hash(),
            prev_hash: self.best_header.prev_block,
            height: self.best_height,
            bits: self.best_header.bits,
            next_stake_diff: 14428162590,
            total_subsidy: 1122503888072909,
            block_size: u64::from(self.best_header.size),
            num_txns: 7,
        }
    }
    fn header_by_hash(&mut self, _hash: &Hash) -> Result<BlockHeader, String> {
        self.header_by_hash.clone().map(|()| {
            let mut h = self.best_header;
            h.height = self.header_height;
            h
        })
    }
    fn main_chain_has_block(&mut self, _hash: &Hash) -> bool {
        self.main_chain
    }
    fn fetch_tspend(&mut self, _tspend: &Hash) -> Result<Vec<Hash>, String> {
        if self.fetch_tspend_mined {
            Ok(vec![self.mined_block.header.block_hash()])
        } else {
            Ok(Vec::new())
        }
    }
    fn block_by_hash(&mut self, _hash: &Hash) -> Result<MsgBlock, String> {
        self.block_by_hash
            .clone()
            .map(|()| self.mined_block.clone())
    }
    fn tspend_count_votes(
        &mut self,
        _check_block: &Hash,
        _tspend: &MsgTx,
    ) -> Result<(u32, u32), TSpendCountVotesFailure> {
        self.votes.clone()
    }
}

/// The scripted mempool over the tspend fixtures.
struct MockMempool10 {
    tspend_hashes: Vec<Hash>,
    fetch: Result<MsgTx, String>,
}

impl RpcTxMempooler for MockMempool10 {
    fn tspend_hashes(&mut self) -> Vec<Hash> {
        self.tspend_hashes.clone()
    }
    fn fetch_transaction(&mut self, _tx_hash: &Hash) -> Result<(MsgTx, i8), String> {
        self.fetch.clone().map(|tx| (tx, 1))
    }
}

#[test]
fn treasury_spend_votes_handler_matches_dcrd() {
    let params = mainnet_params();
    let mut registry = Registry::new();
    register_all(&mut registry);

    // The transaction and block fixtures.
    let mut tspend: Option<MsgTx> = None;
    let mut tspend_bad: Option<MsgTx> = None;
    let mut non_tspend: Option<MsgTx> = None;
    let mut mined_block: Option<MsgBlock> = None;
    for line in VECTORS.lines() {
        let f: Vec<&str> = line.split('|').collect();
        match f[0] {
            "tsp" => tspend = Some(MsgTx::from_bytes(&unhex(f[1])).unwrap().0),
            "tsp2" => tspend_bad = Some(MsgTx::from_bytes(&unhex(f[1])).unwrap().0),
            "ntsp" => non_tspend = Some(MsgTx::from_bytes(&unhex(f[1])).unwrap().0),
            "tspblk" => mined_block = Some(MsgBlock::from_bytes(&unhex(f[1])).unwrap().0),
            _ => {}
        }
    }
    let tspend = tspend.expect("tspend fixture");
    let tspend_bad = tspend_bad.expect("bad tspend fixture");
    let non_tspend = non_tspend.expect("non-tspend fixture");
    let mined_block = mined_block.expect("mined block fixture");

    // The block 432,100 header for the best state facts (from the
    // slice 8 fixture file).
    let best_header = include_str!("data/rpchandlers8_vectors.txt")
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blk").then(|| MsgBlock::from_bytes(&unhex(f[1])).unwrap().0.header)
        })
        .expect("block fixture");

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("case|") || l.starts_with("mock10|") || l.starts_with("result|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        let mock: Vec<&str> = lines[i + 1].split('|').collect();
        let result: Vec<&str> = lines[i + 2].split('|').collect();
        assert_eq!(case[0], "case");
        assert_eq!(mock[0], "mock10");
        assert_eq!(result[0], "result");
        i += 3;
        cases += 1;

        let name = case[2];
        let method_name = case[3];
        let params_json = utf8(case[4]);

        // Parse the command through the ported pipeline.
        let raw_params = split_json_array(&params_json);
        let param_refs: Vec<&str> = raw_params.iter().map(|s| s.as_str()).collect();
        let cmd_instance = parse_params(&registry, &method(method_name), &param_refs)
            .unwrap_or_else(|e| panic!("{name}: parse params: {e:?}"));
        let cmd = GoValue::Struct(cmd_instance.fields);

        let votes = match mock[8] {
            "ERRUB" => Err(TSpendCountVotesFailure {
                is_unknown_block: true,
                message: String::new(),
            }),
            other => match other.strip_prefix("ERR:") {
                Some(msg) => Err(TSpendCountVotesFailure {
                    is_unknown_block: false,
                    message: msg.to_string(),
                }),
                None => {
                    let (yes, no) = other.split_once(':').unwrap();
                    Ok((yes.parse().unwrap(), no.parse().unwrap()))
                }
            },
        };
        let tspend_hashes = match mock[9] {
            "-" => Vec::new(),
            "TSP" => vec![tspend.tx_hash()],
            "TSP2" => vec![tspend_bad.tx_hash()],
            other => panic!("unknown tspend hashes spec {other}"),
        };
        let fetch = match mock[10] {
            "TSP" => Ok(tspend.clone()),
            "TSP2" => Ok(tspend_bad.clone()),
            "NONTSP" => Ok(non_tspend.clone()),
            other => Err(other.strip_prefix("ERR:").unwrap().to_string()),
        };

        let chain = MockChain10 {
            best_header,
            mined_block: mined_block.clone(),
            best_height: mock[2].parse().unwrap(),
            header_height: mock[3].parse().unwrap(),
            header_by_hash: err_or(mock[4]),
            main_chain: mock[5] == "true",
            fetch_tspend_mined: mock[6] == "1",
            block_by_hash: err_or(mock[7]),
            votes,
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(()),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(MockMempool10 {
                tspend_hashes,
                fetch,
            }),
            clock: Box::new(()),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        match handlers::handle_get_treasury_spend_votes(&mut server, &cmd) {
            Ok(value) => {
                assert_eq!(result[2], "ok", "{name}: expected an error");
                let got = gojson::encode(&results::get_treasury_spend_votes_result(), &value);
                assert_eq!(got, utf8(result[3]), "{name}: result");
            }
            Err(err) => {
                assert_eq!(result[2], "err", "{name}: unexpected error {err:?}");
                assert_eq!(
                    i64::from(err.code),
                    result[3].parse::<i64>().unwrap(),
                    "{name}: error code ({})",
                    err.message
                );
                assert_eq!(err.message, utf8(result[4]), "{name}: error message");
            }
        }
    }
    assert_eq!(cases, 19, "unexpected case count");
}
