// SPDX-License-Identifier: ISC
//! Replay of frozen RPC helper vectors generated by an in-package dump
//! test running inside dcrd's internal/rpcserver package at
//! release-v2.1.5: full marshalled `createTxRawResult` outputs for
//! every transaction shape (regular, coinbase, treasurybase, treasury
//! spend, ticket, vote), the difficulty ratio bit patterns, the hash
//! decode and error constructor batteries, and the getwork data
//! helpers.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use std::collections::{HashMap, HashSet};

use dcroxide_chaincfg::{mainnet_params, testnet3_params};
use dcroxide_chainhash::Hash;
use dcroxide_dcrjson::{GoValue, RPCError, gojson};
use dcroxide_rpc::helpers;
use dcroxide_rpc::rpcerrors;
use dcroxide_rpc::txresults;
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_wire::{BlockHeader, CurrencyNet, MsgTx, PROTOCOL_VERSION};
use num_bigint::BigInt;

const VECTORS: &str = include_str!("data/rpchelpers_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd hex length: {s}");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn hex_str(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// The block header pinned by the dump's workdata rows, shared by the
/// txraw rows.
fn dump_header() -> BlockHeader {
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] == "workdata" {
            let (header, _) = BlockHeader::from_bytes(&unhex(fields[2])).unwrap();
            return header;
        }
    }
    panic!("no workdata row in vectors");
}

#[test]
fn txraw_rows_match_dcrd() {
    let params = mainnet_params();
    let header = dump_header();
    let header_hash = header.block_hash().to_string();
    let mut rows = 0;

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "txraw" {
            continue;
        }
        rows += 1;
        let label = fields[1];
        let with_header = fields[2] == "true";
        let treasury = fields[3] == "true";
        let (mtx, _) = MsgTx::from_bytes(&unhex(fields[4])).unwrap();
        let want = String::from_utf8(unhex(fields[5])).unwrap();

        let (hdr, blk_hash, height, confs, idx) = if with_header {
            (Some(&header), header_hash.as_str(), 500000i64, 12i64, 4u32)
        } else {
            (None, "", 0, 0, 0)
        };
        let result = txresults::create_tx_raw_result(
            &params,
            &mtx,
            &mtx.tx_hash().to_string(),
            idx,
            hdr,
            blk_hash,
            height,
            confs,
            treasury,
            PROTOCOL_VERSION,
            CurrencyNet::MAIN_NET,
        )
        .unwrap_or_else(|e| panic!("txraw {label}: {e:?}"));
        let got = gojson::encode(&results::tx_raw_result(), &result);
        assert_eq!(got, want, "txraw {label}");
    }
    assert_eq!(rows, 9, "unexpected txraw row count");
}

#[test]
fn txraw_hash_mismatch_matches_dcrd() {
    let params = mainnet_params();
    let header = dump_header();
    let header_hash = header.block_hash().to_string();
    let mut checked = false;

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        match fields[0] {
            // The mismatch row reuses the regular transaction.
            "txraw" if fields[1] == "regular" => {
                let (mtx, _) = MsgTx::from_bytes(&unhex(fields[4])).unwrap();
                let want = VECTORS
                    .lines()
                    .find(|l| l.starts_with("txrawerr|"))
                    .map(|l| String::from_utf8(unhex(l.split('|').nth(2).unwrap())).unwrap())
                    .unwrap();
                let err = txresults::create_tx_raw_result(
                    &params,
                    &mtx,
                    "00",
                    0,
                    None,
                    "",
                    0,
                    0,
                    true,
                    PROTOCOL_VERSION,
                    CurrencyNet::MAIN_NET,
                )
                .unwrap_err();
                // Go's RPCError.Error() renders "{code}: {message}".
                assert_eq!(format!("{}: {}", err.code, err.message), want);
                checked = true;
                let _ = header_hash.as_str();
            }
            _ => {}
        }
        if checked {
            break;
        }
    }
    assert!(checked, "no regular txraw row in vectors");
}

#[test]
fn vout_filter_matches_dcrd() {
    let params = mainnet_params();
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "voutfilter" {
            continue;
        }
        let want = String::from_utf8(unhex(fields[2])).unwrap();
        // The dump filters the regular transaction's outputs with an
        // address none of them pay.
        let regular = VECTORS
            .lines()
            .find(|l| l.starts_with("txraw|regular|"))
            .unwrap();
        let (mtx, _) = MsgTx::from_bytes(&unhex(regular.split('|').nth(4).unwrap())).unwrap();
        let mut filter = HashSet::new();
        filter.insert("bogus-address".to_string());
        let vouts = txresults::create_vout_list(&mtx, &params, &filter);
        let got = gojson::encode(&results::vout().slice(), &GoValue::Array(vouts));
        assert_eq!(got, want, "voutfilter");
        return;
    }
    panic!("no voutfilter row in vectors");
}

#[test]
fn difficulty_ratios_match_dcrd() {
    let mainnet = mainnet_params();
    let testnet = testnet3_params();
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "diff" {
            continue;
        }
        let pow_limit_bits = match fields[1] {
            "mainnet" => mainnet.pow_limit_bits,
            "testnet3" => testnet.pow_limit_bits,
            other => panic!("unknown network {other}"),
        };
        let bits = u32::from_str_radix(fields[2], 16).unwrap();
        let want = u64::from_str_radix(fields[3], 16).unwrap();
        let ratio = helpers::get_difficulty_ratio(bits, pow_limit_bits);
        assert_eq!(ratio.to_bits(), want, "diff {} {}", fields[1], fields[2]);
    }
}

#[test]
fn hash_decodes_match_dcrd() {
    // The exact strings the dump decoded, keyed by row label.
    let valid64 = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
    let inputs: HashMap<&str, Vec<String>> = HashMap::from([
        ("plain", vec![valid64.to_string()]),
        ("plain-short", vec!["abcd".to_string()]),
        ("plain-badhex", vec![format!("zz{}", &valid64[2..])]),
        ("ptr", vec![valid64.to_string()]),
        ("ptr-short", vec!["abcd".to_string()]),
        ("ptr-bad", vec!["gg".to_string()]),
    ]);

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "hashes" {
            continue;
        }
        let label = fields[1];
        let strs = &inputs[label];
        let result = if label.starts_with("ptr") {
            helpers::decode_hash_pointers(strs)
        } else {
            helpers::decode_hashes(strs)
        };
        match fields[2] {
            "ok" => {
                let hashes = result.unwrap_or_else(|e| panic!("hashes {label}: {e:?}"));
                let got: Vec<String> = hashes.iter().map(|h| hex_str(h.as_bytes())).collect();
                assert_eq!(got.join(","), fields[3], "hashes {label}");
            }
            "err" => {
                let err = result.expect_err(label);
                assert_eq!(i64::from(err.code), fields[3].parse::<i64>().unwrap());
                let want = String::from_utf8(unhex(fields[4])).unwrap();
                assert_eq!(err.message, want, "hashes {label}");
            }
            other => panic!("unknown hashes outcome {other}"),
        }
    }
}

#[test]
fn agenda_statuses_match_dcrd() {
    use dcroxide_rpc::helpers::threshold::State;
    let states: HashMap<&str, State> = HashMap::from([
        ("defined", State::Defined),
        ("started", State::Started),
        ("lockedin", State::LockedIn),
        ("active", State::Active),
        ("failed", State::Failed),
        ("invalid", State::Invalid),
    ]);
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "status" {
            continue;
        }
        let got = helpers::threshold_state_to_agenda_status(states[fields[1]]);
        assert_eq!(got, fields[2], "status {}", fields[1]);
    }
}

#[test]
fn version_map_matches_dcrd() {
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "vmap" {
            continue;
        }
        let want = String::from_utf8(unhex(fields[2])).unwrap();
        let m: HashMap<i64, i64> = HashMap::from([(9, 3), (4, 1), (7, 2), (12, 9)]);
        let counts = helpers::convert_version_map(&m);
        let value = GoValue::Array(
            counts
                .iter()
                .map(|&(v, c)| {
                    GoValue::Struct(vec![GoValue::Uint(v as u64), GoValue::Uint(c as u64)])
                })
                .collect(),
        );
        let got = gojson::encode(&results::version_count().slice(), &value);
        assert_eq!(got, want, "vmap");
        return;
    }
    panic!("no vmap row in vectors");
}

#[test]
fn le_uint256_matches_dcrd() {
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "le256" {
            continue;
        }
        let n = BigInt::parse_bytes(fields[1].as_bytes(), 16).unwrap();
        let got = helpers::big_to_le_uint256(&n);
        assert_eq!(hex_str(&got), fields[2], "le256 {}", fields[1]);
    }
}

#[test]
fn getwork_helpers_match_dcrd() {
    let header = dump_header();
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        match fields[0] {
            "workkey" => {
                let key = helpers::get_work_template_key(&header);
                assert_eq!(hex_str(&key), fields[1], "workkey");
            }
            "workdata" => {
                let blake3 = fields[1] == "true";
                let data = helpers::serialize_get_work_data(&header, blake3).unwrap();
                assert_eq!(hex_str(&data), fields[3], "workdata blake3={blake3}");
            }
            _ => {}
        }
    }
}

#[test]
fn error_constructors_match_dcrd() {
    // The same hash the dump formats into its error messages.
    let mut hash_bytes = [0u8; 32];
    hash_bytes[0] = 0x01;
    hash_bytes[1] = 0x02;
    let hash = Hash(hash_bytes);

    let build = |label: &str| -> RPCError {
        match label {
            "internal" => rpcerrors::rpc_internal_err("boom"),
            "invalid" => rpcerrors::rpc_invalid_error("bad thing 7"),
            "deserialization" => rpcerrors::rpc_deserialization_error("broken tx"),
            "rule" => rpcerrors::rpc_rule_error("rule 9"),
            "duplicate" => rpcerrors::rpc_duplicate_tx_error(&format!("dup {hash}")),
            "addresskey" => rpcerrors::rpc_address_key_error("key x"),
            "decodehex" => rpcerrors::rpc_decode_hex_error("nothex"),
            "notxinfo" => rpcerrors::rpc_no_tx_info_error(&hash),
            "blocknotfound" => rpcerrors::rpc_block_not_found_error(&hash),
            "mixmsgnotfound" => rpcerrors::rpc_mix_message_not_found_error(&hash),
            "connclosed" => rpcerrors::rpc_connection_closed_error(),
            "cancel" => rpcerrors::rpc_cancel_error("canceled call"),
            "misc" => rpcerrors::rpc_misc_error("just misc"),
            other => panic!("unknown error row {other}"),
        }
    };

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        if fields[0] != "rpcerr" {
            continue;
        }
        let err = build(fields[1]);
        assert_eq!(
            i64::from(err.code),
            fields[2].parse::<i64>().unwrap(),
            "rpcerr {} code",
            fields[1]
        );
        let want = String::from_utf8(unhex(fields[3])).unwrap();
        assert_eq!(err.message, want, "rpcerr {} message", fields[1]);
    }
}
