// SPDX-License-Identifier: ISC
//! Replay of frozen websocket notification vectors generated by an
//! in-package dump test at release-v2.1.5: 14 events driving dcrd's
//! own notification builders over clients with buffered channels.
//! Covered: blockconnected with per-client relevant transactions
//! (regular address, ticket commitment address, outpoint, and
//! filterless clients), blockdisconnected, the three work update
//! reasons, tspend, reorganization, winningtickets (the
//! string-indexed ticket map), newtickets, txaccepted with the
//! shared verbose payload, relevanttxaccepted by outpoint and by
//! address, and mixmessage.  Every marshalled notification is
//! compared byte for byte per client.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chaincfg::mainnet_params;
use dcroxide_chainhash::Hash;
use dcroxide_rpc::helpers::NoInterfaces;
use dcroxide_rpc::server::{Config, RpcBestState, RpcChain, RpcSubsidyParams, Server};
use dcroxide_rpc::websocket::{
    TemplateUpdateReason, WsClient, WsClientFilter, notify_block_connected,
    notify_block_disconnected, notify_for_new_tx, notify_mix_message, notify_new_tickets,
    notify_relevant_tx_accepted, notify_reorganization, notify_tspend, notify_winning_tickets_ntfn,
    notify_work,
};
use dcroxide_standalone::SubsidyCache;
use dcroxide_wire::{
    MIX_VERSION, MsgBlock, MsgTx, OutPoint, PROTOCOL_VERSION, decode_message_payload,
};

const VECTORS: &str = include_str!("data/rpchandlers15_vectors.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).unwrap()
}

/// The scripted chain: block 432,100 best state with the treasury
/// agenda active and blake3 inactive (the dcrd mock defaults).
struct MockChain15 {
    header: dcroxide_wire::BlockHeader,
}

impl RpcChain for MockChain15 {
    fn best_snapshot(&mut self) -> RpcBestState {
        RpcBestState {
            hash: self.header.block_hash(),
            prev_hash: self.header.prev_block,
            height: 432100,
            bits: self.header.bits,
            next_stake_diff: 14428162590,
            total_subsidy: 1122503888072909,
            block_size: u64::from(self.header.size),
            num_txns: 7,
        }
    }
    fn is_treasury_agenda_active(&mut self, _prev_blk_hash: &Hash) -> Result<bool, String> {
        Ok(true)
    }
    fn is_blake3_pow_agenda_active(&mut self, _prev_blk_hash: &Hash) -> Result<bool, String> {
        Ok(false)
    }
}

fn byte_hash(b: u8) -> Hash {
    let mut h = [0u8; 32];
    h[0] = b;
    Hash(h)
}

#[test]
fn websocket_notifications_match_dcrd() {
    let params = mainnet_params();

    let block: MsgBlock = include_str!("data/rpchandlers8_vectors.txt")
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "blk").then(|| MsgBlock::from_bytes(&unhex(f[1])).unwrap().0)
        })
        .expect("block fixture");

    // The mixing pair request fixture from the slice 9 vectors (the
    // dump constructs the identical message).
    let pr_msg = include_str!("data/rpchandlers9_vectors.txt")
        .lines()
        .find_map(|line| {
            let f: Vec<&str> = line.split('|').collect();
            (f[0] == "prfix")
                .then(|| decode_message_payload("mixpairreq", &unhex(f[1]), MIX_VERSION).unwrap())
        })
        .expect("pr fixture");

    // The bare treasury spend fixture (Go's zero MsgTx with only the
    // expiry set).
    let tspend = MsgTx {
        version: 0,
        expiry: 432290,
        ..MsgTx::default()
    };

    let lines: Vec<&str> = VECTORS
        .lines()
        .filter(|l| l.starts_with("nt|") || l.starts_with("ncli|") || l.starts_with("nres|"))
        .collect();
    let mut cases = 0;
    let mut i = 0;
    while i < lines.len() {
        let case: Vec<&str> = lines[i].split('|').collect();
        assert_eq!(case[0], "nt");
        i += 1;
        cases += 1;

        let name = case[2];
        let client_count: usize = case[3].parse().unwrap();

        // Build the clients from their filter specs.
        let mut clients: Vec<WsClient> = Vec::with_capacity(client_count);
        for ci in 0..client_count {
            let cli: Vec<&str> = lines[i].split('|').collect();
            assert_eq!(cli[0], "ncli");
            i += 1;

            let mut wsc = WsClient::new(ci as u64 + 1);
            wsc.verbose_tx_updates = cli[4] == "true";
            if cli[3] != "none" {
                let mut addresses: Vec<String> = Vec::new();
                let mut out_points: Vec<OutPoint> = Vec::new();
                if cli[3] != "empty" {
                    for part in cli[3].split('+') {
                        if let Some(addrs) = part.strip_prefix("a=") {
                            addresses.extend(addrs.split(',').map(|s| s.to_string()));
                        } else if let Some(ops) = part.strip_prefix("o=") {
                            for op in ops.split(',') {
                                let bits: Vec<&str> = op.split(':').collect();
                                out_points.push(OutPoint {
                                    hash: bits[0].parse().unwrap(),
                                    tree: bits[1].parse().unwrap(),
                                    index: bits[2].parse().unwrap(),
                                });
                            }
                        }
                    }
                }
                wsc.filter_data = Some(WsClientFilter::new(&addresses, &out_points, &params));
            }
            clients.push(wsc);
        }

        // The expected notifications per client.
        let mut expected: Vec<Vec<String>> = Vec::with_capacity(client_count);
        for ci in 0..client_count {
            let res: Vec<&str> = lines[i].split('|').collect();
            assert_eq!(res[0], "nres");
            assert_eq!(res[2], ci.to_string());
            i += 1;
            if res[3].is_empty() {
                expected.push(Vec::new());
            } else {
                expected.push(res[3].split('\x1f').map(utf8).collect());
            }
        }

        let chain = MockChain15 {
            header: block.header,
        };
        let mut server = Server::new(Config {
            chain,
            chain_params: params.clone(),
            subsidy_cache: SubsidyCache::new(RpcSubsidyParams(params.clone())),
            min_relay_tx_fee: 10000,
            max_protocol_version: PROTOCOL_VERSION,
            sync_mgr: Box::new(()),
            conn_mgr: Box::new(()),
            tx_mempooler: Box::new(()),
            clock: Box::new(()),
            interfaces: Box::new(NoInterfaces),
            rand_u64: Box::new(|| 0),
            tx_indexer: None,
            db: Box::new(()),
            filterer_v2: Box::new(()),
            exists_addresser: None,
            log_manager: Box::new(()),
            fee_estimator: Box::new(()),
            block_templater: None,
            sanity_checker: Box::new(()),
            time_source: Box::new(()),
            proxy: String::new(),
            test_net: false,
            runtime_version: String::new(),
            cpu_miner: Box::new(()),
            mix_pooler: Box::new(()),
            profiler_mgr: Box::new(()),
            addr_manager: Box::new(()),
            mining_addrs: Vec::new(),
            user_agent_version: String::new(),
            net_info: Vec::new(),
            services: 0,
            request_shutdown: Box::new(|| {}),
            allow_unsynced_mining: false,
            rpc_user: String::new(),
            rpc_pass: String::new(),
            rpc_limit_user: String::new(),
            rpc_limit_pass: String::new(),
        });

        let mut refs: Vec<&mut WsClient> = clients.iter_mut().collect();
        let notifications: Vec<(u64, String)> = match name {
            "nb: blockconnected" | "nb: blockconnected outpoint" => {
                notify_block_connected(&mut server, &mut refs, &block)
            }
            "nb: blockdisconnected" => notify_block_disconnected(&mut server, &refs, &block),
            "nb: work 0" => {
                notify_work(&mut server, &refs, &block, TemplateUpdateReason::NewParent)
            }
            "nb: work 1" => notify_work(&mut server, &refs, &block, TemplateUpdateReason::NewVotes),
            "nb: work 2" => notify_work(&mut server, &refs, &block, TemplateUpdateReason::NewTxns),
            "nb: tspend" => notify_tspend(&mut server, &refs, &tspend),
            "nb: reorganization" => notify_reorganization(
                &mut server,
                &refs,
                &byte_hash(0x01),
                432100,
                &byte_hash(0x02),
                432101,
            ),
            "nb: winningtickets" => notify_winning_tickets_ntfn(
                &mut server,
                &refs,
                &block.header.block_hash(),
                432100,
                &[byte_hash(0x0a), byte_hash(0x0b), byte_hash(0x0c)],
            ),
            "nb: newtickets" => notify_new_tickets(
                &mut server,
                &refs,
                &block.header.block_hash(),
                432100,
                14428162590,
                &[byte_hash(0x0d), byte_hash(0x0e)],
            ),
            "nb: txaccepted" => notify_for_new_tx(&mut server, &refs, &block.transactions[1]),
            "nb: relevanttx outpoint" | "nb: relevanttx address" => {
                notify_relevant_tx_accepted(&mut server, &mut refs, &block.transactions[1], 0)
            }
            "nb: mixmessage" => notify_mix_message(&mut server, &refs, &pr_msg),
            other => panic!("unknown case {other}"),
        };

        // Group the returned notifications per client session.
        let mut got: Vec<Vec<String>> = vec![Vec::new(); client_count];
        for (session, msg) in notifications {
            got[(session - 1) as usize].push(msg);
        }
        for ci in 0..client_count {
            assert_eq!(got[ci], expected[ci], "{name}: client {ci}");
        }
    }
    assert_eq!(cases, 14, "unexpected case count");
}
