// SPDX-License-Identifier: ISC
//! Replay of frozen configuration pipeline vectors generated by a
//! package-main dump test at release-v2.1.5: 76 scenarios drive
//! dcrd's real loadConfig with crafted command lines and config
//! files rooted in temp directories (tokenized as @HOME@), and the
//! full effective configuration — every option field, the cooked
//! values, the network info, and the subsystem log levels — or the
//! error text is compared field for field.  Also pinned: the
//! embedded sample config byte for byte, createDefaultConfigFile
//! under both auth types, and the cleanAndExpandPath battery.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use std::collections::BTreeMap;
use std::fs;

use dcroxide_node::config::{Assignment, ConfigEnv, sample_dcrd_conf};
use dcroxide_node::{clean_and_expand_path, create_default_config_file, load_config};

mod common;
use common::{emit_cfg, unhex};

const VECTORS: &str = include_str!("data/config_vectors.txt");

/// The controlled environment lookups the dump ran under.
fn test_getenv(name: &str) -> Option<String> {
    match name {
        "DCRTESTV1" => Some("/foo/bar".to_string()),
        _ => None,
    }
}

fn test_user_home(name: &str) -> Option<String> {
    match name {
        "" => Some("@UHOME@".to_string()),
        _ => None,
    }
}

/// Replace the generated credential lines like the dump's
/// normalization regexes.
fn normalize_creds(content: &str) -> String {
    let lines: Vec<String> = content
        .split('\n')
        .map(|line| {
            if line.starts_with("rpcuser=") {
                "rpcuser=@RAND@".to_string()
            } else if line.starts_with("rpcpass=") {
                "rpcpass=@RAND@".to_string()
            } else {
                line.to_string()
            }
        })
        .collect();
    lines.join("\n")
}

/// One scenario's parsed input rows.
#[derive(Default)]
struct Scenario {
    name: String,
    args: Vec<String>,
    no_file: bool,
    conf: Vec<String>,
    alt_conf: Vec<String>,
    expect_ok: Option<String>,
    expect_err: Option<String>,
}

#[test]
fn config_pipeline_matches_dcrd() {
    let mut localhost: Vec<String> = Vec::new();
    let mut scenarios: BTreeMap<usize, Scenario> = BTreeMap::new();
    let tmp = tempfile::tempdir().unwrap();

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.splitn(3, '|').collect();
        match fields[0] {
            "clocalhost" => {
                localhost = fields[1].split(',').map(|s| s.to_string()).collect();
            }
            "csample" => {
                assert_eq!(
                    sample_dcrd_conf().as_bytes(),
                    unhex(fields[1]),
                    "sample config"
                );
            }
            "ccreate" => {
                let dest = tmp
                    .path()
                    .join(format!("create-{}.conf", fields[1]))
                    .to_string_lossy()
                    .into_owned();
                create_default_config_file(&dest, fields[1], &|b: &mut [u8]| b.fill(0x42)).unwrap();
                let mut got = fs::read_to_string(&dest).unwrap();
                if fields[1] == "basic" {
                    got = normalize_creds(&got);
                }
                assert_eq!(
                    got.as_bytes(),
                    unhex(fields[2]),
                    "createDefaultConfigFile {}",
                    fields[1]
                );
            }
            "cpath" => {
                let got = clean_and_expand_path(fields[1], &test_getenv, &test_user_home);
                assert_eq!(got, fields[2], "cleanAndExpandPath {}", fields[1]);
            }
            "cscen" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios.entry(n).or_default().name = fields[2].to_string();
            }
            "carg" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios
                    .entry(n)
                    .or_default()
                    .args
                    .push(fields[2].to_string());
            }
            "cnofile" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios.entry(n).or_default().no_file = true;
            }
            "cfile" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios
                    .entry(n)
                    .or_default()
                    .conf
                    .push(fields[2].to_string());
            }
            "califile" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios
                    .entry(n)
                    .or_default()
                    .alt_conf
                    .push(fields[2].to_string());
            }
            "cok" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios.entry(n).or_default().expect_ok = Some(fields[2].to_string());
            }
            "cerr" => {
                let n: usize = fields[1].parse().unwrap();
                scenarios.entry(n).or_default().expect_err = Some(fields[2].to_string());
            }
            other => panic!("unknown row tag {other}"),
        }
    }
    assert_eq!(scenarios.len(), 76, "unexpected scenario count");

    for (n, sc) in &scenarios {
        // A fresh home directory per scenario, like the dump's
        // t.TempDir.
        let home_dir = tempfile::tempdir().unwrap();
        let home = home_dir.path().to_string_lossy().into_owned();

        if !sc.no_file {
            fs::write(home_dir.path().join("dcrd.conf"), sc.conf.join("\n")).unwrap();
        }
        if !sc.alt_conf.is_empty() {
            fs::write(home_dir.path().join("alt.conf"), sc.alt_conf.join("\n")).unwrap();
        }

        // Split the emitted command line into option assignments and
        // positional arguments (the dump restricts itself to
        // --long=value and bare --long forms).
        let mut cli: Vec<Assignment> = Vec::new();
        let mut positional: Vec<String> = Vec::new();
        for arg in &sc.args {
            let arg = arg.replace("@HOME@", &home);
            match arg.strip_prefix("--") {
                Some(opt) => match opt.split_once('=') {
                    Some((name, value)) => cli.push(Assignment {
                        name: name.to_string(),
                        value: Some(value.to_string()),
                    }),
                    None => cli.push(Assignment {
                        name: opt.to_string(),
                        value: None,
                    }),
                },
                None => positional.push(arg),
            }
        }

        let localhost = localhost.clone();
        let env = ConfigEnv {
            default_home_dir: "/dcroxide-nonexistent-default".to_string(),
            lookup_localhost: Box::new(move || Ok(localhost.clone())),
            interface_by_name: Box::new(|_| None),
            getenv: Box::new(test_getenv),
            user_home: Box::new(test_user_home),
            rand_bytes: Box::new(|b: &mut [u8]| b.fill(0x42)),
        };

        match load_config(&cli, &positional, &env) {
            Ok((cfg, remaining)) => {
                let expected = sc
                    .expect_ok
                    .as_ref()
                    .unwrap_or_else(|| panic!("scenario {n} {}: expected error", sc.name));
                let norm_creds = sc.name == "fresh start creates config";
                let got = emit_cfg(&cfg, &remaining, &home, norm_creds);
                assert_eq!(&got, expected, "scenario {n}: {}", sc.name);
            }
            Err(err) => {
                let expected = sc
                    .expect_err
                    .as_ref()
                    .unwrap_or_else(|| panic!("scenario {n} {}: unexpected error {err}", sc.name));
                let got = err.replace(&home, "@HOME@");
                assert_eq!(&got, expected, "scenario {n}: {}", sc.name);
            }
        }
    }
}
