// SPDX-License-Identifier: ISC
//! Replay of frozen daemon-shell vectors generated by in-package
//! dump tests at release-v2.1.5: every pipe IPC message kind framed
//! byte for byte as `serviceControlPipeTx` writes it, and the
//! version machinery — parseSemVer verdicts with dcrd's exact error
//! texts over the upstream test table plus range and separator edge
//! cases, NormalizeString, and the pinned release version with its
//! parsed components.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_node::ipc::{LifetimeAction, PipeMessage};
use dcroxide_node::version::{
    VERSION, normalize_string, parse_sem_ver, version_components, version_string,
};

const IPC_VECTORS: &str = include_str!("data/ipc_vectors.txt");
const VERSION_VECTORS: &str = include_str!("data/version_vectors.txt");

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn ipc_messages_match_dcrd() {
    let mut rows = 0;
    for line in IPC_VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        assert_eq!(fields[0], "ipc");
        rows += 1;
        let msg = match fields[1] {
            "startup db open" => PipeMessage::startup_event(LifetimeAction::DbOpen),
            "startup p2p" => PipeMessage::startup_event(LifetimeAction::P2pServer),
            "startup complete" => PipeMessage::startup_complete(),
            "shutdown p2p" => PipeMessage::shutdown_event(LifetimeAction::P2pServer),
            "shutdown db" => PipeMessage::shutdown_event(LifetimeAction::DbOpen),
            "p2p addr" => PipeMessage::BoundP2pListenAddr("127.0.0.1:9108".to_string()),
            "p2p addr v6" => PipeMessage::BoundP2pListenAddr("[::1]:9108".to_string()),
            "p2p addr empty" => PipeMessage::BoundP2pListenAddr(String::new()),
            "rpc addr" => PipeMessage::BoundRpcListenAddr("127.0.0.1:9109".to_string()),
            "rpc addr utf8" => PipeMessage::BoundRpcListenAddr("żółć.example:19109".to_string()),
            other => panic!("unknown message {other}"),
        };
        assert_eq!(hex(&msg.encode()), fields[2], "{}", fields[1]);
    }
    assert_eq!(rows, 10, "unexpected message count");
}

#[test]
fn version_machinery_matches_dcrd() {
    let mut sem_rows = 0;
    for line in VERSION_VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        match fields[0] {
            "vver" => {
                assert_eq!(fields[1], VERSION);
                assert_eq!(fields[1], version_string());
                let c = version_components();
                assert_eq!(
                    (
                        c.major,
                        c.minor,
                        c.patch,
                        c.pre_release.as_str(),
                        c.build_metadata.as_str()
                    ),
                    (
                        fields[2].parse().unwrap(),
                        fields[3].parse().unwrap(),
                        fields[4].parse().unwrap(),
                        fields[5],
                        fields[6],
                    )
                );
            }
            "vsem" => {
                sem_rows += 1;
                let ver = fields[1];
                match parse_sem_ver(ver) {
                    Ok(sem) => {
                        assert_eq!(fields[2], "ok", "{ver}: expected error {:?}", fields.get(3));
                        assert_eq!(
                            (
                                sem.major,
                                sem.minor,
                                sem.patch,
                                sem.pre_release.as_str(),
                                sem.build_metadata.as_str()
                            ),
                            (
                                fields[3].parse().unwrap(),
                                fields[4].parse().unwrap(),
                                fields[5].parse().unwrap(),
                                fields[6],
                                fields[7],
                            ),
                            "{ver}"
                        );
                    }
                    Err(err) => {
                        assert_eq!(fields[2], "err", "{ver}: unexpected error {err}");
                        assert_eq!(err, fields[3], "{ver}");
                    }
                }
            }
            "vnorm" => {
                assert_eq!(normalize_string(fields[1]), fields[2], "{}", fields[1]);
            }
            other => panic!("unknown row tag {other}"),
        }
    }
    assert_eq!(sem_rows, 83, "unexpected semver row count");
}
