// SPDX-License-Identifier: ISC
//! Replay of frozen server address bookkeeping vectors generated by
//! an in-package dump test at release-v2.1.5: the network address
//! submission cache semantics (score resets on re-add, oldest
//! access eviction at the limit, per-type best submissions),
//! hostToNetAddress over recognized and resolver-backed hosts, and
//! ResolveLocalAddress majority and listener matching over a real
//! address manager — compared row for row.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_addrmgr::{
    AddrManager, NetAddressReach, NetAddressType, new_net_address_from_ip_port,
};
use dcroxide_node::server::{NaSubmission, NaSubmissionCache};
use dcroxide_node::{host_to_net_address, resolve_local_address};
use dcroxide_wire::ServiceFlag;

const VECTORS: &str = include_str!("data/srvaddr_vectors.txt");

fn net_type(v: u8) -> NetAddressType {
    match v {
        1 => NetAddressType::IPv4,
        2 => NetAddressType::IPv6,
        _ => NetAddressType::Unknown,
    }
}

fn make_sub(ip: &str, net_type: NetAddressType, reach: NetAddressReach) -> NaSubmission {
    let ip_bytes: Vec<u8> = match ip.parse::<std::net::IpAddr>().unwrap() {
        std::net::IpAddr::V4(v4) => v4.octets().to_vec(),
        std::net::IpAddr::V6(v6) => v6.octets().to_vec(),
    };
    NaSubmission {
        na: new_net_address_from_ip_port(&ip_bytes, 9108, ServiceFlag(0), 0),
        net_type,
        reach,
        score: 0,
        last_accessed: 0,
    }
}

fn emit_cache(sc: &NaSubmissionCache) -> String {
    // The cache iterates in key order, matching the dump's sort.
    sc.cache
        .iter()
        .map(|(k, sub)| {
            format!(
                "{k};{};{};{};{}",
                sub.net_type as u8, sub.reach as u8, sub.score, sub.last_accessed
            )
        })
        .collect::<Vec<_>>()
        .join(",")
}

fn resolver(host: &str) -> Result<Vec<std::net::IpAddr>, String> {
    match host {
        "resolves.example" => Ok(vec![
            "93.184.216.34".parse().unwrap(),
            "::1".parse().unwrap(),
        ]),
        "empty.example" => Ok(Vec::new()),
        _ => Err(format!("lookup failed for {host}")),
    }
}

#[test]
fn server_address_bookkeeping_matches_dcrd() {
    // Rebuild the dump's cache session alongside the row stream.
    let mut sc = NaSubmissionCache::new(4);
    for (i, ip) in ["8.8.8.8", "1.2.3.4", "2001:4860:4860::8888"]
        .iter()
        .enumerate()
    {
        let nt = if ip.contains(':') {
            NetAddressType::IPv6
        } else {
            NetAddressType::IPv4
        };
        let reach = if ip.contains(':') {
            NetAddressReach::Ipv6Strong
        } else {
            NetAddressReach::Ipv4
        };
        sc.add(make_sub(ip, nt, reach), 0).unwrap();
        sc.cache.get_mut(*ip).unwrap().last_accessed = 100 * (i as i64 + 1);
    }
    let mut cache_states: Vec<(String, String)> = Vec::new();
    cache_states.push(("initial".to_string(), emit_cache(&sc)));

    for _ in 0..3 {
        sc.increment_score("8.8.8.8", 0).unwrap();
    }
    sc.cache.get_mut("8.8.8.8").unwrap().last_accessed = 150;
    cache_states.push(("incremented".to_string(), emit_cache(&sc)));

    let inc_err = sc.increment_score("9.9.9.9", 0).unwrap_err();

    sc.add(
        make_sub("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4),
        0,
    )
    .unwrap();
    sc.cache.get_mut("8.8.8.8").unwrap().last_accessed = 400;
    cache_states.push(("readded".to_string(), emit_cache(&sc)));

    sc.add(
        make_sub("5.6.7.8", NetAddressType::IPv4, NetAddressReach::Ipv4),
        0,
    )
    .unwrap();
    sc.cache.get_mut("5.6.7.8").unwrap().last_accessed = 500;
    sc.add(
        make_sub("9.10.11.12", NetAddressType::IPv4, NetAddressReach::Ipv4),
        0,
    )
    .unwrap();
    sc.cache.get_mut("9.10.11.12").unwrap().last_accessed = 600;
    cache_states.push(("evicted".to_string(), emit_cache(&sc)));

    sc.cache.get_mut("5.6.7.8").unwrap().score = 7;

    let mut cache_idx = 0;
    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        match fields[0] {
            "scache" => {
                let (name, state) = &cache_states[cache_idx];
                cache_idx += 1;
                assert_eq!(name, fields[1]);
                assert_eq!(state, fields[2], "{name}");
            }
            "sexists" => {
                assert_eq!(
                    sc.exists(fields[1]).to_string(),
                    fields[2],
                    "exists {}",
                    fields[1]
                );
            }
            "sincerr" => {
                assert_eq!(inc_err, fields[2], "increment error");
            }
            "sbest" => {
                let nt = net_type(fields[1].parse().unwrap());
                match sc.best_submission(nt) {
                    None => assert_eq!(fields[2], "-", "best {nt:?}"),
                    Some(best) => {
                        assert_eq!(
                            format!("{};{}", best.na.ip_string(), best.score),
                            fields[2],
                            "best {nt:?}"
                        );
                    }
                }
            }
            "shost" => {
                let host = fields[1];
                match host_to_net_address(host, 19108, ServiceFlag::NODE_NETWORK, &resolver, 0) {
                    Ok(na) => {
                        assert_eq!(fields[2], "ok", "{host}");
                        assert_eq!(na.key(), fields[3], "{host}");
                        assert_eq!((na.addr_type as u8).to_string(), fields[4], "{host}");
                    }
                    Err(err) => {
                        assert_eq!(fields[2], "err", "{host}: {err}");
                        assert_eq!(err, fields[3], "{host}");
                    }
                }
            }
            "srla" => {
                let name = fields[2];
                // The scenario parameters mirror the dump's table.
                let (ip, nt, reach, score, max_peers, listeners): (
                    &str,
                    NetAddressType,
                    NetAddressReach,
                    u32,
                    i64,
                    Vec<String>,
                ) = match name {
                    "below majority" => (
                        "8.8.8.8",
                        NetAddressType::IPv4,
                        NetAddressReach::Ipv4,
                        4,
                        125,
                        vec!["8.8.8.8:9108".into()],
                    ),
                    "exact listener match" => (
                        "8.8.8.8",
                        NetAddressType::IPv4,
                        NetAddressReach::Ipv4,
                        5,
                        125,
                        vec!["8.8.8.8:9108".into()],
                    ),
                    "generic listener" => (
                        "8.8.8.8",
                        NetAddressType::IPv4,
                        NetAddressReach::Ipv4,
                        5,
                        125,
                        vec![":9108".into()],
                    ),
                    "external v4 endpoint" => (
                        "8.8.4.4",
                        NetAddressType::IPv4,
                        NetAddressReach::Ipv4,
                        6,
                        125,
                        vec!["1.2.3.4:9108".into()],
                    ),
                    "external v6 endpoint" => (
                        "2001:4860:4860::8888",
                        NetAddressType::IPv6,
                        NetAddressReach::Ipv6Strong,
                        5,
                        125,
                        vec!["[2620:1a0::1]:9108".into()],
                    ),
                    "reach mismatch" => (
                        "2001:4860:4860::8888",
                        NetAddressType::IPv6,
                        NetAddressReach::Ipv6Strong,
                        5,
                        125,
                        vec!["1.2.3.4:9108".into()],
                    ),
                    "low maxpeers majority" => (
                        "8.8.8.8",
                        NetAddressType::IPv4,
                        NetAddressReach::Ipv4,
                        2,
                        3,
                        vec!["8.8.8.8:9108".into()],
                    ),
                    "zoned v6 listener" => (
                        "2001:4860:4860::8888",
                        NetAddressType::IPv6,
                        NetAddressReach::Ipv6Strong,
                        5,
                        125,
                        vec!["[2001:4860:4860::8888%2]:9108".into()],
                    ),
                    other => panic!("unknown scenario {other}"),
                };

                let dir = tempfile::tempdir().unwrap();
                let mut amgr = AddrManager::new(dir.path());
                let mut cache = NaSubmissionCache::new(20);
                cache.add(make_sub(ip, nt, reach), 0).unwrap();
                cache
                    .cache
                    .get_mut(&make_sub(ip, nt, reach).na.ip_string())
                    .unwrap()
                    .score = score;

                resolve_local_address(
                    &cache,
                    nt,
                    &mut amgr,
                    ServiceFlag::NODE_NETWORK,
                    &listeners,
                    max_peers,
                    &resolver,
                    0,
                );

                let mut parts: Vec<String> = amgr
                    .local_addresses()
                    .iter()
                    .map(|la| format!("{};{}", la.address, la.port))
                    .collect();
                parts.sort();
                assert_eq!(parts.join(","), fields[3], "{name}");
            }
            other => panic!("unknown row tag {other}"),
        }
    }
    assert_eq!(cache_idx, 4, "cache state rows consumed");
}
