// SPDX-License-Identifier: ISC
//! Replay of frozen server peer admission vectors generated by an
//! in-package dump driving dcrd's real handleAddPeer, DonePeer,
//! disconnectPeer, and isWhitelisted on live piped serverPeers at
//! release-v2.1.5, reading the peer state maps, banned hosts,
//! outbound groups, and submission cache directly — the ban gate
//! with expiry, the single-IP and max-peer limits with their
//! whitelisted-inbound and loopback bypasses, inbound submission
//! corroboration, outbound placement and groups, the discovery tail
//! feeding the local address resolution, and the untracked-peer
//! connection time update — compared row for row.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_addrmgr::AddrManager;
use dcroxide_node::config::IpPrefix;
use dcroxide_node::server::{
    AddPeerFacts, AddPeerOutcome, DonePeerFacts, ExternalAddrCandidateCache, ExternalAddrFacts,
    PeerState, PeerStateEntry, disconnect_peer, handle_add_peer, is_whitelisted,
    wire_to_addrmgr_net_address,
};
use dcroxide_wire::{NetAddress, ServiceFlag};

const VECTORS: &str = include_str!("data/srvadmit_vectors.txt");

/// A fixed base clock for the admission rows.
const NOW_NANOS: i64 = 1_750_000_000 * 1_000_000_000;
const HOUR_NANOS: i64 = 3_600 * 1_000_000_000;

fn wire_addr(ip: &str, port: u16) -> NetAddress {
    let mut bytes = [0u8; 16];
    match ip.parse::<std::net::IpAddr>().unwrap() {
        std::net::IpAddr::V4(v4) => {
            bytes[10] = 0xff;
            bytes[11] = 0xff;
            bytes[12..16].copy_from_slice(&v4.octets());
        }
        std::net::IpAddr::V6(v6) => bytes.copy_from_slice(&v6.octets()),
    }
    NetAddress {
        timestamp: 1_700_000_000,
        services: ServiceFlag::NODE_NETWORK,
        ip: bytes,
        port,
    }
}

/// Facts mirroring the dump's base config and an inbound rig peer.
fn base_facts(id: i32, remote: &str) -> AddPeerFacts {
    let (host, port) = remote.rsplit_once(':').unwrap();
    AddPeerFacts {
        shutdown: false,
        id,
        addr: remote.to_string(),
        inbound: true,
        persistent: false,
        is_whitelisted: false,
        na: wire_addr(host, port.parse().unwrap()),
        peer_na: None,
        max_same_ip: 0,
        external: ExternalAddrFacts {
            listeners: Vec::new(),
            has_proxy: false,
            // The dump's base config disables discovery and has no
            // listeners.
            no_discover_ip: true,
            has_external_ips: false,
            listen_disabled: true,
            sim_or_reg_net: false,
            services: ServiceFlag::NODE_NETWORK,
            target_outbound: 8,
        },
    }
}

fn banned_hosts(state: &PeerState) -> String {
    state.banned.keys().cloned().collect::<Vec<_>>().join(",")
}

struct Rows<'a> {
    lines: std::str::Lines<'a>,
}

impl<'a> Rows<'a> {
    fn next(&mut self, name: &str) -> Vec<&'a str> {
        let line = self.lines.next().expect("vector row");
        let fields: Vec<&str> = line.split('|').collect();
        assert_eq!(fields[1], name, "row order: {line}");
        fields
    }
}

#[test]
fn server_peer_admission_matches_dcrd() {
    let mut rows = Rows {
        lines: VECTORS.lines(),
    };
    let no_dns = |_: &str| -> Result<Vec<std::net::IpAddr>, String> { Err("no dns".to_string()) };
    // A fresh candidate cache per call: these scenarios all run with
    // discovery disabled, so nothing is ever stored in it, and the pin
    // keeps it on the server rather than on the peer state.
    let add = |state: &mut PeerState,
               addr_mgr: &mut AddrManager,
               facts: &AddPeerFacts|
     -> AddPeerOutcome {
        handle_add_peer(
            state,
            &mut ExternalAddrCandidateCache::new(),
            addr_mgr,
            facts,
            &no_dns,
            NOW_NANOS,
        )
    };
    let amgr_dir = || tempfile::tempdir().unwrap();

    // --- banned host gate (dcrd 2.2 handleBannedConn, before the
    // handshake; the vector rows carry the v2.1.5 dump's banned-map
    // transitions, which the relocated check preserves) -----------------
    let dir = amgr_dir();
    let mut amgr = AddrManager::new(dir.path());
    let mut state = PeerState::new();
    state
        .banned
        .insert("10.0.0.2".to_string(), NOW_NANOS + HOUR_NANOS);
    let out = dcroxide_node::server::handle_banned_conn(&mut state.banned, "10.0.0.2", NOW_NANOS);
    let fields = rows.next("bannedactive");
    assert!(out.banned, "an active ban rejects the connection");
    assert_eq!(fields[2], "false");
    assert_eq!(banned_hosts(&state), fields[3]);
    assert_eq!(state.inbound_peers.len().to_string(), fields[4]);

    let mut state = PeerState::new();
    state
        .banned
        .insert("10.0.0.2".to_string(), NOW_NANOS - HOUR_NANOS);
    let out = dcroxide_node::server::handle_banned_conn(&mut state.banned, "10.0.0.2", NOW_NANOS);
    let fields = rows.next("bannedexpired");
    assert!(!out.banned);
    assert!(out.unbanned, "an expired ban lifts");
    assert_eq!(fields[2], "true");
    assert_eq!(banned_hosts(&state), fields[3]);
    // The 2.2 check runs before the handshake, so no peer is added;
    // the admission that follows it inserts unconditionally.
    let out = add(&mut state, &mut amgr, &base_facts(1, "10.0.0.2:34567"));
    assert_eq!(out.rejected, None);
    assert_eq!(state.inbound_peers.len().to_string(), fields[4]);

    // --- outbound placement and groups ----------------------------------------
    let mut state = PeerState::new();
    let mut facts = base_facts(1, "52.91.77.2:34567");
    facts.inbound = false;
    let out = add(&mut state, &mut amgr, &facts);
    let fields = rows.next("outboundgroup");
    assert_eq!(out.rejected.is_none().to_string(), fields[2]);
    assert_eq!(state.outbound_peers.len().to_string(), fields[3]);
    // fields[4] carried the v2.1.5 peer-state group count; dcrd 2.2
    // tracks outbound groups in the connection manager instead.

    // DonePeer removes the tracked outbound peer and decrements its
    // group.
    let done = dcroxide_node::server::done_peer(
        &mut state,
        &mut amgr,
        &DonePeerFacts {
            id: 1,
            inbound: false,
            persistent: false,
            version_known: true,
            ver_ack_received: true,
            na: Some(wire_addr("52.91.77.2", 34567)),
            has_conn_req: false,
            sim_or_reg_net: false,
        },
    );
    let fields = rows.next("outbound");
    assert!(done.removed);
    assert!(!done.conn_mgr_disconnect);
    assert_eq!(state.outbound_peers.len().to_string(), fields[2]);
    // fields[3] carried the v2.1.5 group decrement, now in the
    // connection manager.

    let mut state = PeerState::new();
    let mut facts = base_facts(1, "52.91.77.2:34567");
    facts.inbound = false;
    facts.persistent = true;
    let out = add(&mut state, &mut amgr, &facts);
    let fields = rows.next("persistent");
    assert_eq!(out.rejected.is_none().to_string(), fields[2]);
    assert_eq!(state.persistent_peers.len().to_string(), fields[3]);
    // fields[4]: the v2.1.5 group count, now in the connection
    // manager.

    // The outbound discovery scenarios that used to sit here moved to
    // `srvextaddr_vectors.rs`: at the pin they run through
    // `consider_reported_addr` over the server's candidate cache
    // rather than through the peer state, and their rows are dumped
    // from 036b7090 rather than from release-v2.1.5.

    // --- DonePeer for untracked peers ---------------------------------------------
    let seed_amgr = |amgr: &mut AddrManager| {
        let na = wire_to_addrmgr_net_address(&wire_addr("52.91.77.2", 34567));
        let src = wire_to_addrmgr_net_address(&wire_addr("8.8.8.8", 9108));
        amgr.add_addresses(std::slice::from_ref(&na), &src);
        amgr.good(&na).unwrap();
    };
    let cache_ts = |amgr: &mut AddrManager| -> i64 {
        let cache = amgr.address_cache(|_: dcroxide_addrmgr::NetAddressType| true);
        assert_eq!(cache.len(), 1, "expected one cached address");
        cache[0].timestamp
    };
    let untracked_facts = |sim_or_reg_net: bool| DonePeerFacts {
        id: 1,
        inbound: true,
        persistent: false,
        version_known: true,
        ver_ack_received: true,
        na: Some(wire_addr("52.91.77.2", 34567)),
        has_conn_req: false,
        sim_or_reg_net,
    };
    let seed_ts_nanos: i64 = 1_700_000_000 * 1_000_000_000;

    let dir = amgr_dir();
    let mut amgr = AddrManager::new(dir.path());
    let mut state = PeerState::new();
    seed_amgr(&mut amgr);
    let pre = cache_ts(&mut amgr);
    let done = dcroxide_node::server::done_peer(&mut state, &mut amgr, &untracked_facts(false));
    let post = cache_ts(&mut amgr);
    let fields = rows.next("notinmaps");
    assert!(!done.removed);
    assert!(done.marked_connected);
    assert_eq!((pre == seed_ts_nanos).to_string(), fields[2]);
    assert_eq!((post > pre).to_string(), fields[3]);

    // The simulation networks skip the connection time update.
    let dir = amgr_dir();
    let mut amgr = AddrManager::new(dir.path());
    let mut state = PeerState::new();
    seed_amgr(&mut amgr);
    let pre = cache_ts(&mut amgr);
    let done = dcroxide_node::server::done_peer(&mut state, &mut amgr, &untracked_facts(true));
    let post = cache_ts(&mut amgr);
    let fields = rows.next("simnet");
    assert!(!done.marked_connected);
    assert_eq!((pre == seed_ts_nanos).to_string(), fields[2]);
    assert_eq!((post > pre).to_string(), fields[3]);

    // --- isWhitelisted ---------------------------------------------------------------
    let whitelists = vec![
        IpPrefix {
            ip: vec![10, 0, 0, 0],
            ones: 8,
        },
        IpPrefix {
            ip: vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            ones: 128,
        },
    ];
    let fields = rows.next("empty");
    assert_eq!(is_whitelisted(&[], "10.0.0.2:34567").to_string(), fields[2]);
    let fields = rows.next("contained");
    assert_eq!(
        is_whitelisted(&whitelists, "10.0.0.2:34567").to_string(),
        fields[2]
    );
    let fields = rows.next("notcontained");
    assert_eq!(
        is_whitelisted(&whitelists, "52.91.77.2:34567").to_string(),
        fields[2]
    );
    let fields = rows.next("v6loopback");
    assert_eq!(
        is_whitelisted(&whitelists, "[::1]:1234").to_string(),
        fields[2]
    );
    let fields = rows.next("badhostport");
    assert_eq!(is_whitelisted(&whitelists, "noport").to_string(), fields[2]);
    let fields = rows.next("badip");
    assert_eq!(
        is_whitelisted(&whitelists, "host:1234").to_string(),
        fields[2]
    );

    // --- disconnectPeer -----------------------------------------------------------------
    let entry = |remote: &str| -> PeerStateEntry {
        let (host, port) = remote.rsplit_once(':').unwrap();
        PeerStateEntry {
            na: wire_addr(host, port.parse().unwrap()),
            inbound: true,
            persistent: false,
        }
    };
    let mut peer_map = std::collections::BTreeMap::new();
    peer_map.insert(1, entry("10.0.0.2:34567"));
    peer_map.insert(2, entry("10.0.0.3:34567"));
    let mut when_found = 0;
    let removed = disconnect_peer(&mut peer_map, |id, _| id == 1);
    if removed.is_some() {
        when_found += 1;
    }
    let fields = rows.next("found");
    assert_eq!(removed.is_some().to_string(), fields[2]);
    assert_eq!(peer_map.len().to_string(), fields[3]);
    assert_eq!(when_found.to_string(), fields[4]);
    // The removed peer is disconnected by the caller.
    assert_eq!(fields[5], "false");

    let removed = disconnect_peer(&mut peer_map, |_, _| false);
    let fields = rows.next("notfound");
    assert_eq!(removed.is_some().to_string(), fields[2]);
    assert_eq!(peer_map.len().to_string(), fields[3]);

    assert!(rows.lines.next().is_none(), "unconsumed vector rows");
}
