// SPDX-License-Identifier: ISC
//! Replay of frozen server abuse control vectors generated by an
//! in-package dump driving dcrd's real handlers over piped peers at
//! release-v2.1.5: the mempool flood ban ladder (three warnings,
//! banned on the fourth), the unsupported version 1 committed
//! filter enforcement (a single violation scores exactly the
//! threshold and disconnects without banning), and the notfound
//! classification with its block/transaction/mix ban scores —
//! compared row for row.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use std::collections::BTreeMap;

use dcroxide_chainhash::Hash;
use dcroxide_node::server::{
    CfFlagOutcome, OnMemPoolOutcome, OnNotFoundOutcome, ServerPeerAddrState, ban_peer,
    enforce_node_cf_flag, on_mem_pool, on_not_found,
};
use dcroxide_wire::{InvType, InvVect, PROTOCOL_VERSION};

const VECTORS: &str = include_str!("data/srvabuse_vectors.txt");

fn invs(inv_type: InvType, count: u8) -> Vec<InvVect> {
    (0..count)
        .map(|i| {
            let mut h = [0u8; 32];
            h[0] = i + 1;
            InvVect {
                inv_type,
                hash: Hash(h),
            }
        })
        .collect()
}

fn banned_hosts(banned: &BTreeMap<String, i64>) -> String {
    banned.keys().cloned().collect::<Vec<_>>().join(",")
}

#[test]
fn server_abuse_control_matches_dcrd() {
    let now: i64 = 1_700_000_000;
    let ban_threshold: u32 = 100;
    let ban_duration_nanos: i64 = 24 * 3600 * 1_000_000_000;
    let peer_addr = "10.0.0.2:34567";

    // The mempool ladder shares one peer state across the rows.
    let mut mp_state = ServerPeerAddrState::new(false);
    let mut mp_banned: BTreeMap<String, i64> = BTreeMap::new();

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        match (fields[0], fields[1]) {
            ("mp", n) => {
                let out = on_mem_pool(&mut mp_state, &[], false, ban_threshold, now);
                let banned = out == OnMemPoolOutcome::Banned;
                if banned {
                    ban_peer(
                        &mut mp_banned,
                        peer_addr,
                        false,
                        false,
                        ban_duration_nanos,
                        now * 1_000_000_000,
                    );
                }
                // The empty pool never produces inventory.
                assert_eq!(fields[2], "false", "request {n}: no inventory");
                assert_eq!(banned_hosts(&mp_banned), fields[3], "request {n}");
                // dcrd stays connected until the ban.
                assert_eq!((!banned).to_string(), fields[4], "request {n}");
            }
            ("cf", name) => {
                let disable_banning = name.contains("nobanning");
                let out = enforce_node_cf_flag(PROTOCOL_VERSION, disable_banning, "getcfilter");
                match out {
                    CfFlagOutcome::BanAndDisconnect { reason } => {
                        // dcrd 2.2 bans directly with the command and
                        // protocol version in the reason.
                        assert!(!disable_banning, "{name}");
                        assert_eq!(
                            reason,
                            format!(
                                "sent getcfilter request with protocol version \
                                 {PROTOCOL_VERSION} >= {}",
                                dcroxide_wire::NODE_CF_VERSION
                            ),
                            "{name}"
                        );
                    }
                    CfFlagOutcome::DisconnectOnly => {
                        // With banning disabled only the disconnect
                        // remains.
                        assert!(disable_banning, "{name}");
                    }
                }
            }
            ("nf", name) => {
                let inv_list = match name {
                    "invalidtype" => invs(InvType::FILTERED_BLOCK, 1),
                    "blocksban" => invs(InvType::BLOCK, 6),
                    "txflood" => invs(InvType::TX, 11),
                    "mixflood" => invs(InvType::MIX, 11),
                    other => panic!("unknown nf row {other}"),
                };
                let mut state = ServerPeerAddrState::new(false);
                let mut banned: BTreeMap<String, i64> = BTreeMap::new();
                let out = on_not_found(&mut state, true, &inv_list, false, ban_threshold, now);
                match name {
                    "invalidtype" => {
                        assert_eq!(out, OnNotFoundOutcome::DisconnectInvalidType);
                    }
                    "blocksban" => {
                        assert_eq!(out, OnNotFoundOutcome::Banned("6 blocks not found".into()));
                    }
                    "txflood" => {
                        assert_eq!(
                            out,
                            OnNotFoundOutcome::Banned("11 transactions not found".into())
                        );
                    }
                    "mixflood" => {
                        assert_eq!(
                            out,
                            OnNotFoundOutcome::Banned("11 mix messages not found".into())
                        );
                    }
                    _ => unreachable!(),
                }
                if matches!(out, OnNotFoundOutcome::Banned(_)) {
                    ban_peer(
                        &mut banned,
                        peer_addr,
                        false,
                        false,
                        ban_duration_nanos,
                        now * 1_000_000_000,
                    );
                }
                assert_eq!(banned_hosts(&banned), fields[2], "{name}");
                assert_eq!(fields[3], "false", "{name}: disconnected");
            }
            other => panic!("unknown row {other:?}"),
        }
    }
}
