// SPDX-License-Identifier: ISC
//! Replay of frozen external address discovery vectors generated by
//! an in-package dump driving dcrd's real hostToNetAddress, the LRU
//! under externalAddrCandidateCache, bestCandidate,
//! resolveExternalAddress, considerReportedAddrOutbound,
//! considerReportedAddr and handleAddPeer on live piped serverPeers
//! at 036b7090, reading the candidate cache and the address manager's
//! local addresses directly — the host encode and DNS fallback, LRU
//! promotion and eviction, the score tie-break, the listener match
//! and reachability arms of the local address resolution, every gate
//! that disables automatic discovery, the 60% majority threshold, the
//! score saturation, and the disjoint inbound key space that leaves
//! corroboration dead — compared row for row.

// Index and score arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]
// The `ecraothresh` rows pin dcrd's majority expression as dcrd
// spells it, `((targetOutbound*60)+99)/100`; `div_ceil` computes the
// same number but stops the row from reading as the transcription of
// an unsigned integer expression that it is.
#![allow(clippy::manual_div_ceil)]

use dcroxide_addrmgr::{AddrManager, NetAddressReach, NetAddressType};
use dcroxide_node::server::{
    AddPeerFacts, ExternalAddrCandidate, ExternalAddrCandidateCache, ExternalAddrFacts,
    MAX_EXTERNAL_ADDR_CANDIDATES, PeerState, consider_reported_addr,
    consider_reported_addr_outbound, handle_add_peer, host_to_net_address,
    resolve_external_address, wire_to_addrmgr_net_address,
};
use dcroxide_wire::{NetAddress, ServiceFlag};

const VECTORS: &str = include_str!("data/srvextaddr_vectors.txt");

/// A fixed base clock.  Every timestamp this subsystem stamps is
/// invisible in the rows, which carry only addresses, ports, types,
/// reachabilities and scores.
const NOW_NANOS: i64 = 1_750_000_000 * 1_000_000_000;
const NOW_UNIX: i64 = NOW_NANOS / 1_000_000_000;

/// The port every candidate and peer in the dump uses.
const PORT: u16 = 9108;

/// Render a wire address's 16-byte IP the way Go's `net.IP.String`
/// does; dcrd reads `candidate.addr.IP.String()` on the RAW WIRE IP
/// throughout this subsystem, both for the cache key and for the
/// address handed to `AddLocalAddress`.  An IPv4-mapped address
/// prints as a bare dotted quad with no `::ffff:` prefix, which is
/// the one place Go and Rust's own `Ipv6Addr` rendering disagree; the
/// remaining forms collapse the longest zero run identically.  dcrd's
/// renderer is `pub(crate)` in the port, so the row strings are
/// derived here from the wire bytes rather than by widening it.
fn wire_ip_string(ip: &[u8; 16]) -> String {
    let v6 = std::net::Ipv6Addr::from(*ip);
    match v6.to_ipv4_mapped() {
        Some(v4) => v4.to_string(),
        None => v6.to_string(),
    }
}

/// Go's `net.JoinHostPort`: an IPv6 literal is bracketed, everything
/// else is not.  dcrd builds the inbound corroboration lookup key
/// with it (`considerReportedAddr`); the port's copy lives in a
/// private module, so the `ecrakey` rows are reproduced here.
fn join_host_port(host: &str, port: u16) -> String {
    if host.contains(':') {
        format!("[{host}]:{port}")
    } else {
        format!("{host}:{port}")
    }
}

/// The dump's `wireAddr` (dcrd `wire.NewNetAddressTimestamp` with
/// `time.Unix(0, 0)`).
fn wire_addr(ip: &str, port: u16) -> NetAddress {
    let mut bytes = [0u8; 16];
    match ip.parse::<std::net::IpAddr>().expect("literal IP") {
        std::net::IpAddr::V4(v4) => {
            bytes[10] = 0xff;
            bytes[11] = 0xff;
            bytes[12..16].copy_from_slice(&v4.octets());
        }
        std::net::IpAddr::V6(v6) => bytes.copy_from_slice(&v6.octets()),
    }
    NetAddress {
        timestamp: 0,
        services: ServiceFlag::NODE_NETWORK,
        ip: bytes,
        port,
    }
}

/// The dump's `makePeer` remote address (dcrd
/// `addrmgr.NewNetAddressFromIPPort` on the address the peer
/// connected from); `handleAddPeer` derives the same bytes from the
/// peer's wire address.
fn remote_addr(ip: &str, port: u16) -> dcroxide_addrmgr::NetAddress {
    wire_to_addrmgr_net_address(&wire_addr(ip, port))
}

/// The dump's `candidate` helper.
fn candidate(
    ip: &str,
    net_type: NetAddressType,
    reach: NetAddressReach,
    score: u32,
) -> ExternalAddrCandidate {
    ExternalAddrCandidate {
        addr: wire_addr(ip, PORT),
        net_type,
        reach,
        score,
    }
}

/// The dump's `smallCache`: a candidate cache with a hand-chosen
/// limit so eviction and promotion are legible in four entries rather
/// than twenty.  Otherwise identical to
/// `ExternalAddrCandidateCache::new`.
fn small_cache(limit: u32) -> ExternalAddrCandidateCache {
    ExternalAddrCandidateCache {
        entries: dcroxide_containers::lru::Map::new(limit),
    }
}

/// The dump's `cacheStr`: the cache in LRU order (least recently used
/// first), which is exactly the order `keys`/`values` walk and
/// therefore the order `best_candidate` scans.  Neither call
/// promotes an entry.
fn cache_str(cache: &ExternalAddrCandidateCache) -> String {
    let keys = cache.entries.keys();
    let values = cache.entries.values();
    keys.iter()
        .zip(values.iter())
        .map(|(key, value)| {
            format!(
                "{key};{};{};{}",
                value.net_type as u8, value.reach as u8, value.score
            )
        })
        .collect::<Vec<String>>()
        .join(",")
}

/// The dump's `localStr`: the address manager's local addresses,
/// sorted, since dcrd's `LocalAddresses` walks a Go map.
fn local_str(addr_mgr: &AddrManager) -> String {
    let mut parts: Vec<String> = addr_mgr
        .local_addresses()
        .iter()
        .map(|la| format!("{};{}", la.address, la.port))
        .collect();
    parts.sort();
    parts.join(",")
}

/// The dump's `bestStr`.
fn best_str(cache: &ExternalAddrCandidateCache, net_type: NetAddressType) -> String {
    match cache.best_candidate(net_type) {
        None => "none".to_string(),
        Some(best) => format!("{};{}", wire_ip_string(&best.addr.ip), best.score),
    }
}

/// A fresh address manager on its own temporary directory, as the
/// dump's `newTestServer` does with `t.TempDir()`.  The handle is
/// returned with it so the directory outlives the manager.
fn new_amgr() -> (tempfile::TempDir, AddrManager) {
    let dir = tempfile::tempdir().expect("temp dir");
    let amgr = AddrManager::new(dir.path());
    (dir, amgr)
}

/// The subset of dcrd's package-level `cfg` global and `*server`
/// fields the external address subsystem reads, in the dump's
/// `cfgOpts` shape.  dcrd's `cfg.Proxy` and `cfg.OnionProxy` are one
/// boolean in the port (its gate is `cfg.Proxy != "" ||
/// cfg.OnionProxy != ""`), so the `gateproxy` and `gateonion` rows
/// spell the same fact twice.
#[derive(Default)]
struct CfgOpts {
    listeners: Vec<String>,
    proxy: bool,
    no_discover_ip: bool,
    external_ips: bool,
    disable_listen: bool,
    /// dcrd reads `s.chainParams.Name` here, not `cfg.SimNet`, which
    /// is why the dump can set the cfg boolean and still reach the
    /// discovery path under mainnet params.
    sim_or_reg_net: bool,
}

fn facts(opts: CfgOpts, target_outbound: u32) -> ExternalAddrFacts {
    ExternalAddrFacts {
        // dcrd's gate is `cfg.DisableListen || len(cfg.Listeners) == 0`.
        listen_disabled: opts.disable_listen || opts.listeners.is_empty(),
        listeners: opts.listeners,
        has_proxy: opts.proxy,
        no_discover_ip: opts.no_discover_ip,
        has_external_ips: opts.external_ips,
        sim_or_reg_net: opts.sim_or_reg_net,
        services: ServiceFlag::NODE_NETWORK,
        target_outbound,
    }
}

/// The dump's base listener set.
fn listeners() -> Vec<String> {
    vec!["0.0.0.0:9108".to_string()]
}

/// The dump's `makePeer` facts for `handleAddPeer`.
fn add_peer_facts(
    remote: &str,
    inbound: bool,
    reported: Option<NetAddress>,
    external: ExternalAddrFacts,
) -> AddPeerFacts {
    AddPeerFacts {
        shutdown: false,
        // dcrd assigns `sp.ID()` from `atomic.AddInt32(&nodeCount, 1)`
        // while handling the version message, and the dump's peers are
        // never started, so every one of them carries the zero value
        // and successive peers land under the same peer state key.
        // That is why the map lengths in the rows never exceed one.
        id: 0,
        addr: format!("{remote}:{PORT}"),
        inbound,
        persistent: false,
        is_whitelisted: false,
        na: wire_addr(remote, PORT),
        peer_na: reported,
        // dcrd 2.2 enforces the single-IP limit in the connection
        // manager; `handleAddPeer` no longer reads it.
        max_same_ip: 0,
        external,
    }
}

struct Rows<'a> {
    lines: std::str::Lines<'a>,
}

impl<'a> Rows<'a> {
    /// The next row, with its kind and label asserted so a reordered
    /// or dropped scenario fails loudly rather than silently
    /// comparing against the wrong row.
    fn next(&mut self, kind: &str, label: &str) -> Vec<&'a str> {
        let line = self.lines.next().expect("vector row");
        let fields: Vec<&str> = line.split('|').collect();
        assert_eq!(fields[0], kind, "row kind: {line}");
        assert_eq!(fields[1], label, "row order: {line}");
        fields
    }
}

/// The `eap` row shape: acceptance, the three peer state map
/// lengths, the candidate cache and the local addresses.
fn assert_add_peer_row(
    rows: &mut Rows<'_>,
    label: &str,
    accepted: bool,
    state: &PeerState,
    cache: &ExternalAddrCandidateCache,
    addr_mgr: &AddrManager,
) {
    let fields = rows.next("eap", label);
    assert_eq!(accepted.to_string(), fields[2], "accepted: {label}");
    assert_eq!(state.inbound_peers.len().to_string(), fields[3]);
    assert_eq!(state.outbound_peers.len().to_string(), fields[4]);
    assert_eq!(state.persistent_peers.len().to_string(), fields[5]);
    assert_eq!(cache_str(cache), fields[6], "cache: {label}");
    assert_eq!(local_str(addr_mgr), fields[7], "local: {label}");
}

#[test]
fn server_external_addresses_match_dcrd() {
    let mut rows = Rows {
        lines: VECTORS.lines(),
    };
    // `resolveExternalAddress` only ever hands `hostToNetAddress` an
    // IP literal, which `encode_host` recognizes, so this resolver is
    // never consulted outside the `ehost` section.
    let no_dns = |_: &str| -> Result<Vec<std::net::IpAddr>, String> { Err("no dns".to_string()) };

    // --- hostToNetAddress (dcrd `hostToNetAddress`) ---------------------
    const TOR_V3: &str = "xa4r2iadxm55fbnqgwwi5mymqdcofiu3w6rpbtqn7b2dyn7mgwj64jyd.onion";
    let resolver = |host: &str| -> Result<Vec<std::net::IpAddr>, String> {
        match host {
            "resolves.example" => Ok(vec![
                "93.184.216.34".parse().expect("literal IP"),
                "::1".parse().expect("literal IP"),
            ]),
            "empty.example" => Ok(Vec::new()),
            _ => Err(format!("lookup failed for {host}")),
        }
    };
    let hosts = [
        "8.8.8.8",
        "2001:4860:4860::8888",
        "::ffff:1.2.3.4",
        TOR_V3,
        "resolves.example",
        "empty.example",
        "fails.example",
    ];
    for host in hosts {
        let fields = rows.next("ehost", host);
        match host_to_net_address(host, 19108, ServiceFlag::NODE_NETWORK, &resolver, NOW_UNIX) {
            Ok(na) => {
                assert_eq!(fields[2], "ok", "host: {host}");
                assert_eq!(na.key(), fields[3]);
                assert_eq!((na.addr_type as u8).to_string(), fields[4]);
            }
            Err(err) => {
                assert_eq!(fields[2], "err", "host: {host}");
                assert_eq!(err, fields[3]);
            }
        }
    }

    // --- the LRU underneath the cache -----------------------------------
    let mut cache = small_cache(4);
    for ip in ["8.8.8.8", "1.2.3.4", "9.9.9.9", "1.1.1.1"] {
        cache.entries.put(
            ip.to_string(),
            candidate(ip, NetAddressType::IPv4, NetAddressReach::Ipv4, 1),
        );
    }
    let fields = rows.next("ecache", "filled");
    assert_eq!(cache_str(&cache), fields[2]);

    // Get promotes the entry to most recently used.
    assert!(
        cache.entries.get(&"8.8.8.8".to_string()).is_some(),
        "expected hit"
    );
    let fields = rows.next("ecache", "getpromotes");
    assert_eq!(cache_str(&cache), fields[2]);

    // Keys/Values do not promote; two renders in a row are identical.
    let fields = rows.next("ecache", "valuesnopromote");
    assert_eq!(cache_str(&cache), fields[2]);

    // Put over the limit evicts the least recently used entry (the
    // front of the rendered order).
    cache.entries.put(
        "5.6.7.8".to_string(),
        candidate("5.6.7.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 1),
    );
    let fields = rows.next("ecache", "evicted");
    assert_eq!(cache_str(&cache), fields[2]);

    // Put over an existing key replaces the value and promotes.
    cache.entries.put(
        "9.9.9.9".to_string(),
        candidate("9.9.9.9", NetAddressType::IPv4, NetAddressReach::Ipv4, 7),
    );
    let fields = rows.next("ecache", "putreplaces");
    assert_eq!(cache_str(&cache), fields[2]);

    // A miss does not promote anything.
    assert!(
        cache.entries.get(&"203.0.113.9".to_string()).is_none(),
        "expected miss"
    );
    let fields = rows.next("ecache", "missnopromote");
    assert_eq!(cache_str(&cache), fields[2]);

    // The real cache limit is `MAX_EXTERNAL_ADDR_CANDIDATES`.  Filling
    // it past the limit records how many survive and which was
    // dropped.
    let mut full = ExternalAddrCandidateCache::new();
    for i in 0..=MAX_EXTERNAL_ADDR_CANDIDATES {
        let ip = format!("8.8.{}.{}", i / 256, i % 256);
        full.entries.put(
            ip.clone(),
            candidate(&ip, NetAddressType::IPv4, NetAddressReach::Ipv4, 1),
        );
    }
    let fields = rows.next("ecache", "limit");
    assert_eq!(MAX_EXTERNAL_ADDR_CANDIDATES.to_string(), fields[2]);
    assert_eq!(full.entries.len().to_string(), fields[3]);
    assert_eq!(cache_str(&full), fields[4]);

    // --- bestCandidate (dcrd `bestCandidate`) ---------------------------
    let mut cache = small_cache(8);
    let fields = rows.next("ebest", "empty");
    assert_eq!((NetAddressType::IPv4 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&cache, NetAddressType::IPv4), fields[3]);

    cache.entries.put(
        "8.8.8.8".to_string(),
        candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 3),
    );
    cache.entries.put(
        "1.2.3.4".to_string(),
        candidate("1.2.3.4", NetAddressType::IPv4, NetAddressReach::Ipv4, 7),
    );
    cache.entries.put(
        "2001:4860:4860::8888".to_string(),
        candidate(
            "2001:4860:4860::8888",
            NetAddressType::IPv6,
            NetAddressReach::Ipv6Strong,
            2,
        ),
    );
    let fields = rows.next("ebest", "v4");
    assert_eq!((NetAddressType::IPv4 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&cache, NetAddressType::IPv4), fields[3]);
    let fields = rows.next("ebest", "v6");
    assert_eq!((NetAddressType::IPv6 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&cache, NetAddressType::IPv6), fields[3]);
    let fields = rows.next("ebest", "torv3none");
    assert_eq!((NetAddressType::TorV3 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&cache, NetAddressType::TorV3), fields[3]);

    // Ties: `best_candidate` keeps the first maximum it sees while
    // scanning from least to most recently used, so the older of two
    // tied candidates wins.
    let mut tie = small_cache(8);
    tie.entries.put(
        "8.8.8.8".to_string(),
        candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 5),
    );
    tie.entries.put(
        "1.2.3.4".to_string(),
        candidate("1.2.3.4", NetAddressType::IPv4, NetAddressReach::Ipv4, 5),
    );
    let fields = rows.next("ecache", "tieorder");
    assert_eq!(cache_str(&tie), fields[2]);
    let fields = rows.next("ebest", "tie");
    assert_eq!((NetAddressType::IPv4 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&tie, NetAddressType::IPv4), fields[3]);

    // Touching the older one promotes it to most recently used, which
    // flips which of the two tied candidates is returned.
    tie.entries.get(&"8.8.8.8".to_string());
    let fields = rows.next("ecache", "tieorderafterget");
    assert_eq!(cache_str(&tie), fields[2]);
    let fields = rows.next("ebest", "tieafterget");
    assert_eq!((NetAddressType::IPv4 as u8).to_string(), fields[2]);
    assert_eq!(best_str(&tie, NetAddressType::IPv4), fields[3]);

    // --- resolveExternalAddress (dcrd `resolveExternalAddress`) ---------
    let v4 = || candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 9);
    let v6 = |reach| candidate("2001:4860:4860::8888", NetAddressType::IPv6, reach, 9);
    let unroutable = || candidate("10.0.0.5", NetAddressType::IPv4, NetAddressReach::Ipv4, 9);
    let cases: Vec<(&str, Vec<&str>, ExternalAddrCandidate)> = vec![
        ("exactmatch", vec!["8.8.8.8:9108"], v4()),
        (
            "exactmatchv6",
            vec!["[2001:4860:4860::8888]:9108"],
            v6(NetAddressReach::Ipv6Strong),
        ),
        (
            "duplicatelisteners",
            vec!["8.8.8.8:9108", "8.8.8.8:9108"],
            v4(),
        ),
        ("genericlistener", vec![":9108"], v4()),
        ("externalv4", vec!["0.0.0.0:9108"], v4()),
        (
            "externalv6",
            vec!["[::]:9108"],
            v6(NetAddressReach::Ipv6Strong),
        ),
        (
            "externalv6weak",
            vec!["[2001:db8::1]:9108"],
            v6(NetAddressReach::Ipv6Weak),
        ),
        (
            "reachmismatch",
            vec!["0.0.0.0:9108"],
            v6(NetAddressReach::Ipv6Strong),
        ),
        ("v4candidatev6listener", vec!["[2001:db8::1]:9108"], v4()),
        (
            "zonedv6listener",
            vec!["[fe80::1%eth0]:9108"],
            v6(NetAddressReach::Ipv6Strong),
        ),
        ("multilistener", vec!["8.8.8.8:9108", "0.0.0.0:19108"], v4()),
        ("nolisteners", Vec::new(), v4()),
        // A listener that fails to split, parse its port, or parse its
        // host is skipped -- the remaining listeners are still
        // considered.
        ("badhostportskipped", vec!["bogus", "8.8.8.8:9108"], v4()),
        (
            "badportskipped",
            vec!["1.2.3.4:99999", "8.8.8.8:9108"],
            v4(),
        ),
        (
            "badiplistenerskipped",
            vec!["notanip:9108", "8.8.8.8:9108"],
            v4(),
        ),
        (
            "allbad",
            vec!["bogus", "1.2.3.4:99999", "notanip:9108"],
            v4(),
        ),
        // The third arm of the valid-external test: an IPv6 listener
        // accepts Ipv6Weak, Ipv6Strong and Teredo, but neither Default
        // nor Unreachable -- note `is_external_addr_candidate` DOES
        // accept Default for IPv6, so the two lists deliberately
        // disagree.
        (
            "externalv6teredo",
            vec!["[2001:db8::1]:9108"],
            v6(NetAddressReach::Teredo),
        ),
        (
            "externalv6default",
            vec!["[2001:db8::1]:9108"],
            v6(NetAddressReach::Default),
        ),
        (
            "externalv6unreachable",
            vec!["[2001:db8::1]:9108"],
            v6(NetAddressReach::Unreachable),
        ),
        // `add_local_address` rejects an unroutable address; the error
        // is logged and the listener loop moves on.
        ("unroutablecandidate", vec![":9108"], unroutable()),
    ];
    for (label, case_listeners, cand) in cases {
        let (_dir, mut amgr) = new_amgr();
        let case_facts = facts(
            CfgOpts {
                listeners: case_listeners.iter().map(|l| (*l).to_string()).collect(),
                ..CfgOpts::default()
            },
            8,
        );
        resolve_external_address(&cand, &mut amgr, &case_facts, &no_dns, NOW_UNIX);
        let fields = rows.next("erea", label);
        assert_eq!(local_str(&amgr), fields[2], "local: {label}");
    }

    // --- considerReportedAddrOutbound -----------------------------------
    // Every condition that disables automatic discovery.
    let gates: Vec<(&str, CfgOpts)> = vec![
        (
            "gateproxy",
            CfgOpts {
                listeners: listeners(),
                proxy: true,
                ..CfgOpts::default()
            },
        ),
        // dcrd's `cfg.OnionProxy` reaches the same disjunct as
        // `cfg.Proxy`; the port carries one boolean for both.
        (
            "gateonion",
            CfgOpts {
                listeners: listeners(),
                proxy: true,
                ..CfgOpts::default()
            },
        ),
        (
            "gatenodiscover",
            CfgOpts {
                listeners: listeners(),
                no_discover_ip: true,
                ..CfgOpts::default()
            },
        ),
        (
            "gateexternalip",
            CfgOpts {
                listeners: listeners(),
                external_ips: true,
                ..CfgOpts::default()
            },
        ),
        (
            "gatenolisten",
            CfgOpts {
                listeners: listeners(),
                disable_listen: true,
                ..CfgOpts::default()
            },
        ),
        // No listeners at all closes the same gate, and leaves
        // `resolve_external_address` nothing to walk.
        ("gatenolisteners", CfgOpts::default()),
        (
            "gatesimnet",
            CfgOpts {
                listeners: listeners(),
                sim_or_reg_net: true,
                ..CfgOpts::default()
            },
        ),
        (
            "gateregnet",
            CfgOpts {
                listeners: listeners(),
                sim_or_reg_net: true,
                ..CfgOpts::default()
            },
        ),
        (
            "gateopen",
            CfgOpts {
                listeners: listeners(),
                ..CfgOpts::default()
            },
        ),
    ];
    for (label, opts) in gates {
        let (_dir, mut amgr) = new_amgr();
        let mut cache = ExternalAddrCandidateCache::new();
        let gate_facts = facts(opts, 8);
        consider_reported_addr_outbound(
            &mut cache,
            &mut amgr,
            &wire_addr("8.8.8.8", PORT),
            &remote_addr("52.91.30.7", PORT),
            &gate_facts,
            &no_dns,
            NOW_UNIX,
        );
        let fields = rows.next("ecrao", label);
        assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
        assert_eq!(local_str(&amgr), fields[3], "local: {label}");
    }

    // Candidate rejection by the address manager.
    let rejects = [
        (
            "rejectv6candidatev4remote",
            "2001:4860:4860::8888",
            "52.91.30.7",
        ),
        ("rejectlocalcandidate", "127.0.0.1", "52.91.30.7"),
        ("rejectprivatecandidate", "10.0.0.5", "52.91.30.7"),
        ("rejectunroutableremote", "8.8.8.8", "10.0.0.5"),
        ("acceptv4", "8.8.8.8", "52.91.30.7"),
        ("acceptv6", "2001:4860:4860::8888", "2606:4700:4700::1111"),
    ];
    for (label, reported_ip, remote_ip) in rejects {
        let (_dir, mut amgr) = new_amgr();
        let mut cache = ExternalAddrCandidateCache::new();
        let reject_facts = facts(
            CfgOpts {
                listeners: listeners(),
                ..CfgOpts::default()
            },
            8,
        );
        consider_reported_addr_outbound(
            &mut cache,
            &mut amgr,
            &wire_addr(reported_ip, PORT),
            &remote_addr(remote_ip, PORT),
            &reject_facts,
            &no_dns,
            NOW_UNIX,
        );
        let fields = rows.next("ecrao", label);
        assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
        assert_eq!(local_str(&amgr), fields[3], "local: {label}");
    }

    // The majority threshold: `((target_outbound*60)+99)/100` reports
    // of the same address are needed before it is resolved into a
    // local address.  The expression is unsigned integer arithmetic,
    // not a float ceiling.
    for target in [0u32, 1, 2, 8, 125] {
        let (_dir, mut amgr) = new_amgr();
        let mut cache = ExternalAddrCandidateCache::new();
        let majority_facts = facts(
            CfgOpts {
                listeners: listeners(),
                ..CfgOpts::default()
            },
            target,
        );
        let fields = rows.next("ecraothresh", &target.to_string());
        assert_eq!((((target * 60) + 99) / 100).to_string(), fields[2]);
        for i in 1..=6u32 {
            consider_reported_addr_outbound(
                &mut cache,
                &mut amgr,
                &wire_addr("8.8.8.8", PORT),
                &remote_addr(&format!("52.91.30.{i}"), PORT),
                &majority_facts,
                &no_dns,
                NOW_UNIX,
            );
            let label = format!("majority-{target}-{i}");
            let fields = rows.next("ecrao", &label);
            assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
            assert_eq!(local_str(&amgr), fields[3], "local: {label}");
        }
    }

    // Two competing candidates: the one that reaches the threshold
    // first wins, and both keep accumulating score.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let compete_facts = facts(
        CfgOpts {
            listeners: listeners(),
            ..CfgOpts::default()
        },
        8,
    );
    let sequence = [
        "8.8.8.8", "9.9.9.9", "8.8.8.8", "9.9.9.9", "8.8.8.8", "8.8.8.8", "8.8.8.8", "9.9.9.9",
        "9.9.9.9", "9.9.9.9",
    ];
    for (index, ip) in sequence.iter().enumerate() {
        let nth = index + 1;
        consider_reported_addr_outbound(
            &mut cache,
            &mut amgr,
            &wire_addr(ip, PORT),
            &remote_addr(&format!("52.91.30.{nth}"), PORT),
            &compete_facts,
            &no_dns,
            NOW_UNIX,
        );
        let label = format!("compete-{nth}");
        let fields = rows.next("ecrao", &label);
        assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
        assert_eq!(local_str(&amgr), fields[3], "local: {label}");
    }

    // Score saturation: a candidate already at `u32::MAX` does not
    // wrap.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let saturate_facts = facts(
        CfgOpts {
            listeners: listeners(),
            ..CfgOpts::default()
        },
        8,
    );
    cache.entries.put(
        "8.8.8.8".to_string(),
        candidate(
            "8.8.8.8",
            NetAddressType::IPv4,
            NetAddressReach::Ipv4,
            u32::MAX,
        ),
    );
    consider_reported_addr_outbound(
        &mut cache,
        &mut amgr,
        &wire_addr("8.8.8.8", PORT),
        &remote_addr("52.91.30.7", PORT),
        &saturate_facts,
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecrao", "saturated");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // One below saturation still increments.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    cache.entries.put(
        "8.8.8.8".to_string(),
        candidate(
            "8.8.8.8",
            NetAddressType::IPv4,
            NetAddressReach::Ipv4,
            u32::MAX - 1,
        ),
    );
    consider_reported_addr_outbound(
        &mut cache,
        &mut amgr,
        &wire_addr("8.8.8.8", PORT),
        &remote_addr("52.91.30.7", PORT),
        &saturate_facts,
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecrao", "nearsaturated");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // An IPv6 candidate driven to the threshold through the real
    // path, so `best_candidate(IPv6)` is covered from
    // `consider_reported_addr_outbound` and not only from the
    // synthetic `ebest` rows.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let v6_facts = facts(
        CfgOpts {
            listeners: vec!["[::]:9108".to_string()],
            ..CfgOpts::default()
        },
        2,
    );
    for i in 1..=3u32 {
        consider_reported_addr_outbound(
            &mut cache,
            &mut amgr,
            &wire_addr("2001:4860:4860::8888", PORT),
            &remote_addr(&format!("2606:4700:4700::{i}"), PORT),
            &v6_facts,
            &no_dns,
            NOW_UNIX,
        );
        let label = format!("majorityv6-{i}");
        let fields = rows.next("ecrao", &label);
        assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
        assert_eq!(local_str(&amgr), fields[3], "local: {label}");
    }

    // Eviction through the real path rather than a direct put: one
    // more distinct reported address than the cache holds drops the
    // least recently used entry.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let evict_facts = facts(
        CfgOpts {
            listeners: listeners(),
            ..CfgOpts::default()
        },
        8,
    );
    for i in 0..=MAX_EXTERNAL_ADDR_CANDIDATES {
        consider_reported_addr_outbound(
            &mut cache,
            &mut amgr,
            &wire_addr(&format!("8.8.0.{i}"), PORT),
            &remote_addr("52.91.30.7", PORT),
            &evict_facts,
            &no_dns,
            NOW_UNIX,
        );
    }
    let fields = rows.next("ecrao", "evictreal");
    assert_eq!(cache.entries.len().to_string(), fields[2]);
    assert_eq!(cache_str(&cache), fields[3]);
    assert_eq!(local_str(&amgr), fields[4]);

    // --- considerReportedAddr -------------------------------------------
    // The nil and routability gates, exercised through an outbound
    // peer so a pass would otherwise reach the outbound path.
    let gate_cases: Vec<(&str, Option<NetAddress>, bool)> = vec![
        ("niladdr", None, false),
        ("niladdrinbound", None, true),
        (
            "unroutableprivate",
            Some(wire_addr("10.0.0.5", PORT)),
            false,
        ),
        (
            "unroutableloopback",
            Some(wire_addr("127.0.0.1", PORT)),
            false,
        ),
        (
            "unroutablelinklocal",
            Some(wire_addr("169.254.1.1", PORT)),
            false,
        ),
        (
            "unroutabletestnet",
            Some(wire_addr("203.0.113.7", PORT)),
            false,
        ),
        (
            "unroutableuniquelocal",
            Some(wire_addr("fc00::1", PORT)),
            false,
        ),
        ("routableoutbound", Some(wire_addr("8.8.8.8", PORT)), false),
    ];
    let reported_facts = || {
        facts(
            CfgOpts {
                listeners: listeners(),
                ..CfgOpts::default()
            },
            8,
        )
    };
    for (label, addr, inbound) in gate_cases {
        let (_dir, mut amgr) = new_amgr();
        let mut cache = ExternalAddrCandidateCache::new();
        consider_reported_addr(
            &mut cache,
            &mut amgr,
            addr.as_ref(),
            inbound,
            &remote_addr("52.91.30.7", PORT),
            &reported_facts(),
            &no_dns,
            NOW_UNIX,
        );
        let fields = rows.next("ecra", label);
        assert_eq!(cache_str(&cache), fields[2], "cache: {label}");
        assert_eq!(local_str(&amgr), fields[3], "local: {label}");
    }

    // Inbound peers never create candidates.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    consider_reported_addr(
        &mut cache,
        &mut amgr,
        Some(&wire_addr("8.8.8.8", PORT)),
        true,
        &remote_addr("52.91.30.7", PORT),
        &reported_facts(),
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecra", "inboundnocreate");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // THE HEADLINE ROWS (QK-0013).  The outbound path keys candidates
    // by the bare IP string; the inbound path looks them up by
    // `net.JoinHostPort(ip, port)`.  The two key spaces never
    // intersect, so an inbound peer can never bump the score of a
    // candidate the outbound path created.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    consider_reported_addr(
        &mut cache,
        &mut amgr,
        Some(&wire_addr("8.8.8.8", PORT)),
        false,
        &remote_addr("52.91.30.7", PORT),
        &reported_facts(),
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecra", "beforeinbound");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);
    for _ in 0..3 {
        consider_reported_addr(
            &mut cache,
            &mut amgr,
            Some(&wire_addr("8.8.8.8", PORT)),
            true,
            &remote_addr("52.91.30.8", PORT),
            &reported_facts(),
            &no_dns,
            NOW_UNIX,
        );
    }
    let fields = rows.next("ecra", "afterinbound");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // The inbound lookup key, spelled out.  Seeding the cache under
    // the host:port key -- which no code path in dcrd ever writes --
    // is the only way an inbound peer's corroboration finds anything.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let bare_v4 = wire_ip_string(&wire_addr("8.8.8.8", PORT).ip);
    let joined = join_host_port(&bare_v4, PORT);
    let fields = rows.next("ecrakey", "v4");
    assert_eq!(bare_v4, fields[2]);
    assert_eq!(joined, fields[3]);
    cache.entries.put(
        joined.clone(),
        candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 1),
    );
    consider_reported_addr(
        &mut cache,
        &mut amgr,
        Some(&wire_addr("8.8.8.8", PORT)),
        true,
        &remote_addr("52.91.30.8", PORT),
        &reported_facts(),
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecra", "inboundhitjoinedkey");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    let bare_v6 = wire_ip_string(&wire_addr("2001:4860:4860::8888", PORT).ip);
    let fields = rows.next("ecrakey", "v6");
    assert_eq!(bare_v6, fields[2]);
    assert_eq!(join_host_port(&bare_v6, PORT), fields[3]);

    // A corroborated candidate at saturation does not wrap either.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    cache.entries.put(
        joined.clone(),
        candidate(
            "8.8.8.8",
            NetAddressType::IPv4,
            NetAddressReach::Ipv4,
            u32::MAX,
        ),
    );
    consider_reported_addr(
        &mut cache,
        &mut amgr,
        Some(&wire_addr("8.8.8.8", PORT)),
        true,
        &remote_addr("52.91.30.8", PORT),
        &reported_facts(),
        &no_dns,
        NOW_UNIX,
    );
    let fields = rows.next("ecra", "inboundsaturated");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // Corroboration alone never resolves a local address, even past
    // the majority threshold.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    cache.entries.put(
        joined.clone(),
        candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 0),
    );
    for _ in 0..10 {
        consider_reported_addr(
            &mut cache,
            &mut amgr,
            Some(&wire_addr("8.8.8.8", PORT)),
            true,
            &remote_addr("52.91.30.8", PORT),
            &reported_facts(),
            &no_dns,
            NOW_UNIX,
        );
    }
    let fields = rows.next("ecra", "inboundneverresolves");
    assert_eq!(cache_str(&cache), fields[2]);
    assert_eq!(local_str(&amgr), fields[3]);

    // --- handleAddPeer, only where it is reachable ----------------------
    // At the pin `handleAddPeer` calls `considerReportedAddr`
    // unconditionally, but the block above it dereferences
    // `s.syncManager` whenever the peer is outbound and listening is
    // enabled, so the shapes the dump could drive without a chain are
    // any inbound peer, an outbound peer with listening disabled, and
    // an outbound peer under `cfg.SimNet`/`cfg.RegNet` with mainnet
    // chain params.  The port has not wired that advertise block yet,
    // and its discovery gate reads the chain params rather than the
    // cfg booleans, so the last shape carries `sim_or_reg_net: false`
    // here -- which is exactly the distinction the rows pin.
    let reported = || Some(wire_addr("8.8.8.8", PORT));

    // Shutting down rejects the peer before anything else runs.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let mut peer_facts = add_peer_facts("52.91.30.7", true, reported(), reported_facts());
    peer_facts.shutdown = true;
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "shutdown",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // An inbound peer reaches `consider_reported_addr` and cannot
    // create a candidate, even with discovery fully enabled.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let peer_facts = add_peer_facts("52.91.30.7", true, reported(), reported_facts());
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "inboundnocreate",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // An inbound peer with nothing reported at all.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let peer_facts = add_peer_facts("52.91.30.7", true, None, reported_facts());
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "inboundnoreport",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // An inbound peer corroborating a candidate stored under the
    // host:port key the inbound path looks up.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    cache.entries.put(
        joined.clone(),
        candidate("8.8.8.8", NetAddressType::IPv4, NetAddressReach::Ipv4, 4),
    );
    let peer_facts = add_peer_facts("52.91.30.7", true, reported(), reported_facts());
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "inboundcorroborate",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // An outbound peer with listening disabled is placed in the
    // outbound map and its report is dropped by the discovery gate.
    let nolisten_facts = || {
        facts(
            CfgOpts {
                listeners: listeners(),
                disable_listen: true,
                ..CfgOpts::default()
            },
            8,
        )
    };
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let peer_facts = add_peer_facts("52.91.30.7", false, reported(), nolisten_facts());
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "outboundnolisten",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // The same, but persistent.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let mut peer_facts = add_peer_facts("52.91.30.7", false, reported(), nolisten_facts());
    peer_facts.persistent = true;
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "outboundpersistent",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    // The outbound discovery path, reached because the advertise
    // block's gate and the discovery gate read two DIFFERENT sources:
    // the dump set `cfg.SimNet` (skipping the block, and with it the
    // `syncManager.IsCurrent()` dereference) while leaving mainnet
    // chain params, which is what the discovery gate reads.  A port
    // that collapsed the two into one flag would fail these rows.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    for i in 1..=6u32 {
        let peer_facts = add_peer_facts(
            &format!("52.91.30.{i}"),
            false,
            reported(),
            reported_facts(),
        );
        let outcome = handle_add_peer(
            &mut state,
            &mut cache,
            &mut amgr,
            &peer_facts,
            &no_dns,
            NOW_NANOS,
        );
        assert_add_peer_row(
            &mut rows,
            &format!("outbounddiscovery-{i}"),
            outcome.rejected.is_none(),
            &state,
            &cache,
            &amgr,
        );
    }

    // The same through `cfg.RegNet`, to pin that both booleans skip
    // the block; the target outbound count of one puts the very first
    // report over the majority threshold.
    let (_dir, mut amgr) = new_amgr();
    let mut cache = ExternalAddrCandidateCache::new();
    let mut state = PeerState::new();
    let peer_facts = add_peer_facts(
        "52.91.30.7",
        false,
        reported(),
        facts(
            CfgOpts {
                listeners: listeners(),
                ..CfgOpts::default()
            },
            1,
        ),
    );
    let outcome = handle_add_peer(
        &mut state,
        &mut cache,
        &mut amgr,
        &peer_facts,
        &no_dns,
        NOW_NANOS,
    );
    assert_add_peer_row(
        &mut rows,
        "outbounddiscoveryregnet",
        outcome.rejected.is_none(),
        &state,
        &cache,
        &amgr,
    );

    assert!(rows.lines.next().is_none(), "unconsumed vector rows");
}
