// SPDX-License-Identifier: ISC
//! Replay of frozen server inv and getdata intake gate vectors
//! generated by an in-package dump driving dcrd's real OnGetData and
//! OnInv on live piped serverPeers at release-v2.1.5, observing the
//! banned-host map, the connection state, and the pending getdata
//! item counter directly — the empty-request ban, the decaying
//! getdata ban score that warns on one full inventory query and bans
//! on the second, the small-request enqueue, the concurrent-request
//! and pending-item disconnects, and the inv empty-announcement ban
//! with the blocks-only transaction and mix disconnects — compared
//! row for row.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_node::server::{
    MAX_CONCURRENT_GETDATA_REQS, MAX_INV_PER_MSG, MAX_PENDING_GETDATA_ITEM_REQS, OnGetDataOutcome,
    OnInvOutcome, ServerPeerAddrState, on_get_data, on_inv_classify,
};
use dcroxide_wire::InvType;

const VECTORS: &str = include_str!("data/srvintake_vectors.txt");

const NOW_UNIX: i64 = 1_700_000_000;
const BAN_THRESHOLD: u32 = 100;
const PEER_HOST: &str = "10.0.0.2";

/// Look up a `gd|` row by its second field.
fn row<'a>(name: &str) -> Vec<&'a str> {
    VECTORS
        .lines()
        .map(|l| l.split('|').collect::<Vec<&str>>())
        .find(|f| f[0] == "gd" && f[1] == name)
        .unwrap_or_else(|| panic!("missing gd row {name}"))
}

/// The banned host recorded for a getdata/inv outcome that bans the
/// peer, and the resulting connection state.
struct BanState {
    banned: String,
    connected: bool,
    pending: u32,
}

#[test]
fn server_intake_gates_match_dcrd() {
    // --- getdata: empty request bans -------------------------------------
    let f = row("empty");
    let mut state = ServerPeerAddrState::new(false);
    let out = on_get_data(&mut state, 0, 0, 0, false, BAN_THRESHOLD, NOW_UNIX);
    assert_eq!(out, OnGetDataOutcome::BanEmpty);
    let bs = get_data_ban_state(out, 0);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);
    assert_eq!(bs.pending.to_string(), f[4]);

    // --- getdata: a small request enqueues --------------------------------
    let f = row("smallenqueue");
    let mut state = ServerPeerAddrState::new(false);
    let out = on_get_data(&mut state, 5, 0, 0, false, BAN_THRESHOLD, NOW_UNIX);
    let bs = get_data_ban_state(out, 0);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);
    assert_eq!(bs.pending.to_string(), f[4]);
    assert_eq!(
        out,
        OnGetDataOutcome::Enqueue {
            new_pending_items: 5
        }
    );

    // --- getdata: a full request warns but does not ban, then bans --------
    let f = row("scorewarn");
    let mut state = ServerPeerAddrState::new(false);
    let out = on_get_data(
        &mut state,
        MAX_INV_PER_MSG,
        0,
        0,
        false,
        BAN_THRESHOLD,
        NOW_UNIX,
    );
    let bs = get_data_ban_state(out, 0);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);
    assert_eq!(bs.pending.to_string(), f[4]);
    assert_eq!(
        out,
        OnGetDataOutcome::Enqueue {
            new_pending_items: MAX_INV_PER_MSG
        }
    );
    // A second full request on the same peer state crosses the ban
    // threshold; the pending count carries over from the first.
    let f = row("scoreban");
    let out = on_get_data(
        &mut state,
        MAX_INV_PER_MSG,
        1,
        MAX_INV_PER_MSG,
        false,
        BAN_THRESHOLD,
        NOW_UNIX,
    );
    assert_eq!(out, OnGetDataOutcome::BanScore);
    let bs = get_data_ban_state(out, MAX_INV_PER_MSG);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);

    // --- getdata: too many concurrent request batches disconnects ---------
    let f = row("concurrent");
    let mut state = ServerPeerAddrState::new(false);
    let out = on_get_data(
        &mut state,
        1,
        MAX_CONCURRENT_GETDATA_REQS,
        0,
        false,
        BAN_THRESHOLD,
        NOW_UNIX,
    );
    assert_eq!(out, OnGetDataOutcome::DisconnectConcurrent);
    let bs = get_data_ban_state(out, 0);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);

    // --- getdata: too many pending item requests disconnects --------------
    let f = row("pendingitems");
    let mut state = ServerPeerAddrState::new(false);
    let out = on_get_data(
        &mut state,
        10,
        0,
        MAX_PENDING_GETDATA_ITEM_REQS - 5,
        false,
        BAN_THRESHOLD,
        NOW_UNIX,
    );
    assert_eq!(out, OnGetDataOutcome::DisconnectPendingItems);
    let bs = get_data_ban_state(out, 0);
    assert_eq!(bs.banned, f[2]);
    assert_eq!(bs.connected.to_string(), f[3]);

    // --- inv: empty announcement bans -------------------------------------
    let f = iv_row("empty");
    let out = on_inv_classify(&[], false);
    assert_eq!(out, OnInvOutcome::BanEmpty);
    let (banned, connected) = inv_ban_state(out);
    assert_eq!(banned, f[2]);
    assert_eq!(connected.to_string(), f[3]);

    // --- inv: blocksonly disconnects a transaction announcement -----------
    let f = iv_row("blocksonlytx");
    let out = on_inv_classify(&[InvType::BLOCK, InvType::TX], true);
    assert_eq!(out, OnInvOutcome::DisconnectAnnouncement("transactions"));
    let (banned, connected) = inv_ban_state(out);
    assert_eq!(banned, f[2]);
    assert_eq!(connected.to_string(), f[3]);

    // --- inv: blocksonly disconnects a mix announcement -------------------
    let f = iv_row("blocksonlymix");
    let out = on_inv_classify(&[InvType::MIX], true);
    assert_eq!(out, OnInvOutcome::DisconnectAnnouncement("mix messages"));
    let (banned, connected) = inv_ban_state(out);
    assert_eq!(banned, f[2]);
    assert_eq!(connected.to_string(), f[3]);

    // The non-blocks-only and blocks-only-blocks paths forward to the
    // ported sync manager, which is not reachable from this dump; the
    // classification is still exercised here.
    assert_eq!(
        on_inv_classify(&[InvType::TX], false),
        OnInvOutcome::Forward
    );
    assert_eq!(
        on_inv_classify(&[InvType::BLOCK, InvType::BLOCK], true),
        OnInvOutcome::Forward
    );
}

/// Map a getdata outcome to the observable ban, connection, and
/// pending state dcrd exposes.  The empty and score bans disconnect
/// with the peer host recorded; the two capacity limits disconnect
/// without a ban; the enqueue keeps the peer connected.
fn get_data_ban_state(out: OnGetDataOutcome, prior_pending: u32) -> BanState {
    match out {
        OnGetDataOutcome::BanEmpty | OnGetDataOutcome::BanScore => BanState {
            banned: PEER_HOST.to_string(),
            connected: false,
            pending: prior_pending,
        },
        OnGetDataOutcome::DisconnectConcurrent | OnGetDataOutcome::DisconnectPendingItems => {
            BanState {
                banned: String::new(),
                connected: false,
                pending: prior_pending,
            }
        }
        OnGetDataOutcome::Enqueue { new_pending_items } => BanState {
            banned: String::new(),
            connected: true,
            pending: new_pending_items,
        },
    }
}

/// Map an inv outcome to the observable ban and connection state.
fn inv_ban_state(out: OnInvOutcome) -> (String, bool) {
    match out {
        OnInvOutcome::BanEmpty => (PEER_HOST.to_string(), false),
        OnInvOutcome::DisconnectAnnouncement(_) => (String::new(), false),
        OnInvOutcome::Forward => (String::new(), true),
    }
}

/// Look up an `iv|` row by its second field.
fn iv_row<'a>(name: &str) -> Vec<&'a str> {
    VECTORS
        .lines()
        .map(|l| l.split('|').collect::<Vec<&str>>())
        .find(|fields| fields[0] == "iv" && fields[1] == name)
        .unwrap_or_else(|| panic!("missing iv row {name}"))
}
