// SPDX-License-Identifier: ISC
//! Replay of frozen getdata serve queue vectors generated by an
//! in-package dump that built a real regnet chain from dcrd's own
//! fullblocktests generator with empty mempool and mix pools and drove
//! dcrd's real handleServeGetData over a live piped serverPeer at
//! release-v2.1.5.  Each row freezes the requested inventory with its
//! per-item fetch resolution (the chain/mempool/mixpool seams) and the
//! ordered sequence of messages the remote received, so this replay
//! checks the decision-core port reproduces dcrd's ordered data,
//! notfound, and continuation-inventory queueing along with the
//! pending-item decrements and the continuation-hash clearing.  The
//! block hashes differ per generation, so each row is self-contained.

// Index arithmetic over pinned vector rows and hex parsing.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chainhash::Hash;
use dcroxide_node::server::{GetDataResolution, ServeGetDataAction, serve_get_data};
use dcroxide_wire::{InvType, InvVect};

const VECTORS: &str = include_str!("data/srvservedata_vectors.txt");

fn parse_hash(s: &str) -> Hash {
    let bytes: Vec<u8> = (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect();
    let mut h = [0u8; 32];
    for (i, b) in bytes.iter().rev().enumerate() {
        h[i] = *b;
    }
    Hash(h)
}

fn inv_type(name: &str) -> InvType {
    match name {
        "block" => InvType::BLOCK,
        "tx" => InvType::TX,
        "mix" => InvType::MIX,
        _ => InvType::FILTERED_BLOCK,
    }
}

fn resolution(name: &str) -> GetDataResolution {
    match name {
        "found" => GetDataResolution::Found,
        "notfound" => GetDataResolution::NotFound,
        "unknown" => GetDataResolution::UnknownType,
        other => panic!("unknown resolution {other}"),
    }
}

/// Format a served action the way the dump's remote recorder does.
fn action_str(action: &ServeGetDataAction) -> String {
    match action {
        ServeGetDataAction::QueueData(iv) => {
            let kind = match iv.inv_type {
                InvType::BLOCK => "block",
                InvType::TX => "tx",
                InvType::MIX => "mix",
                _ => "other",
            };
            format!("{kind}:{}", iv.hash)
        }
        ServeGetDataAction::QueueContinueInv(_) => "inv:1".to_string(),
        ServeGetDataAction::QueueNotFound(invs) => format!("notfound:{}", invs.len()),
    }
}

#[test]
fn serve_get_data_matches_dcrd() {
    for line in VECTORS.lines() {
        // sd|name|items|contIn|seq|pending|cont
        let f: Vec<&str> = line.split('|').collect();
        assert_eq!(f[0], "sd");
        let name = f[1];

        let mut items: Vec<(InvVect, GetDataResolution)> = Vec::new();
        if !f[2].is_empty() {
            for item in f[2].split(';') {
                let parts: Vec<&str> = item.split(':').collect();
                let iv = InvVect {
                    inv_type: inv_type(parts[0]),
                    hash: parse_hash(parts[1]),
                };
                items.push((iv, resolution(parts[2])));
            }
        }

        let continue_hash = if f[3] == "nil" {
            None
        } else {
            Some(parse_hash(f[3]))
        };
        let expected_seq = f[4];
        let expected_pending: u32 = f[5].parse().unwrap();
        let expected_cont = f[6];

        // The best tip only feeds the continuation inventory, which is
        // observed as a count; any value reproduces the recorded form.
        let out = serve_get_data(&items, continue_hash, Hash([0u8; 32]));

        let got_seq = out
            .actions
            .iter()
            .map(action_str)
            .collect::<Vec<_>>()
            .join(",");
        assert_eq!(got_seq, expected_seq, "row {name} sequence");

        // The pending counter starts at the request count and is
        // decremented for served and not-found items.
        let final_pending = items.len() as u32 - out.pending_decrements;
        assert_eq!(final_pending, expected_pending, "row {name} pending");

        // The stored continuation hash remains set only when it was
        // provided and not cleared by serving its block.
        let final_cont = if continue_hash.is_some() && !out.cleared_continue_hash {
            "set"
        } else {
            "nil"
        };
        assert_eq!(final_cont, expected_cont, "row {name} continue hash");
    }
}
