// SPDX-License-Identifier: ISC
//! Replay of frozen server version handler vectors generated by an
//! in-package dump driving dcrd's real OnVersion directly on live
//! piped serverPeers at release-v2.1.5: the old-protocol and
//! missing-services rejections, the mix-capable maintenance
//! disconnect that deliberately falls through (the address manager
//! still marks the peer good), the outbound accept path with its
//! address manager updates and relay preference, the inbound and
//! simnet skips, and the verack sendheaders response — compared row
//! for row.

// Index arithmetic over pinned vector rows.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_addrmgr::{AddrManager, NetAddressType};
use dcroxide_node::server::{
    OnVersionFacts, ServerPeerAddrState, VersionRejection, on_ver_ack, on_version,
    wire_to_addrmgr_net_address,
};
use dcroxide_peer::{Peer, PeerEnv};
use dcroxide_wire::{
    MIX_VERSION, Message, NetAddress, PROTOCOL_VERSION, REMOVE_REJECT_VERSION, ServiceFlag,
};

const VECTORS: &str = include_str!("data/srvversion_vectors.txt");

struct FixedEnv;

impl PeerEnv for FixedEnv {
    fn now_nanos(&mut self) -> i64 {
        1_700_000_000 * 1_000_000_000
    }
    fn rand_u64(&mut self) -> u64 {
        1
    }
    fn shuffle_addrs(&mut self, _addrs: &mut [NetAddress]) {}
}

fn wire_addr(ip: &str, port: u16) -> NetAddress {
    let mut bytes = [0u8; 16];
    match ip.parse::<std::net::IpAddr>().unwrap() {
        std::net::IpAddr::V4(v4) => {
            bytes[10] = 0xff;
            bytes[11] = 0xff;
            bytes[12..16].copy_from_slice(&v4.octets());
        }
        std::net::IpAddr::V6(v6) => bytes.copy_from_slice(&v6.octets()),
    }
    NetAddress {
        timestamp: 1_700_000_000,
        services: ServiceFlag::NODE_NETWORK,
        ip: bytes,
        port,
    }
}

/// A shell mirroring the dump's seeded address manager.
fn seeded_amgr(dir: &std::path::Path, seed_remote: bool) -> AddrManager {
    let mut amgr = AddrManager::new(dir);
    if seed_remote {
        let na = wire_to_addrmgr_net_address(&wire_addr("52.91.77.2", 34567));
        let src = wire_to_addrmgr_net_address(&wire_addr("8.8.8.8", 9108));
        amgr.add_addresses(&[na], &src);
    }
    amgr
}

fn cache_len(amgr: &mut AddrManager) -> usize {
    amgr.address_cache(|_: NetAddressType| true).len()
}

#[test]
fn server_version_handler_matches_dcrd() {
    let remote_na = wire_addr("52.91.77.2", 34567);

    for line in VECTORS.lines() {
        let fields: Vec<&str> = line.split('|').collect();
        assert_eq!(fields[0], "sv");
        let name = fields[1];

        if name == "verack" {
            assert_eq!(on_ver_ack(), Message::SendHeaders);
            assert_eq!(fields[2], "true");
            continue;
        }

        let (inbound, sim_or_reg, seed, target_outbound, pver, services, disable_relay) = match name
        {
            "oldprotocol" => (
                false,
                false,
                false,
                8,
                REMOVE_REJECT_VERSION as i32 - 1,
                ServiceFlag::NODE_NETWORK,
                false,
            ),
            "missingservices" => (
                false,
                false,
                false,
                8,
                PROTOCOL_VERSION as i32,
                ServiceFlag(0),
                false,
            ),
            "mixdisconnect" => (
                false,
                false,
                true,
                3,
                MIX_VERSION as i32 - 1,
                ServiceFlag::NODE_NETWORK,
                false,
            ),
            "acceptoutbound" => (
                false,
                false,
                true,
                8,
                PROTOCOL_VERSION as i32,
                ServiceFlag::NODE_NETWORK,
                true,
            ),
            "acceptinbound" => (
                true,
                false,
                true,
                8,
                PROTOCOL_VERSION as i32,
                ServiceFlag::NODE_NETWORK,
                false,
            ),
            "simnet" => (
                false,
                true,
                true,
                8,
                PROTOCOL_VERSION as i32,
                ServiceFlag::NODE_NETWORK,
                false,
            ),
            other => panic!("unknown row {other}"),
        };

        let dir = tempfile::tempdir().unwrap();
        let mut amgr = seeded_amgr(dir.path(), seed);
        let mut state = ServerPeerAddrState::new(false);
        let mut peer = Peer::new_inbound(dcroxide_peer::Config::default());
        let facts = OnVersionFacts {
            inbound,
            sim_or_reg_net: sim_or_reg,
            disable_listen: true,
            sync_is_current: false,
            num_outbound: 0,
            num_mix_capable_outbound: 0,
            target_outbound,
            remote_na,
        };
        let out = on_version(
            &mut state,
            &mut peer,
            &mut FixedEnv,
            &mut amgr,
            &facts,
            pver,
            services,
            disable_relay,
        );

        // The connection state: every row ends disconnected — the
        // rejections and the mix maintenance disconnect directly,
        // and the accept rows through the zero max-peers admission.
        assert_eq!(fields[2], "false", "{name}");
        // The address cache after the handler.
        assert_eq!(cache_len(&mut amgr).to_string(), fields[3], "{name}");

        match name {
            "oldprotocol" => {
                assert_eq!(out.rejected, Some(VersionRejection::OldProtocol));
                assert!(out.set_services);
            }
            "missingservices" => {
                assert_eq!(out.rejected, Some(VersionRejection::MissingServices));
                assert!(!out.mix_disconnect);
            }
            "mixdisconnect" => {
                // The disconnect falls through, so the peer is
                // still marked good.
                assert_eq!(out.rejected, None);
                assert!(out.mix_disconnect);
                assert!(out.marked_good);
            }
            "acceptoutbound" => {
                assert_eq!(out.rejected, None);
                assert!(!out.mix_disconnect);
                assert!(out.marked_good);
                assert!(out.requested_more_addrs);
                assert_eq!(out.disable_relay_tx.to_string(), fields[4]);
                // The advertised address dcrd stores from AddrYou.
                assert_eq!(fields[5], "52.91.77.1:9108");
            }
            "acceptinbound" => {
                assert!(!out.set_services);
                assert!(!out.marked_good);
                assert_eq!(out.disable_relay_tx.to_string(), fields[4]);
            }
            "simnet" => {
                assert!(!out.set_services);
                assert!(!out.marked_good);
                assert!(!out.requested_more_addrs);
            }
            _ => unreachable!(),
        }
    }
}
