// SPDX-License-Identifier: ISC
//! Replay of frozen rpc/jsonrpc/types vectors generated by an
//! in-package dump test running inside dcrd's types package at
//! release-v2.1.5.
//!
//! The dump pins the full registered method set with per-method flags
//! and usage text, a zero-value marshal of every struct type (field
//! names, json tags, declaration order, omitempty, and base
//! encodings), curated populated command and result marshals, the
//! parameter-parsing default round trips, the five custom Vin
//! marshaling shapes, spot help generation, and the string constants.

use std::collections::HashMap;

use dcroxide_dcrjson::{CmdInstance, GoType, GoValue, Registry, RpcId, gojson, marshal_cmd};
use dcroxide_rpctypes::chainsvrcmds as cmds;
use dcroxide_rpctypes::chainsvrresults as results;
use dcroxide_rpctypes::chainsvrwscmds as wscmds;
use dcroxide_rpctypes::chainsvrwsntfns as ntfns;
use dcroxide_rpctypes::chainsvrwsresults as wsresults;
use dcroxide_rpctypes::{METHOD_TYPE_NAME, method, register_all};
use dcroxide_testutil::unhex;

const VECTORS: &str = include_str!("data/rpctypes_vectors.txt");

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).expect("utf8 payload")
}

fn s(v: &str) -> GoValue {
    GoValue::String(v.to_string())
}

fn strings(items: &[&str]) -> GoValue {
    GoValue::Array(items.iter().map(|v| s(v)).collect())
}

/// Every struct type in the package, keyed by its Go type name, for
/// the zero-value marshal battery.
fn all_types() -> Vec<(&'static str, GoType)> {
    vec![
        ("AddNodeCmd", cmds::add_node_cmd()),
        ("SStxInput", cmds::sstx_input()),
        ("SStxCommitOut", cmds::sstx_commit_out()),
        ("CreateRawSStxCmd", cmds::create_raw_sstx_cmd()),
        ("CreateRawSSRtxCmd", cmds::create_raw_ssrtx_cmd()),
        ("TransactionInput", cmds::transaction_input()),
        (
            "CreateRawTransactionCmd",
            cmds::create_raw_transaction_cmd(),
        ),
        ("DebugLevelCmd", cmds::debug_level_cmd()),
        (
            "DecodeRawTransactionCmd",
            cmds::decode_raw_transaction_cmd(),
        ),
        ("DecodeScriptCmd", cmds::decode_script_cmd()),
        ("EstimateFeeCmd", cmds::estimate_fee_cmd()),
        ("EstimateSmartFeeCmd", cmds::estimate_smart_fee_cmd()),
        ("EstimateStakeDiffCmd", cmds::estimate_stake_diff_cmd()),
        ("ExistsAddressCmd", cmds::exists_address_cmd()),
        ("ExistsAddressesCmd", cmds::exists_addresses_cmd()),
        ("ExistsLiveTicketCmd", cmds::exists_live_ticket_cmd()),
        ("ExistsLiveTicketsCmd", cmds::exists_live_tickets_cmd()),
        ("ExistsMempoolTxsCmd", cmds::exists_mempool_txs_cmd()),
        ("GenerateCmd", cmds::generate_cmd()),
        ("GetAddedNodeInfoCmd", cmds::get_added_node_info_cmd()),
        ("GetBestBlockCmd", cmds::get_best_block_cmd()),
        ("GetBestBlockHashCmd", cmds::get_best_block_hash_cmd()),
        ("GetBlockCmd", cmds::get_block_cmd()),
        ("GetBlockChainInfoCmd", cmds::get_block_chain_info_cmd()),
        ("GetBlockCountCmd", cmds::get_block_count_cmd()),
        ("GetBlockHashCmd", cmds::get_block_hash_cmd()),
        ("GetBlockHeaderCmd", cmds::get_block_header_cmd()),
        ("GetBlockSubsidyCmd", cmds::get_block_subsidy_cmd()),
        ("GetCFilterV2Cmd", cmds::get_cfilter_v2_cmd()),
        ("GetChainTipsCmd", cmds::get_chain_tips_cmd()),
        ("GetCoinSupplyCmd", cmds::get_coin_supply_cmd()),
        ("GetConnectionCountCmd", cmds::get_connection_count_cmd()),
        ("GetCurrentNetCmd", cmds::get_current_net_cmd()),
        ("GetDifficultyCmd", cmds::get_difficulty_cmd()),
        ("GetGenerateCmd", cmds::get_generate_cmd()),
        ("GetHashesPerSecCmd", cmds::get_hashes_per_sec_cmd()),
        ("GetHeadersCmd", cmds::get_headers_cmd()),
        ("GetInfoCmd", cmds::get_info_cmd()),
        ("GetMempoolInfoCmd", cmds::get_mempool_info_cmd()),
        ("GetMiningInfoCmd", cmds::get_mining_info_cmd()),
        ("GetMixMessageCmd", cmds::get_mix_message_cmd()),
        ("GetMixPairRequestsCmd", cmds::get_mix_pair_requests_cmd()),
        ("GetNetworkInfoCmd", cmds::get_network_info_cmd()),
        ("GetNetTotalsCmd", cmds::get_net_totals_cmd()),
        ("GetNetworkHashPSCmd", cmds::get_network_hash_ps_cmd()),
        ("GetPeerInfoCmd", cmds::get_peer_info_cmd()),
        ("GetRawMempoolCmd", cmds::get_raw_mempool_cmd()),
        ("GetRawTransactionCmd", cmds::get_raw_transaction_cmd()),
        ("GetStakeDifficultyCmd", cmds::get_stake_difficulty_cmd()),
        ("GetStakeVersionInfoCmd", cmds::get_stake_version_info_cmd()),
        ("GetStakeVersionsCmd", cmds::get_stake_versions_cmd()),
        ("GetTicketPoolValueCmd", cmds::get_ticket_pool_value_cmd()),
        ("GetTxOutCmd", cmds::get_tx_out_cmd()),
        ("GetTxOutSetInfoCmd", cmds::get_tx_out_set_info_cmd()),
        ("GetVoteInfoCmd", cmds::get_vote_info_cmd()),
        ("GetTreasuryBalanceCmd", cmds::get_treasury_balance_cmd()),
        (
            "GetTreasurySpendVotesCmd",
            cmds::get_treasury_spend_votes_cmd(),
        ),
        ("GetWorkCmd", cmds::get_work_cmd()),
        ("RegenTemplateCmd", cmds::regen_template_cmd()),
        ("HelpCmd", cmds::help_cmd()),
        ("InvalidateBlockCmd", cmds::invalidate_block_cmd()),
        ("LiveTicketsCmd", cmds::live_tickets_cmd()),
        ("NodeCmd", cmds::node_cmd()),
        ("PingCmd", cmds::ping_cmd()),
        ("ReconsiderBlockCmd", cmds::reconsider_block_cmd()),
        ("SendRawMixMessageCmd", cmds::send_raw_mix_message_cmd()),
        ("SendRawTransactionCmd", cmds::send_raw_transaction_cmd()),
        ("SetGenerateCmd", cmds::set_generate_cmd()),
        ("StartProfilerCmd", cmds::start_profiler_cmd()),
        ("StopCmd", cmds::stop_cmd()),
        ("StopProfilerCmd", cmds::stop_profiler_cmd()),
        ("SubmitBlockOptions", cmds::submit_block_options()),
        ("SubmitBlockCmd", cmds::submit_block_cmd()),
        ("TicketFeeInfoCmd", cmds::ticket_fee_info_cmd()),
        ("TicketsForAddressCmd", cmds::tickets_for_address_cmd()),
        ("TicketVWAPCmd", cmds::ticket_vwap_cmd()),
        ("TxFeeInfoCmd", cmds::tx_fee_info_cmd()),
        ("ValidateAddressCmd", cmds::validate_address_cmd()),
        ("VerifyChainCmd", cmds::verify_chain_cmd()),
        ("VerifyMessageCmd", cmds::verify_message_cmd()),
        ("VersionCmd", cmds::version_cmd()),
        ("AuthenticateCmd", wscmds::authenticate_cmd()),
        ("OutPoint", wscmds::out_point()),
        ("LoadTxFilterCmd", wscmds::load_tx_filter_cmd()),
        ("NotifyBlocksCmd", wscmds::notify_blocks_cmd()),
        ("NotifyWorkCmd", wscmds::notify_work_cmd()),
        ("NotifyTSpendCmd", wscmds::notify_tspend_cmd()),
        (
            "NotifyWinningTicketsCmd",
            wscmds::notify_winning_tickets_cmd(),
        ),
        ("NotifyNewTicketsCmd", wscmds::notify_new_tickets_cmd()),
        ("RebroadcastWinnersCmd", wscmds::rebroadcast_winners_cmd()),
        ("StopNotifyBlocksCmd", wscmds::stop_notify_blocks_cmd()),
        ("StopNotifyWorkCmd", wscmds::stop_notify_work_cmd()),
        ("StopNotifyTSpendCmd", wscmds::stop_notify_tspend_cmd()),
        (
            "NotifyNewTransactionsCmd",
            wscmds::notify_new_transactions_cmd(),
        ),
        ("NotifyMixMessagesCmd", wscmds::notify_mix_messages_cmd()),
        (
            "StopNotifyMixMessagesCmd",
            wscmds::stop_notify_mix_messages_cmd(),
        ),
        ("SessionCmd", wscmds::session_cmd()),
        (
            "StopNotifyNewTransactionsCmd",
            wscmds::stop_notify_new_transactions_cmd(),
        ),
        ("RescanCmd", wscmds::rescan_cmd()),
        ("BlockConnectedNtfn", ntfns::block_connected_ntfn()),
        ("BlockDisconnectedNtfn", ntfns::block_disconnected_ntfn()),
        ("NewTicketsNtfn", ntfns::new_tickets_ntfn()),
        ("WorkNtfn", ntfns::work_ntfn()),
        ("TSpendNtfn", ntfns::tspend_ntfn()),
        ("ReorganizationNtfn", ntfns::reorganization_ntfn()),
        ("TxAcceptedNtfn", ntfns::tx_accepted_ntfn()),
        ("TxAcceptedVerboseNtfn", ntfns::tx_accepted_verbose_ntfn()),
        ("RelevantTxAcceptedNtfn", ntfns::relevant_tx_accepted_ntfn()),
        ("WinningTicketsNtfn", ntfns::winning_tickets_ntfn()),
        ("MixMessageNtfn", ntfns::mix_message_ntfn()),
        ("TxRawDecodeResult", results::tx_raw_decode_result()),
        ("DecodeScriptResult", results::decode_script_result()),
        (
            "EstimateSmartFeeResult",
            results::estimate_smart_fee_result(),
        ),
        (
            "EstimateStakeDiffResult",
            results::estimate_stake_diff_result(),
        ),
        (
            "GetAddedNodeInfoResultAddr",
            results::get_added_node_info_result_addr(),
        ),
        (
            "GetAddedNodeInfoResult",
            results::get_added_node_info_result(),
        ),
        ("GetBlockVerboseResult", results::get_block_verbose_result()),
        ("AgendaInfo", results::agenda_info()),
        ("GetBestBlockResult", results::get_best_block_result()),
        (
            "GetBlockChainInfoResult",
            results::get_block_chain_info_result(),
        ),
        (
            "GetBlockHeaderVerboseResult",
            results::get_block_header_verbose_result(),
        ),
        ("GetBlockSubsidyResult", results::get_block_subsidy_result()),
        ("GetChainTipsResult", results::get_chain_tips_result()),
        ("GetCFilterV2Result", results::get_cfilter_v2_result()),
        ("GetHeadersResult", results::get_headers_result()),
        ("InfoChainResult", results::info_chain_result()),
        ("GetMempoolInfoResult", results::get_mempool_info_result()),
        ("GetMiningInfoResult", results::get_mining_info_result()),
        ("GetMixMessageResult", results::get_mix_message_result()),
        ("LocalAddressesResult", results::local_addresses_result()),
        ("NetworksResult", results::networks_result()),
        ("GetNetworkInfoResult", results::get_network_info_result()),
        ("GetNetTotalsResult", results::get_net_totals_result()),
        ("GetPeerInfoResult", results::get_peer_info_result()),
        (
            "GetRawMempoolVerboseResult",
            results::get_raw_mempool_verbose_result(),
        ),
        ("TxRawResult", results::tx_raw_result()),
        (
            "GetStakeDifficultyResult",
            results::get_stake_difficulty_result(),
        ),
        ("VersionCount", results::version_count()),
        ("VersionInterval", results::version_interval()),
        (
            "GetStakeVersionInfoResult",
            results::get_stake_version_info_result(),
        ),
        ("VersionBits", results::version_bits()),
        ("StakeVersions", results::stake_versions()),
        (
            "GetStakeVersionsResult",
            results::get_stake_versions_result(),
        ),
        ("GetTxOutResult", results::get_tx_out_result()),
        (
            "GetTxOutSetInfoResult",
            results::get_tx_out_set_info_result(),
        ),
        ("Choice", results::choice()),
        ("Agenda", results::agenda()),
        ("GetVoteInfoResult", results::get_vote_info_result()),
        (
            "GetTreasuryBalanceResult",
            results::get_treasury_balance_result(),
        ),
        ("TreasurySpendVotes", results::treasury_spend_votes()),
        (
            "GetTreasurySpendVotesResult",
            results::get_treasury_spend_votes_result(),
        ),
        ("GetWorkResult", results::get_work_result()),
        ("Ticket", results::ticket()),
        ("LiveTicketsResult", results::live_tickets_result()),
        ("StartProfilerResult", results::start_profiler_result()),
        ("FeeInfoBlock", results::fee_info_block()),
        ("FeeInfoMempool", results::fee_info_mempool()),
        ("FeeInfoRange", results::fee_info_range()),
        ("FeeInfoWindow", results::fee_info_window()),
        ("TicketFeeInfoResult", results::ticket_fee_info_result()),
        ("TxFeeInfoResult", results::tx_fee_info_result()),
        (
            "TicketsForAddressResult",
            results::tickets_for_address_result(),
        ),
        (
            "ValidateAddressChainResult",
            results::validate_address_chain_result(),
        ),
        ("VersionResult", results::version_result()),
        ("ScriptPubKeyResult", results::script_pub_key_result()),
        ("ScriptSig", results::script_sig()),
        ("Vin", results::vin()),
        ("Vout", results::vout()),
        ("SessionResult", wsresults::session_result()),
        ("RescanResult", wsresults::rescan_result()),
        ("RescannedBlock", wsresults::rescanned_block()),
    ]
}

/// The five Vin shapes from the dump plus the sigless regular input,
/// as full 12-field values of the [`results::vin`] descriptor.
fn vin_values() -> Vec<(&'static str, GoValue)> {
    let vin = |coinbase: &str,
               stakebase: &str,
               treasurybase: bool,
               treasury_spend: &str,
               txid: &str,
               vout: u64,
               tree: i64,
               sequence: u64,
               amount_in: f64,
               height: u64,
               index: u64,
               script_sig: GoValue| {
        GoValue::Struct(vec![
            s(coinbase),
            s(stakebase),
            GoValue::Bool(treasurybase),
            s(treasury_spend),
            s(txid),
            GoValue::Uint(vout),
            GoValue::Int(tree),
            GoValue::Uint(sequence),
            GoValue::Float64(amount_in),
            GoValue::Uint(height),
            GoValue::Uint(index),
            script_sig,
        ])
    };
    let sig = GoValue::Struct(vec![s("a<sm"), s("aabb")]);
    vec![
        (
            "coinbase",
            vin(
                "cbscript",
                "",
                false,
                "",
                "",
                0,
                0,
                4294967295,
                31.19,
                12,
                0,
                GoValue::Null,
            ),
        ),
        (
            "stakebase",
            vin(
                "",
                "sbscript",
                false,
                "",
                "",
                0,
                0,
                1,
                0.5,
                13,
                1,
                GoValue::Null,
            ),
        ),
        (
            "treasurybase",
            vin("", "", true, "", "", 0, 0, 2, 10.75, 14, 2, GoValue::Null),
        ),
        (
            "treasuryspend",
            vin(
                "",
                "",
                false,
                "tsscript",
                "",
                0,
                0,
                3,
                1e-8,
                15,
                3,
                GoValue::Null,
            ),
        ),
        (
            "regular",
            vin("", "", false, "", "t9", 3, 1, 4, 2.5, 16, 4, sig),
        ),
        (
            "regular-nosig",
            vin("", "", false, "", "t", 1, -1, 5, 0.25, 0, 0, GoValue::Null),
        ),
    ]
}

/// The populated TxRawResult from the dump, with the Vin slice carried
/// as raw pre-marshalled values exactly as a caller embeds custom
/// marshaler output.
fn raw_tx_value() -> GoValue {
    let vins: Vec<GoValue> = vin_values()
        .into_iter()
        .take(5)
        .map(|(_, v)| GoValue::Raw(results::marshal_vin(&v)))
        .collect();
    let spk = GoValue::Struct(vec![
        s("OP_DUP"),
        s("76a9"),
        GoValue::Int(1),
        s("pubkeyhash"),
        strings(&["Ds1"]),
        GoValue::Float64(0.5),
        GoValue::Uint(7),
    ]);
    let vout = GoValue::Struct(vec![
        GoValue::Float64(1.25),
        GoValue::Uint(0),
        GoValue::Uint(2),
        spk,
    ]);
    GoValue::Struct(vec![
        s("00ff"),
        s("txid9"),
        GoValue::Int(3),
        GoValue::Uint(8),
        GoValue::Uint(9),
        GoValue::Array(vins),
        GoValue::Array(vec![vout]),
        s("bh"),
        GoValue::Int(55),
        GoValue::Uint(2),
        GoValue::Int(10),
        GoValue::Int(1700000000),
        GoValue::Int(1700000001),
    ])
}

/// The curated command marshal battery, in dump order.
fn marshalcmd_battery() -> Vec<(&'static str, RpcId, CmdInstance)> {
    let one = RpcId::Int(1);
    let ntfn = RpcId::Null;
    vec![
        (
            "addnode",
            one.clone(),
            CmdInstance::new(
                cmds::add_node_cmd().ptr(),
                vec![s("127.0.0.1"), s("remove")],
            ),
        ),
        (
            "createrawsstx",
            one.clone(),
            CmdInstance::new(
                cmds::create_raw_sstx_cmd().ptr(),
                vec![
                    GoValue::Array(vec![GoValue::Struct(vec![
                        s("t1"),
                        GoValue::Uint(2),
                        GoValue::Int(1),
                        GoValue::Int(100000000),
                    ])]),
                    GoValue::Map(vec![
                        ("DsAddr2".to_string(), GoValue::Int(50)),
                        ("DsAddr1".to_string(), GoValue::Int(100000000)),
                    ]),
                    GoValue::Array(vec![GoValue::Struct(vec![
                        s("c1"),
                        GoValue::Int(99),
                        s("ch1"),
                        GoValue::Int(1),
                    ])]),
                ],
            ),
        ),
        (
            "createrawtransaction",
            one.clone(),
            CmdInstance::new(
                cmds::create_raw_transaction_cmd().ptr(),
                vec![
                    GoValue::Array(vec![
                        GoValue::Struct(vec![
                            GoValue::Float64(0.0),
                            s("t1"),
                            GoValue::Uint(0),
                            GoValue::Int(0),
                        ]),
                        GoValue::Struct(vec![
                            GoValue::Float64(1.5),
                            s("t2"),
                            GoValue::Uint(7),
                            GoValue::Int(1),
                        ]),
                    ]),
                    GoValue::Map(vec![
                        ("zeta".to_string(), GoValue::Float64(0.5)),
                        ("alpha".to_string(), GoValue::Float64(1e-8)),
                    ]),
                    GoValue::Int(12345),
                    GoValue::Int(6789),
                ],
            ),
        ),
        (
            "estimatesmartfee-cut",
            one.clone(),
            CmdInstance::new(
                cmds::estimate_smart_fee_cmd().ptr(),
                vec![GoValue::Int(6), GoValue::Null],
            ),
        ),
        (
            "estimatesmartfee-full",
            one.clone(),
            CmdInstance::new(
                cmds::estimate_smart_fee_cmd().ptr(),
                vec![GoValue::Int(6), s("economical")],
            ),
        ),
        (
            "getblock-min",
            one.clone(),
            CmdInstance::new(
                cmds::get_block_cmd().ptr(),
                vec![s("h"), GoValue::Null, GoValue::Null],
            ),
        ),
        (
            "getblock-full",
            one.clone(),
            CmdInstance::new(
                cmds::get_block_cmd().ptr(),
                vec![s("h"), GoValue::Bool(false), GoValue::Bool(true)],
            ),
        ),
        (
            "getheaders",
            one.clone(),
            CmdInstance::new(
                cmds::get_headers_cmd().ptr(),
                vec![strings(&["l1", "l2"]), s("stop")],
            ),
        ),
        (
            "gettxout",
            one.clone(),
            CmdInstance::new(
                cmds::get_tx_out_cmd().ptr(),
                vec![
                    s("t"),
                    GoValue::Uint(4),
                    GoValue::Int(-1),
                    GoValue::Bool(false),
                ],
            ),
        ),
        (
            "node-cut",
            one.clone(),
            CmdInstance::new(
                cmds::node_cmd().ptr(),
                vec![s("connect"), s("1.1.1.1:9108"), GoValue::Null],
            ),
        ),
        (
            "node-full",
            one.clone(),
            CmdInstance::new(
                cmds::node_cmd().ptr(),
                vec![s("disconnect"), s("1.1.1.1:9108"), s("perm")],
            ),
        ),
        (
            "submitblock-cut",
            one.clone(),
            CmdInstance::new(
                cmds::submit_block_cmd().ptr(),
                vec![s("aabb"), GoValue::Null],
            ),
        ),
        (
            "submitblock-opts",
            one.clone(),
            CmdInstance::new(
                cmds::submit_block_cmd().ptr(),
                vec![s("aabb"), GoValue::Struct(vec![s("w9")])],
            ),
        ),
        (
            "submitblock-emptyopts",
            one.clone(),
            CmdInstance::new(
                cmds::submit_block_cmd().ptr(),
                vec![s("aabb"), GoValue::Struct(vec![s("")])],
            ),
        ),
        (
            "loadtxfilter",
            one.clone(),
            CmdInstance::new(
                wscmds::load_tx_filter_cmd().ptr(),
                vec![
                    GoValue::Bool(true),
                    strings(&["a1", "a2"]),
                    GoValue::Array(vec![GoValue::Struct(vec![
                        s("h1"),
                        GoValue::Int(1),
                        GoValue::Uint(9),
                    ])]),
                ],
            ),
        ),
        (
            "notifynewtransactions",
            one.clone(),
            CmdInstance::new(
                wscmds::notify_new_transactions_cmd().ptr(),
                vec![GoValue::Bool(true)],
            ),
        ),
        (
            "sendrawmixmessage",
            one.clone(),
            CmdInstance::new(
                cmds::send_raw_mix_message_cmd().ptr(),
                vec![s("ke"), s("abcd")],
            ),
        ),
        (
            "getnetworkhashps",
            one.clone(),
            CmdInstance::new(
                cmds::get_network_hash_ps_cmd().ptr(),
                vec![GoValue::Int(200), GoValue::Null],
            ),
        ),
        (
            "gettreasuryspendvotes",
            one.clone(),
            CmdInstance::new(
                cmds::get_treasury_spend_votes_cmd().ptr(),
                vec![s("b"), strings(&["ts1", "ts2"])],
            ),
        ),
        (
            "ticketvwap",
            one.clone(),
            CmdInstance::new(
                cmds::ticket_vwap_cmd().ptr(),
                vec![GoValue::Uint(1), GoValue::Null],
            ),
        ),
        (
            "verifymessage",
            one.clone(),
            CmdInstance::new(
                cmds::verify_message_cmd().ptr(),
                vec![s("addr"), s("sig"), s("msg")],
            ),
        ),
        (
            "createrawssrtx",
            one.clone(),
            CmdInstance::new(
                cmds::create_raw_ssrtx_cmd().ptr(),
                vec![
                    GoValue::Array(vec![GoValue::Struct(vec![
                        GoValue::Float64(100.0),
                        s("t"),
                        GoValue::Uint(0),
                        GoValue::Int(1),
                    ])]),
                    GoValue::Float64(0.001),
                ],
            ),
        ),
        (
            "rescan",
            one.clone(),
            CmdInstance::new(wscmds::rescan_cmd().ptr(), vec![strings(&["b1", "b2"])]),
        ),
        (
            "ntfn-blockconnected",
            ntfn.clone(),
            CmdInstance::new(
                ntfns::block_connected_ntfn().ptr(),
                vec![s("deadbeef"), strings(&["tx1", "tx2"])],
            ),
        ),
        (
            "ntfn-winningtickets",
            ntfn.clone(),
            CmdInstance::new(
                ntfns::winning_tickets_ntfn().ptr(),
                vec![
                    s("bh"),
                    GoValue::Int(100),
                    GoValue::Map(vec![
                        ("2".to_string(), s("t2")),
                        ("1".to_string(), s("t1")),
                        ("10".to_string(), s("t10")),
                    ]),
                ],
            ),
        ),
        (
            "ntfn-txacceptedverbose",
            ntfn,
            CmdInstance::new(
                ntfns::tx_accepted_verbose_ntfn().ptr(),
                vec![raw_tx_value()],
            ),
        ),
    ]
}

/// The parse-params round trip battery, in dump order.
fn parseparams_battery() -> Vec<(&'static str, &'static str, Vec<&'static str>)> {
    vec![
        ("getblock-defaults", "getblock", vec![r#""h""#]),
        ("estimatesmartfee-default", "estimatesmartfee", vec!["6"]),
        ("getnetworkhashps-defaults", "getnetworkhashps", vec![]),
        ("verifychain-defaults", "verifychain", vec![]),
        (
            "getrawtransaction-default",
            "getrawtransaction",
            vec![r#""t""#],
        ),
        ("gettxout-default", "gettxout", vec![r#""t""#, "1", "0"]),
        ("getrawmempool-defaults", "getrawmempool", vec![]),
        (
            "createrawtransaction",
            "createrawtransaction",
            vec![
                r#"[{"txid":"t1","vout":0,"tree":0},{"amount":1.5,"txid":"t2","vout":7,"tree":1}]"#,
                r#"{"zeta":0.5,"alpha":1e-8}"#,
            ],
        ),
        ("node-cut", "node", vec![r#""connect""#, r#""1.2.3.4""#]),
        (
            "loadtxfilter",
            "loadtxfilter",
            vec!["true", r#"["a1"]"#, r#"[{"hash":"h1","tree":1,"index":9}]"#],
        ),
        (
            "notifynewtransactions-default",
            "notifynewtransactions",
            vec![],
        ),
        (
            "sendrawtransaction-default",
            "sendrawtransaction",
            vec![r#""aa""#],
        ),
        (
            "submitblock-opts",
            "submitblock",
            vec![r#""aa""#, r#"{"workid":"w"}"#],
        ),
        ("getstakeversioninfo-cut", "getstakeversioninfo", vec![]),
    ]
}

/// The populated result marshal battery, in dump order.
fn resultmarshal_battery() -> Vec<(&'static str, GoType, GoValue)> {
    let agenda_info = |status: &str, since: i64, start: u64, expire: u64| {
        GoValue::Struct(vec![
            s(status),
            GoValue::Int(since),
            GoValue::Uint(start),
            GoValue::Uint(expire),
        ])
    };
    vec![
        ("txraw-vins", results::tx_raw_result(), raw_tx_value()),
        (
            "blockchaininfo",
            results::get_block_chain_info_result(),
            GoValue::Struct(vec![
                s("mainnet"),
                GoValue::Int(100),
                GoValue::Int(101),
                GoValue::Int(102),
                s("bb"),
                GoValue::Uint(486604799),
                GoValue::Float64(1.5),
                GoValue::Float64(0.75),
                s("cw"),
                GoValue::Bool(true),
                GoValue::Int(393216),
                GoValue::Map(vec![
                    (
                        "zeta".to_string(),
                        agenda_info(results::AGENDA_INFO_STATUS_ACTIVE, 5, 10, 20),
                    ),
                    (
                        "alpha".to_string(),
                        agenda_info(results::AGENDA_INFO_STATUS_DEFINED, 0, 11, 21),
                    ),
                ]),
            ]),
        ),
        (
            "stakediff-user",
            results::estimate_stake_diff_result(),
            GoValue::Struct(vec![
                GoValue::Float64(1.5),
                GoValue::Float64(3.5),
                GoValue::Float64(2.25),
                GoValue::Float64(2.5),
            ]),
        ),
        (
            "stakediff-nouser",
            results::estimate_stake_diff_result(),
            GoValue::Struct(vec![
                GoValue::Float64(1.5),
                GoValue::Float64(3.5),
                GoValue::Float64(2.25),
                GoValue::Null,
            ]),
        ),
        (
            "addednodeinfo",
            results::get_added_node_info_result(),
            GoValue::Struct(vec![
                s("127.0.0.1:9108"),
                GoValue::Bool(true),
                GoValue::Array(vec![GoValue::Struct(vec![
                    s("1.2.3.4:9108"),
                    s("outbound"),
                ])]),
            ]),
        ),
        (
            "validateaddress-valid",
            results::validate_address_chain_result(),
            GoValue::Struct(vec![GoValue::Bool(true), s("Ds1")]),
        ),
        (
            "validateaddress-invalid",
            results::validate_address_chain_result(),
            GoValue::Struct(vec![GoValue::Bool(false), s("")]),
        ),
        (
            "decodescript",
            results::decode_script_result(),
            GoValue::Struct(vec![
                s("OP_DUP"),
                GoValue::Int(0),
                s("pubkeyhash"),
                GoValue::Null,
                s("DcABC"),
            ]),
        ),
        (
            "voteinfo",
            results::get_vote_info_result(),
            GoValue::Struct(vec![
                GoValue::Int(1000),
                GoValue::Int(900),
                GoValue::Int(1100),
                s("vh"),
                GoValue::Uint(9),
                GoValue::Uint(4096),
                GoValue::Uint(8000),
                GoValue::Array(vec![GoValue::Struct(vec![
                    s("ag1"),
                    s("an agenda"),
                    GoValue::Uint(6),
                    GoValue::Uint(100),
                    GoValue::Uint(200),
                    s(results::AGENDA_INFO_STATUS_STARTED),
                    GoValue::Float64(0.5),
                    GoValue::Array(vec![
                        GoValue::Struct(vec![
                            s("abstain"),
                            s("abstain"),
                            GoValue::Uint(0),
                            GoValue::Bool(true),
                            GoValue::Bool(false),
                            GoValue::Uint(10),
                            GoValue::Float64(0.1),
                        ]),
                        GoValue::Struct(vec![
                            s("yes"),
                            s("yes"),
                            GoValue::Uint(2),
                            GoValue::Bool(false),
                            GoValue::Bool(false),
                            GoValue::Uint(90),
                            GoValue::Float64(0.9),
                        ]),
                    ]),
                ])]),
            ]),
        ),
        (
            "blockverbose",
            results::get_block_verbose_result(),
            GoValue::Struct(vec![
                s("bh"),
                s("pw"),
                GoValue::Int(3),
                GoValue::Int(1000),
                GoValue::Int(42),
                GoValue::Int(9),
                s("mr"),
                s("sr"),
                strings(&["t1", "t2"]),
                GoValue::Null,
                GoValue::Null,
                GoValue::Null,
                GoValue::Int(1700000000),
                GoValue::Int(1699999999),
                GoValue::Uint(7),
                GoValue::Uint(1),
                s("fs"),
                GoValue::Uint(5),
                GoValue::Uint(3),
                GoValue::Uint(1),
                GoValue::Uint(40960),
                s("1d00ffff"),
                GoValue::Float64(100.25),
                s("ed"),
                GoValue::Uint(9),
                GoValue::Float64(1.5),
                s("cw"),
                s("ph"),
                s(""),
            ]),
        ),
    ]
}

/// The string constant battery.
fn strconst(name: &str) -> &'static str {
    match name {
        "ANAdd" => cmds::AN_ADD,
        "ANRemove" => cmds::AN_REMOVE,
        "ANOneTry" => cmds::AN_ONE_TRY,
        "NConnect" => cmds::N_CONNECT,
        "NRemove" => cmds::N_REMOVE,
        "NDisconnect" => cmds::N_DISCONNECT,
        "EstimateSmartFeeEconomical" => cmds::ESTIMATE_SMART_FEE_ECONOMICAL,
        "EstimateSmartFeeConservative" => cmds::ESTIMATE_SMART_FEE_CONSERVATIVE,
        "GRMAll" => cmds::GRM_ALL,
        "GRMRegular" => cmds::GRM_REGULAR,
        "GRMTickets" => cmds::GRM_TICKETS,
        "GRMVotes" => cmds::GRM_VOTES,
        "GRMRevocations" => cmds::GRM_REVOCATIONS,
        "GRMTSpend" => cmds::GRM_TSPEND,
        "GRMTAdd" => cmds::GRM_TADD,
        "AgendaInfoStatusDefined" => results::AGENDA_INFO_STATUS_DEFINED,
        "AgendaInfoStatusStarted" => results::AGENDA_INFO_STATUS_STARTED,
        "AgendaInfoStatusLockedIn" => results::AGENDA_INFO_STATUS_LOCKED_IN,
        "AgendaInfoStatusActive" => results::AGENDA_INFO_STATUS_ACTIVE,
        "AgendaInfoStatusFailed" => results::AGENDA_INFO_STATUS_FAILED,
        "BlockConnectedNtfnMethod" => ntfns::BLOCK_CONNECTED_NTFN_METHOD,
        "BlockDisconnectedNtfnMethod" => ntfns::BLOCK_DISCONNECTED_NTFN_METHOD,
        "NewTicketsNtfnMethod" => ntfns::NEW_TICKETS_NTFN_METHOD,
        "WorkNtfnMethod" => ntfns::WORK_NTFN_METHOD,
        "TSpendNtfnMethod" => ntfns::TSPEND_NTFN_METHOD,
        "ReorganizationNtfnMethod" => ntfns::REORGANIZATION_NTFN_METHOD,
        "TxAcceptedNtfnMethod" => ntfns::TX_ACCEPTED_NTFN_METHOD,
        "TxAcceptedVerboseNtfnMethod" => ntfns::TX_ACCEPTED_VERBOSE_NTFN_METHOD,
        "RelevantTxAcceptedNtfnMethod" => ntfns::RELEVANT_TX_ACCEPTED_NTFN_METHOD,
        "WinningTicketsNtfnMethod" => ntfns::WINNING_TICKETS_NTFN_METHOD,
        "MixMessageNtfnMethod" => ntfns::MIX_MESSAGE_NTFN_METHOD,
        other => panic!("unknown constant {other}"),
    }
}

#[test]
fn rpctypes_vectors() {
    let mut registry = Registry::new();
    register_all(&mut registry);

    let types = all_types();
    let marshals = marshalcmd_battery();
    let parses = parseparams_battery();
    let result_marshals = resultmarshal_battery();
    let vins = vin_values();

    let mut counts: HashMap<&str, usize> = HashMap::new();
    let mut zero_idx = 0usize;
    let mut cmd_idx = 0usize;
    let mut pp_idx = 0usize;
    let mut res_idx = 0usize;
    let mut vin_idx = 0usize;

    for line in VECTORS.lines() {
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('|').collect();
        *counts.entry(parts[0]).or_insert(0) += 1;
        match parts[0] {
            "methods" => {
                let methods = registry.registered_methods(METHOD_TYPE_NAME);
                assert_eq!(methods.join(","), parts[1], "{line}");
            }
            "flags" => {
                let flags = registry.method_usage_flags(&method(parts[1])).unwrap();
                let want: u32 = parts[2].parse().unwrap();
                assert_eq!(flags.0, want, "{line}");
            }
            "usage" => {
                let usage = registry.method_usage_text(&method(parts[1])).unwrap();
                assert_eq!(usage, utf8(parts[2]), "{line}");
            }
            "zeromarshal" => {
                let (name, typ) = &types[zero_idx];
                zero_idx += 1;
                assert_eq!(*name, parts[1], "zeromarshal order for {line}");
                let encoded = gojson::encode(typ, &GoValue::zero(typ));
                assert_eq!(encoded, utf8(parts[2]), "{line}");
            }
            "marshalcmd" => {
                let (label, id, cmd) = &marshals[cmd_idx];
                cmd_idx += 1;
                assert_eq!(*label, parts[1], "marshalcmd order for {line}");
                let encoded = marshal_cmd(&registry, "1.0", id, cmd)
                    .unwrap_or_else(|e| panic!("{line}: {e}"));
                assert_eq!(encoded, utf8(parts[2]), "{line}");
            }
            "parseparams" => {
                let (label, m, params) = &parses[pp_idx];
                pp_idx += 1;
                assert_eq!(*label, parts[1], "parseparams order for {line}");
                let cmd = dcroxide_dcrjson::parse_params(&registry, &method(m), params)
                    .unwrap_or_else(|e| panic!("{line}: {e}"));
                let encoded = marshal_cmd(&registry, "1.0", &RpcId::Int(1), &cmd)
                    .unwrap_or_else(|e| panic!("{line}: {e}"));
                assert_eq!(encoded, utf8(parts[2]), "{line}");
            }
            "resultmarshal" => {
                let (label, typ, value) = &result_marshals[res_idx];
                res_idx += 1;
                assert_eq!(*label, parts[1], "resultmarshal order for {line}");
                let encoded = gojson::encode(typ, value);
                assert_eq!(encoded, utf8(parts[2]), "{line}");
            }
            "vin" => {
                let (label, value) = &vins[vin_idx];
                vin_idx += 1;
                assert_eq!(*label, parts[1], "vin order for {line}");
                assert_eq!(results::marshal_vin(value), utf8(parts[2]), "{line}");
            }
            "help" => {
                let result_type = match parts[1] {
                    "getblock" => results::get_block_verbose_result(),
                    "gettxout" => results::get_tx_out_result(),
                    "ticketfeeinfo" => results::ticket_fee_info_result(),
                    other => panic!("unknown help row {other}"),
                };
                let (help, err) = registry.generate_help(
                    &method(parts[1]),
                    &HashMap::new(),
                    &[Some(result_type.ptr())],
                );
                assert_eq!(help, utf8(parts[2]), "{line}");
                let err = err.unwrap_or_else(|| panic!("{line}: expected missing key"));
                assert_eq!(err.description, utf8(parts[3]), "{line}");
            }
            "strconst" => {
                assert_eq!(strconst(parts[1]), parts[2], "{line}");
            }
            other => panic!("unknown vector op {other}"),
        }
    }

    assert_eq!(zero_idx, types.len());
    assert_eq!(cmd_idx, marshals.len());
    assert_eq!(pp_idx, parses.len());
    assert_eq!(res_idx, result_marshals.len());
    assert_eq!(vin_idx, vins.len());
    let expected: &[(&str, usize)] = &[
        ("methods", 1),
        ("flags", 105),
        ("usage", 105),
        ("zeromarshal", 171),
        ("marshalcmd", 26),
        ("parseparams", 14),
        ("resultmarshal", 10),
        ("vin", 6),
        ("help", 3),
        ("strconst", 31),
    ];
    for (op, want) in expected {
        assert_eq!(counts.get(op), Some(want), "row count for {op}");
    }
}
