// SPDX-License-Identifier: ISC
//! The English help descriptions for the RPC server commands (dcrd
//! internal/rpcserver `helpDescsEnUS`), sorted by key.
//!
//! This table is generated from dcrd's map at the parity tag; its
//! contents are behaviorally pinned through the frozen per-method
//! help vectors, which compare the fully generated help text byte
//! for byte.

/// The `(key, description)` pairs of dcrd's `helpDescsEnUS` map.
#[rustfmt::skip]
pub static HELP_DESCS_EN_US: &[(&str, &str)] = &[
    ("addnode--synopsis", "Attempts to add or remove a persistent peer."),
    ("addnode-addr", "IP address and port of the peer to operate on"),
    ("addnode-subcmd", "'add' to add a persistent peer, 'remove' to remove a persistent peer, or 'onetry' to try a single connection to a peer"),
    ("agenda-choices", "All choices in this agenda."),
    ("agenda-description", "Description of this agenda."),
    ("agenda-expiretime", "Time agenda becomes invalid."),
    ("agenda-id", "Unique identifier of this agenda."),
    ("agenda-mask", "Agenda mask."),
    ("agenda-quorumprogress", "Progress of quorum reached."),
    ("agenda-starttime", "Time agenda becomes valid."),
    ("agenda-status", "Agenda status."),
    ("agendainfo-expiretime", "The expiry time of the voting period for the agenda."),
    ("agendainfo-since", "The block height of the first block to which the status applies."),
    ("agendainfo-starttime", "The start time of the voting period for the agenda."),
    ("agendainfo-status", "The deployment agenda's current status."),
    ("choice-bits", "Bits that identify this choice."),
    ("choice-count", "How many votes received."),
    ("choice-description", "Description of this choice."),
    ("choice-id", "Unique identifier of this choice."),
    ("choice-isabstain", "This choice is to abstain from change."),
    ("choice-isno", "Hard no choice (1 and only 1 per agenda)."),
    ("choice-progress", "Progress of the overall count."),
    ("createrawssrtx--result0", "Hex-encoded bytes of the serialized transaction"),
    ("createrawssrtx--synopsis", "Returns a new transaction spending the provided inputs and sending to the provided addresses.\nThe transaction inputs are not signed in the created transaction.\nThe signrawtransaction RPC command provided by wallet must be used to sign the resulting transaction."),
    ("createrawssrtx-fee", "The fee to apply to the revocation in coins"),
    ("createrawssrtx-inputs", "The input to the transaction"),
    ("createrawsstx--result0", "Hex-encoded bytes of the serialized transaction"),
    ("createrawsstx--synopsis", "Returns a new transaction spending the provided inputs and sending to the provided addresses.\nThe transaction inputs are not signed in the created transaction.\nThe signrawtransaction RPC command provided by wallet must be used to sign the resulting transaction."),
    ("createrawsstx-amount", "JSON object with the destination address as key and amount as value"),
    ("createrawsstx-amount--desc", "The destination address as the key and the amount in atoms as the value"),
    ("createrawsstx-amount--key", "address"),
    ("createrawsstx-amount--value", "n"),
    ("createrawsstx-couts", "Array of sstx commit outs to use"),
    ("createrawsstx-inputs", "The inputs to the transaction"),
    ("createrawtransaction--result0", "Hex-encoded bytes of the serialized transaction"),
    ("createrawtransaction--synopsis", "Returns a new transaction spending the provided inputs and sending to the provided addresses.\nThe transaction inputs are not signed in the created transaction.\nThe signrawtransaction RPC command provided by wallet must be used to sign the resulting transaction."),
    ("createrawtransaction-amounts", "JSON object with the destination addresses as keys and amounts as values"),
    ("createrawtransaction-amounts--desc", "The destination address as the key and the amount in coins as the value"),
    ("createrawtransaction-amounts--key", "address"),
    ("createrawtransaction-amounts--value", "n.nnn"),
    ("createrawtransaction-expiry", "Expiry value; a non-zero value when the transaction expiry"),
    ("createrawtransaction-inputs", "The inputs to the transaction"),
    ("createrawtransaction-locktime", "Locktime value; a non-zero value will also locktime-activate the inputs"),
    ("debuglevel--condition0", "levelspec!=show"),
    ("debuglevel--condition1", "levelspec=show"),
    ("debuglevel--result0", "The string 'Done.'"),
    ("debuglevel--result1", "The list of subsystems"),
    ("debuglevel--synopsis", "Dynamically changes the debug logging level.\nThe levelspec can either a debug level or of the form:\n<subsystem>=<level>,<subsystem2>=<level2>,...\nThe valid debug levels are trace, debug, info, warn, error, and critical.\nThe valid subsystems are AMGR, BCDB, DCRD, CHAN, DISC, PEER, RPCS, SCRP, SRVR, SYNC, and TXMP.\nFinally the keyword 'show' will return a list of the available subsystems."),
    ("debuglevel-levelspec", "The debug level(s) to use or the keyword 'show'"),
    ("decoderawtransaction--synopsis", "Returns a JSON object representing the provided serialized, hex-encoded transaction."),
    ("decoderawtransaction-hextx", "Serialized, hex-encoded transaction"),
    ("decodescript--synopsis", "Returns a JSON object with information about the provided hex-encoded script."),
    ("decodescript-hexscript", "Hex-encoded script"),
    ("decodescript-version", "The script version, defaults to version 0 if not set."),
    ("decodescriptresult-addresses", "The Decred addresses associated with this script"),
    ("decodescriptresult-asm", "Disassembly of the script"),
    ("decodescriptresult-p2sh", "The script hash for use in pay-to-script-hash transactions (only present if the provided redeem script is not already a pay-to-script-hash script)"),
    ("decodescriptresult-reqSigs", "The number of required signatures"),
    ("decodescriptresult-type", "The type of the script (e.g. 'pubkeyhash')"),
    ("estimatefee--result0", "Estimated fee."),
    ("estimatefee--synopsis", "Returns the estimated fee in dcr/kb."),
    ("estimatefee-numblocks", "(unused)"),
    ("estimatesmartfee--synopsis", "Returns the estimated fee using the historical fee data in dcr/kb."),
    ("estimatesmartfee-confirmations", "Estimate the fee rate a transaction requires so that it is mined in up to this number of blocks."),
    ("estimatesmartfee-mode", "The only supported mode for the moment is 'conservative'."),
    ("estimatesmartfeeresult-blocks", "The block number where the estimate was found."),
    ("estimatesmartfeeresult-errors", "Unused."),
    ("estimatesmartfeeresult-feerate", "The Estimated fee rate (in DCR/KB)."),
    ("estimatestakediff--synopsis", "Estimate the next minimum, maximum, expected, and user-specified stake difficulty"),
    ("estimatestakediff-tickets", "Use this number of new tickets in blocks to estimate the next difficulty"),
    ("estimatestakediffresult-expected", "Expected estimate for stake difficulty"),
    ("estimatestakediffresult-max", "Maximum estimate for stake difficulty"),
    ("estimatestakediffresult-min", "Minimum estimate for stake difficulty"),
    ("estimatestakediffresult-user", "Estimate for stake difficulty with the passed user amount of tickets"),
    ("existsaddress--result0", "Bool showing if address exists or not"),
    ("existsaddress--synopsis", "Test for the existence of the provided address"),
    ("existsaddress-address", "The address to check"),
    ("existsaddresses--result0", "Bitset of bools showing if addresses exist or not"),
    ("existsaddresses--synopsis", "Test for the existence of the provided addresses in the blockchain or memory pool"),
    ("existsaddresses-addresses", "The addresses to check"),
    ("existsliveticket--result0", "Bool showing if address exists in the live ticket database or not"),
    ("existsliveticket--synopsis", "Test for the existence of the provided ticket"),
    ("existsliveticket-txhash", "The ticket hash to check"),
    ("existslivetickets--result0", "Bool blob showing if ticket exists in the live ticket database or not"),
    ("existslivetickets--synopsis", "Test for the existence of the provided tickets in the live ticket map"),
    ("existslivetickets-txhashes", "Array of hashes to check"),
    ("existsmempooltxs--result0", "Bool blob showing if txs exist in the mempool or not"),
    ("existsmempooltxs--synopsis", "Test for the existence of the provided txs in the mempool"),
    ("existsmempooltxs-txhashes", "Array of hashes to check"),
    ("feeinfoblock-height", "Height of the block"),
    ("feeinfoblock-max", "Maximum transaction fee in the block"),
    ("feeinfoblock-mean", "Mean of transaction fees in the block"),
    ("feeinfoblock-median", "Median of transaction fees in the block"),
    ("feeinfoblock-min", "Minimum transaction fee in the block"),
    ("feeinfoblock-number", "Number of transactions in the block"),
    ("feeinfoblock-stddev", "Standard deviation of transaction fees in the block"),
    ("feeinfomempool-max", "Maximum transaction fee in the mempool"),
    ("feeinfomempool-mean", "Mean of transaction fees in the mempool"),
    ("feeinfomempool-median", "Median of transaction fees in the mempool"),
    ("feeinfomempool-min", "Minimum transaction fee in the mempool"),
    ("feeinfomempool-number", "Number of transactions in the mempool"),
    ("feeinfomempool-stddev", "Standard deviation of transaction fees in the mempool"),
    ("feeinforange-max", "Maximum transaction fee in the window"),
    ("feeinforange-mean", "Mean of transaction fees in the window"),
    ("feeinforange-median", "Median of transaction fees in the window"),
    ("feeinforange-min", "Minimum transaction fee in the window"),
    ("feeinforange-number", "Number of transactions in the window"),
    ("feeinforange-stddev", "Standard deviation of transaction fees in the window"),
    ("feeinfowindow-endheight", "Last block in the window (exclusive)"),
    ("feeinfowindow-max", "Maximum transaction fee in the window"),
    ("feeinfowindow-mean", "Mean of transaction fees in the window"),
    ("feeinfowindow-median", "Median of transaction fees in the window"),
    ("feeinfowindow-min", "Minimum transaction fee in the window"),
    ("feeinfowindow-number", "Number of transactions in the window"),
    ("feeinfowindow-startheight", "First block in the window (inclusive)"),
    ("feeinfowindow-stddev", "Standard deviation of transaction fees in the window"),
    ("generate--condition0", "numblocks>0"),
    ("generate--condition1", "numblocks=0"),
    ("generate--result0", "The hashes, in order, of blocks that extended the main chain"),
    ("generate--synopsis", "Generates blocks as needed to extend the main chain by a set number of blocks (testnet or simnet only).\nBlocks that arrive from other sources are built upon and a best effort attempt is made to avoid as many forks as possible.\nAn error is returned when the server is already CPU mining and CPU mining via any other RPCs is prevented while it runs."),
    ("generate-numblocks", "Number of blocks to extend the main chain or 0 to cancel an active instance"),
    ("getaddednodeinfo--condition0", "dns=false"),
    ("getaddednodeinfo--condition1", "dns=true"),
    ("getaddednodeinfo--result0", "List of added peers"),
    ("getaddednodeinfo--synopsis", "Returns information about manually added (persistent) peers."),
    ("getaddednodeinfo-dns", "Specifies whether the returned data is a JSON object including DNS and connection information, or just a list of added peers"),
    ("getaddednodeinfo-node", "Only return information about this specific peer instead of all added peers"),
    ("getaddednodeinforesult-addednode", "The ip address or domain of the added peer"),
    ("getaddednodeinforesult-addresses", "DNS lookup and connection information about the peer"),
    ("getaddednodeinforesult-connected", "Whether or not the peer is currently connected"),
    ("getaddednodeinforesultaddr-address", "The ip address for this DNS entry"),
    ("getaddednodeinforesultaddr-connected", "The connection 'direction' (inbound/outbound/false)"),
    ("getbestblock--result0", "Get block height and hash of best block in the main chain."),
    ("getbestblock--synopsis", "Get block height and hash of best block in the main chain."),
    ("getbestblockhash--result0", "The hex-encoded block hash"),
    ("getbestblockhash--synopsis", "Returns the hash of the best (most recent) block in the longest block chain."),
    ("getbestblockresult-hash", "Hex-encoded bytes of the best block hash"),
    ("getbestblockresult-height", "Height of the best block"),
    ("getblock--condition0", "verbose=false"),
    ("getblock--condition1", "verbose=true"),
    ("getblock--result0", "Hex-encoded bytes of the serialized block"),
    ("getblock--synopsis", "Returns information about a block given its hash."),
    ("getblock-hash", "The hash of the block"),
    ("getblock-verbose", "Specifies the block is returned as a JSON object instead of hex-encoded string"),
    ("getblock-verbosetx", "Specifies that each transaction is returned as a JSON object and only applies if the verbose flag is true (dcrd extension)"),
    ("getblockchaininfo--synopsis", "Returns information about the current state of the block chain."),
    ("getblockchaininforesult-bestblockhash", "The block hash of the current best chain tip."),
    ("getblockchaininforesult-blocks", "The number of blocks in the current best chain."),
    ("getblockchaininforesult-chain", "The current network name."),
    ("getblockchaininforesult-chainwork", "Hex encoded total work done for the chain."),
    ("getblockchaininforesult-deployments", "Network consensus deployments."),
    ("getblockchaininforesult-deployments--desc", "Consensus deployment agendas."),
    ("getblockchaininforesult-deployments--key", "The consensus deployment agenda id."),
    ("getblockchaininforesult-deployments--value", "The consensus deployment agenda information."),
    ("getblockchaininforesult-difficulty", "(DEPRECATED) The current network difficulty."),
    ("getblockchaininforesult-difficultyratio", "The current proof-of-work difficulty as a multiple of the minimum difficulty."),
    ("getblockchaininforesult-headers", "The number of validated block headers that comprise the target best chain."),
    ("getblockchaininforesult-initialblockdownload", "Best guess of whether this node is in the initial chain sync mode used to catch up the chain when it is far behind"),
    ("getblockchaininforesult-maxblocksize", "The maximum allowed block size."),
    ("getblockchaininforesult-syncheight", "The latest known block height being synced to."),
    ("getblockchaininforesult-verificationprogress", "The chain verification progress estimate."),
    ("getblockcount--result0", "The current block count"),
    ("getblockcount--synopsis", "Returns the number of blocks in the longest block chain."),
    ("getblockhash--result0", "The block hash"),
    ("getblockhash--synopsis", "Returns hash of the block in best block chain at the given height."),
    ("getblockhash-index", "The block height"),
    ("getblockheader--condition0", "verbose=false"),
    ("getblockheader--condition1", "verbose=true"),
    ("getblockheader--result0", "The serialized block header."),
    ("getblockheader--synopsis", "Returns information about a block header given its hash."),
    ("getblockheader-hash", "The hash of the block"),
    ("getblockheader-verbose", "Specifies the block header is returned as a JSON object instead of hex-encoded string"),
    ("getblockheaderverboseresult-bits", "The bits which represent the block difficulty"),
    ("getblockheaderverboseresult-chainwork", "The total number of hashes expected to produce the chain up to the block in hex"),
    ("getblockheaderverboseresult-confirmations", "The number of confirmations"),
    ("getblockheaderverboseresult-difficulty", "The proof-of-work difficulty as a multiple of the minimum difficulty"),
    ("getblockheaderverboseresult-extradata", "Extra data field for the requested block"),
    ("getblockheaderverboseresult-finalstate", "The final state value of the ticket pool"),
    ("getblockheaderverboseresult-freshstake", "The number of new tickets in the block"),
    ("getblockheaderverboseresult-hash", "The hash of the block (same as provided)"),
    ("getblockheaderverboseresult-height", "The height of the block in the block chain"),
    ("getblockheaderverboseresult-mediantime", "The median block time over the last 11 blocks"),
    ("getblockheaderverboseresult-merkleroot", "The merkle root of the regular transaction tree"),
    ("getblockheaderverboseresult-nextblockhash", "The hash of the next block (only if there is one)"),
    ("getblockheaderverboseresult-nonce", "The block nonce"),
    ("getblockheaderverboseresult-poolsize", "The size of the live ticket pool"),
    ("getblockheaderverboseresult-powhash", "The Proof-of-Work hash of the block (same as hash prior to DCP0011 activation)"),
    ("getblockheaderverboseresult-previousblockhash", "The hash of the previous block"),
    ("getblockheaderverboseresult-revocations", "The number of revocations in the block"),
    ("getblockheaderverboseresult-sbits", "The stake difficulty in coins"),
    ("getblockheaderverboseresult-size", "The size of the block in bytes"),
    ("getblockheaderverboseresult-stakeroot", "The merkle root of the stake transaction tree"),
    ("getblockheaderverboseresult-stakeversion", "The stake version of the block"),
    ("getblockheaderverboseresult-time", "The block time in seconds since 1 Jan 1970 GMT"),
    ("getblockheaderverboseresult-version", "The block version"),
    ("getblockheaderverboseresult-votebits", "The vote bits"),
    ("getblockheaderverboseresult-voters", "The number of votes in the block"),
    ("getblocksubsidy--synopsis", "Returns information regarding subsidy amounts."),
    ("getblocksubsidy-height", "The block height"),
    ("getblocksubsidy-voters", "The number of voters"),
    ("getblocksubsidyresult-developer", "The developer subsidy"),
    ("getblocksubsidyresult-pos", "The Proof-of-Stake subsidy"),
    ("getblocksubsidyresult-pow", "The Proof-of-Work subsidy"),
    ("getblocksubsidyresult-total", "The total subsidy"),
    ("getblockverboseresult-bits", "The bits which represent the block difficulty"),
    ("getblockverboseresult-chainwork", "The total number of hashes expected to produce the chain up to the block in hex"),
    ("getblockverboseresult-confirmations", "The number of confirmations"),
    ("getblockverboseresult-difficulty", "The proof-of-work difficulty as a multiple of the minimum difficulty"),
    ("getblockverboseresult-extradata", "Extra data field for the requested block"),
    ("getblockverboseresult-finalstate", "The block's finalstate"),
    ("getblockverboseresult-freshstake", "The number of new tickets in the block"),
    ("getblockverboseresult-hash", "The hash of the block (same as provided)"),
    ("getblockverboseresult-height", "The height of the block in the block chain"),
    ("getblockverboseresult-mediantime", "The median block time over the last 11 blocks"),
    ("getblockverboseresult-merkleroot", "Root hash of the merkle tree"),
    ("getblockverboseresult-nextblockhash", "The hash of the next block (only if there is one)"),
    ("getblockverboseresult-nonce", "The block nonce"),
    ("getblockverboseresult-poolsize", "The size of the live ticket pool"),
    ("getblockverboseresult-powhash", "The Proof-of-Work hash of the block (same as hash prior to DCP0011 activation)"),
    ("getblockverboseresult-previousblockhash", "The hash of the previous block"),
    ("getblockverboseresult-rawstx", "The block's raw sstx hashes the were included"),
    ("getblockverboseresult-rawtx", "The transactions as JSON objects (only when verbosetx=true)"),
    ("getblockverboseresult-revocations", "The number of revocations in the block"),
    ("getblockverboseresult-sbits", "The stake difficulty of the block"),
    ("getblockverboseresult-size", "The size of the block"),
    ("getblockverboseresult-stakeroot", "The block's sstx hashes the were included"),
    ("getblockverboseresult-stakeversion", "Stake Version of the block"),
    ("getblockverboseresult-stx", "The block's sstx hashes the were included"),
    ("getblockverboseresult-time", "The block time in seconds since 1 Jan 1970 GMT"),
    ("getblockverboseresult-tx", "The transaction hashes (only when verbosetx=false)"),
    ("getblockverboseresult-version", "The block version"),
    ("getblockverboseresult-votebits", "The block's voting results"),
    ("getblockverboseresult-voters", "The number votes in the block"),
    ("getcfilterv2--synopsis", "Returns the version 2 block filter for the given block along with a proof that can be used to prove the filter is committed to by the block header"),
    ("getcfilterv2-blockhash", "The block hash of the filter to retrieve"),
    ("getcfilterv2result-blockhash", "The block hash for which the filter includes data"),
    ("getcfilterv2result-data", "Hex-encoded bytes of the serialized filter"),
    ("getcfilterv2result-proofhashes", "The hashes needed to prove the filter is committed to by the header commitment"),
    ("getcfilterv2result-proofindex", "The index of the leaf that represents the filter hash in the header commitment"),
    ("getchaintips--synopsis", "Returns information about all known chain tips the in the block tree.\n\nThe statuses in the result have the following meanings:\nactive: The current best chain tip.\ninvalid: The block or one of its ancestors is invalid.\nheaders-only: The block or one of its ancestors does not have the full block data available which also means the block can't be validated or connected.\nvalid-fork: The block is fully validated which implies it was probably part of the main chain at one point and was reorganized.\nvalid-headers: The full block data is available and the header is valid, but the block was never validated which implies it was probably never part of the main chain."),
    ("getchaintipsresult-branchlen", "The length of the branch that connects the tip to the main chain (0 for the main chain tip)"),
    ("getchaintipsresult-hash", "The block hash of the chain tip"),
    ("getchaintipsresult-height", "The height of the chain tip"),
    ("getchaintipsresult-status", "The status of the chain (active, invalid, headers-only, valid-fork, valid-headers)"),
    ("getchaintipsresults--result0", "test"),
    ("getcoinsupply--result0", "Current coin supply in atoms"),
    ("getcoinsupply--synopsis", "Returns current total coin supply in atoms"),
    ("getconnectioncount--result0", "The number of connections"),
    ("getconnectioncount--synopsis", "Returns the number of active connections to other peers."),
    ("getcurrentnet--result0", "The network identifier"),
    ("getcurrentnet--synopsis", "Get Decred network the server is running on."),
    ("getdifficulty--result0", "The difficulty"),
    ("getdifficulty--synopsis", "Returns the proof-of-work difficulty as a multiple of the minimum difficulty."),
    ("getgenerate--result0", "True if mining, false if not"),
    ("getgenerate--synopsis", "Returns if the server is set to generate coins (mine) or not."),
    ("gethashespersec--result0", "The number of hashes per second"),
    ("gethashespersec--synopsis", "Returns a recent hashes per second performance measurement while generating coins (mining)."),
    ("getheaders--synopsis", "Returns block headers starting with the first known block hash from the request"),
    ("getheaders-blocklocators", "Array of block locator hashes.  Headers are returned starting from the first known hash in this list"),
    ("getheaders-hashstop", "Block hash to stop including block headers for. Set to zero to get as many blocks as possible"),
    ("getheadersresult-headers", "Serialized block headers of all located blocks, limited to some arbitrary maximum number of hashes (currently 2000, which matches the wire protocol headers message, but this is not guaranteed)"),
    ("getinfo--synopsis", "Returns a JSON object containing various state info."),
    ("getmempoolinfo--synopsis", "Returns memory pool information"),
    ("getmempoolinforesult-bytes", "Size in bytes of the mempool"),
    ("getmempoolinforesult-size", "Number of transactions in the mempool"),
    ("getmininginfo--synopsis", "Returns a JSON object containing mining-related information."),
    ("getmininginforesult-blocks", "Height of the latest best block"),
    ("getmininginforesult-currentblocksize", "Size of the latest best block"),
    ("getmininginforesult-currentblocktx", "Number of transactions in the latest best block"),
    ("getmininginforesult-difficulty", "Current target difficulty"),
    ("getmininginforesult-errors", "Any current errors"),
    ("getmininginforesult-generate", "Whether or not server is set to generate coins"),
    ("getmininginforesult-genproclimit", "Number of processors to use for coin generation (-1 when disabled)"),
    ("getmininginforesult-hashespersec", "Recent hashes per second performance measurement while generating coins"),
    ("getmininginforesult-networkhashps", "Estimated network hashes per second for the most recent blocks"),
    ("getmininginforesult-pooledtx", "Number of transactions in the memory pool"),
    ("getmininginforesult-stakedifficulty", "Stake difficulty required for the next block"),
    ("getmininginforesult-testnet", "Whether or not server is using testnet"),
    ("getmixmessage--result0", "JSON object describing the message command type and the serialized message in hex encoding."),
    ("getmixmessage--synopsis", "Returns a mix message if it is currently accepted by the mixpool."),
    ("getmixmessage-hash", "Hash of the message being queried"),
    ("getmixmessageresult-message", "Serialized message in hex encoding"),
    ("getmixmessageresult-type", "Command type of the message"),
    ("getmixpairrequests--result0", "JSON array of hex-encoded mixing pair request messages."),
    ("getmixpairrequests--synopsis", "Returns current set of mixing pair request messages from mixpool."),
    ("getnettotals--synopsis", "Returns a JSON object containing network traffic statistics."),
    ("getnettotalsresult-timemillis", "Number of milliseconds since 1 Jan 1970 GMT"),
    ("getnettotalsresult-totalbytesrecv", "Total bytes received"),
    ("getnettotalsresult-totalbytessent", "Total bytes sent"),
    ("getnetworkhashps--result0", "Estimated hashes per second"),
    ("getnetworkhashps--synopsis", "Returns the estimated network hashes per second for the block heights provided by the parameters."),
    ("getnetworkhashps-blocks", "The number of blocks or -1 for the default number of blocks"),
    ("getnetworkhashps-height", "Perform estimate ending with this height or -1 for current best chain block height"),
    ("getnetworkinfo--synopsis", "Returns a JSON object containing network-related information."),
    ("getnetworkinforesult-connections", "The total number of open connections for the node"),
    ("getnetworkinforesult-localaddresses", "An array of objects describing local addresses being listened on by the node"),
    ("getnetworkinforesult-localservices", "The services supported by the node, as advertised in its version message"),
    ("getnetworkinforesult-networks", "An array of objects describing IPV4, IPV6 and Onion network interface states"),
    ("getnetworkinforesult-protocolversion", "The protocol version of the node"),
    ("getnetworkinforesult-relayfee", "The minimum required transaction fee for the node."),
    ("getnetworkinforesult-subversion", "The subversion of the node, as advertised to peers"),
    ("getnetworkinforesult-timeoffset", "The node clock offset in seconds"),
    ("getnetworkinforesult-version", "The version of the node as a numeric"),
    ("getpeerinfo--synopsis", "Returns data about each connected network peer as an array of json objects."),
    ("getpeerinforesult-addr", "The ip address and port of the peer"),
    ("getpeerinforesult-addrlocal", "Local address"),
    ("getpeerinforesult-banscore", "The ban score"),
    ("getpeerinforesult-bytesrecv", "Total bytes received"),
    ("getpeerinforesult-bytessent", "Total bytes sent"),
    ("getpeerinforesult-conntime", "Time the connection was made in seconds since 1 Jan 1970 GMT"),
    ("getpeerinforesult-currentheight", "The current height of the peer"),
    ("getpeerinforesult-id", "A unique node ID"),
    ("getpeerinforesult-inbound", "Whether or not the peer is an inbound connection"),
    ("getpeerinforesult-lastrecv", "Time the last message was sent in seconds since 1 Jan 1970 GMT"),
    ("getpeerinforesult-lastsend", "Time the last message was received in seconds since 1 Jan 1970 GMT"),
    ("getpeerinforesult-pingtime", "Number of microseconds the last ping took"),
    ("getpeerinforesult-pingwait", "Number of microseconds a queued ping has been waiting for a response"),
    ("getpeerinforesult-relaytxes", "Peer has requested transactions be relayed to it"),
    ("getpeerinforesult-services", "Services bitmask which represents the services supported by the peer"),
    ("getpeerinforesult-startingheight", "The latest block height the peer knew about when the connection was established"),
    ("getpeerinforesult-subver", "The user agent of the peer"),
    ("getpeerinforesult-syncnode", "Whether or not the peer is the sync peer"),
    ("getpeerinforesult-timeoffset", "The time offset of the peer"),
    ("getpeerinforesult-version", "The protocol version of the peer"),
    ("getrawmempool--condition0", "verbose=false"),
    ("getrawmempool--condition1", "verbose=true"),
    ("getrawmempool--result0", "Array of transaction hashes"),
    ("getrawmempool--synopsis", "Returns information about all of the transactions currently in the memory pool."),
    ("getrawmempool-txtype", "Type of tx to return (regular/tickets/votes/revocations/tspend/tadd/all)"),
    ("getrawmempool-verbose", "Returns JSON object when true or an array of transaction hashes when false"),
    ("getrawmempoolverboseresult-currentpriority", "(DEPRECATED) This field is always 0 and will be removed in a future version of the software"),
    ("getrawmempoolverboseresult-depends", "Unconfirmed transactions used as inputs for this transaction"),
    ("getrawmempoolverboseresult-fee", "Transaction fee in decred"),
    ("getrawmempoolverboseresult-height", "Block height when transaction entered the pool"),
    ("getrawmempoolverboseresult-size", "Transaction size in bytes"),
    ("getrawmempoolverboseresult-startingpriority", "(DEPRECATED) This field is always 0 and will be removed in a future version of the software"),
    ("getrawmempoolverboseresult-time", "Local time transaction entered pool in seconds since 1 Jan 1970 GMT"),
    ("getrawtransaction--condition0", "verbose=false"),
    ("getrawtransaction--condition1", "verbose=true"),
    ("getrawtransaction--result0", "Hex-encoded bytes of the serialized transaction"),
    ("getrawtransaction--synopsis", "Returns information about a transaction given its hash."),
    ("getrawtransaction-txid", "The hash of the transaction"),
    ("getrawtransaction-verbose", "Specifies the transaction is returned as a JSON object instead of a hex-encoded string"),
    ("getstakedifficulty--synopsis", "Returns the proof-of-stake difficulty."),
    ("getstakedifficultyresult-current", "The current top block's stake difficulty"),
    ("getstakedifficultyresult-next", "The calculated stake difficulty of the next block"),
    ("getstakeversioninfo--synopsis", "Returns stake version statistics for one or more stake version intervals."),
    ("getstakeversioninfo-count", "Number of intervals to return."),
    ("getstakeversioninforesult-currentheight", "Top of the chain height."),
    ("getstakeversioninforesult-hash", "Top of the chain hash."),
    ("getstakeversioninforesult-intervals", "Array of total stake and vote counts."),
    ("getstakeversions--synopsis", "Returns the stake versions statistics."),
    ("getstakeversions-count", "The number of blocks that will be returned."),
    ("getstakeversions-hash", "The start block hash."),
    ("getstakeversionsresult-stakeversions", "Array of stake versions per block."),
    ("getticketpoolvalue--result0", "Total value of ticket pool"),
    ("getticketpoolvalue--synopsis", "Return the current value of all locked funds in the ticket pool"),
    ("gettreasurybalance--condition0", "verbose=false"),
    ("gettreasurybalance--condition1", "verbose=true"),
    ("gettreasurybalance--synopsis", "Returns treasury balance at the given hash."),
    ("gettreasurybalance-hash", "The hash of the block"),
    ("gettreasurybalance-verbose", "Optionally returns the updates to the balance that will be applied coinbase maturity from now"),
    ("gettreasurybalanceresult-balance", "Treasury balance at this block"),
    ("gettreasurybalanceresult-hash", "Block hash"),
    ("gettreasurybalanceresult-height", "Block height"),
    ("gettreasurybalanceresult-updates", "Optional treasury updates that will be applied coinbase maturity from now"),
    ("gettreasuryspendvotes--synopsis", "Returns a tally of votes for a list of treasury spend transactions."),
    ("gettreasuryspendvotes-block", "Count votes only up to the specified block.\nIf empty, count up to the current mainchain tip."),
    ("gettreasuryspendvotes-tspends", "Count votes for the specified tspends.\nIf empty, count votes for all tspends currently in the mempool."),
    ("gettreasuryspendvotesresult-hash", "The block hash for the last block where votes were tallied"),
    ("gettreasuryspendvotesresult-height", "The block height for the last block where votes were tallied"),
    ("gettreasuryspendvotesresult-votes", "Vote counts for each tspend"),
    ("gettxout--synopsis", "Returns information about an unspent transaction output."),
    ("gettxout-includemempool", "Include the mempool when true"),
    ("gettxout-tree", "The tree of the transaction"),
    ("gettxout-txid", "The hash of the transaction"),
    ("gettxout-vout", "The index of the output"),
    ("gettxoutresult-bestblock", "The block hash that contains the transaction output"),
    ("gettxoutresult-coinbase", "Whether or not the transaction is a coinbase"),
    ("gettxoutresult-confirmations", "The number of confirmations"),
    ("gettxoutresult-scriptPubKey", "The public key script used to pay coins as a JSON object"),
    ("gettxoutresult-value", "The transaction amount in DCR"),
    ("gettxoutsetinfo--synopsis", "Returns statistics on current unspent transaction output set."),
    ("gettxoutsetinforesult-bestblock", "The hex encoded hash of the best block."),
    ("gettxoutsetinforesult-disksize", "The size of the utxo set on disk, in bytes."),
    ("gettxoutsetinforesult-height", "The current block height."),
    ("gettxoutsetinforesult-serializedhash", "The merklized hash of the utxo set."),
    ("gettxoutsetinforesult-totalamount", "The total value of the utxo set."),
    ("gettxoutsetinforesult-transactions", "The number of unique transactions referenced by outputs."),
    ("gettxoutsetinforesult-txouts", "The number of transaction outputs."),
    ("getvoteinfo--synopsis", "Returns the vote info statistics."),
    ("getvoteinfo-version", "The stake version."),
    ("getvoteinforesult-agendas", "All agendas for this stake version."),
    ("getvoteinforesult-currentheight", "Top of the chain height."),
    ("getvoteinforesult-endheight", "The end height of this voting window."),
    ("getvoteinforesult-hash", "The hash of the current height block."),
    ("getvoteinforesult-quorum", "Minimum amount of votes required."),
    ("getvoteinforesult-startheight", "The start height of this voting window."),
    ("getvoteinforesult-totalvotes", "Total votes."),
    ("getvoteinforesult-voteversion", "Selected vote version."),
    ("getwork--condition0", "no data provided"),
    ("getwork--condition1", "data provided"),
    ("getwork--result1", "Whether or not the solved data is valid and was added to the chain"),
    ("getwork--synopsis", "Returns formatted hash data to work on or checks and submits solved data."),
    ("getwork-data", "Hex-encoded data to check"),
    ("getworkresult-data", "Hex-encoded block data"),
    ("getworkresult-hash1", "(DEPRECATED) Hex-encoded formatted hash buffer"),
    ("getworkresult-midstate", "(DEPRECATED) Hex-encoded precomputed hash state after hashing first half of the data"),
    ("getworkresult-target", "Hex-encoded little-endian hash target"),
    ("help--condition0", "no command provided"),
    ("help--condition1", "command specified"),
    ("help--result0", "List of commands"),
    ("help--result1", "Help for specified command"),
    ("help--synopsis", "Returns a list of all commands or help for a specified command."),
    ("help-command", "The command to retrieve help for"),
    ("infochainresult-blocks", "The number of blocks processed"),
    ("infochainresult-connections", "The number of connected peers"),
    ("infochainresult-difficulty", "The current target difficulty"),
    ("infochainresult-errors", "Any current errors"),
    ("infochainresult-protocolversion", "The latest supported protocol version"),
    ("infochainresult-proxy", "The proxy used by the server"),
    ("infochainresult-relayfee", "The minimum relay fee for transactions in DCR/KB"),
    ("infochainresult-testnet", "Whether or not server is using testnet"),
    ("infochainresult-timeoffset", "The time offset"),
    ("infochainresult-txindex", "Whether or not server has transaction index enabled"),
    ("infochainresult-version", "The version of the server"),
    ("invalidateblock--synopsis", "Permanently invalidates a block as if it had violated consensus rules.\nUse reconsiderblock to remove the invalid status."),
    ("invalidateblock-blockhash", "The hash of the block to invalidate"),
    ("livetickets--synopsis", "Returns live ticket hashes from the ticket database"),
    ("liveticketsresult-tickets", "List of live tickets"),
    ("loadtxfilter--synopsis", "Load, add to, or reload a websocket client's transaction filter for mempool transactions, new blocks and rescans."),
    ("loadtxfilter-addresses", "Array of addresses to add to the transaction filter"),
    ("loadtxfilter-outpoints", "Array of outpoints to add to the transaction filter"),
    ("loadtxfilter-reload", "Load a new filter instead of adding data to an existing one"),
    ("localaddressesresult-address", "The local address being listened on"),
    ("localaddressesresult-port", "The port being listened on for the associated local address"),
    ("localaddressesresult-score", "Reserved"),
    ("networksresult-limited", "True if only connections to the network are allowed"),
    ("networksresult-name", "The name of the network interface"),
    ("networksresult-proxy", "The proxy set for the network"),
    ("networksresult-proxyrandomizecredentials", "True if randomized credentials are set for the proxy"),
    ("networksresult-reachable", "True if connections can be made to or from the network"),
    ("node--synopsis", "Attempts to add or remove a peer."),
    ("node-connectsubcmd", "'perm' to make the connected peer a permanent one, 'temp' to try a single connect to a peer"),
    ("node-subcmd", "'disconnect' to remove all matching non-persistent peers, 'remove' to remove a persistent peer, or 'connect' to connect to a peer"),
    ("node-target", "Either the IP address and port of the peer to operate on, or a valid peer ID."),
    ("notifyblocks--synopsis", "Request notifications for whenever a block is connected or disconnected from the main (best) chain."),
    ("notifymixmessages--synopsis", "Request notifications for whenever mixing messages are accepted to the mixpool."),
    ("notifynewtickets--synopsis", "Request notifications for whenever new tickets are found."),
    ("notifynewtransactions--synopsis", "Send either a txaccepted or a txacceptedverbose notification when a new transaction is accepted into the mempool."),
    ("notifynewtransactions-verbose", "Specifies which type of notification to receive. If verbose is true, then the caller receives txacceptedverbose, otherwise the caller receives txaccepted"),
    ("notifytspend--synopsis", "Request notifications for whenever a new tspend arrives in the mempool."),
    ("notifywinningtickets--synopsis", "Request notifications for whenever any tickets are chosen to vote."),
    ("notifywork--synopsis", "Request notifications for whenever a new block template is generated."),
    ("outpoint-hash", "The hex-encoded bytes of the outpoint hash"),
    ("outpoint-index", "The index of the outpoint"),
    ("outpoint-tree", "The tree of the outpoint"),
    ("ping--synopsis", "Queues a ping to be sent to each connected peer.\nPing times are provided by getpeerinfo via the pingtime and pingwait fields."),
    ("prevout-addresses", "previous output addresses"),
    ("prevout-value", "previous output value"),
    ("rebroadcastwinners--synopsis", "Asks the daemon to rebroadcast the winners of the voting lottery."),
    ("reconsiderblock--synopsis", "Reconsiders a block for validation and best chain selection by removing any invalid status from it and its ancestors.\nAny descendants that are neither themselves marked as having failed validation, nor descendants of another such block, are also made eligibile for best chain selection."),
    ("reconsiderblock-blockhash", "The hash of the block to reconsider"),
    ("regentemplate--synopsis", "Asks the node to regenerate its block mining template."),
    ("rescan--synopsis", "Rescan blocks for transactions matching the loaded transaction filter."),
    ("rescan-blockhashes", "Array of block hashes to rescan.  Each subsequent block after the first one must be a child of the previous."),
    ("rescannedblock-hash", "The hash of the block containing matching transactions."),
    ("rescannedblock-transactions", "Array of hex-encoded bytes of the serialized matching transactions."),
    ("rescanresult-discovereddata", "The data matching the loaded transaction filter as JSON objects."),
    ("scriptpubkeyresult-addresses", "The Decred addresses associated with this script"),
    ("scriptpubkeyresult-asm", "Disassembly of the script"),
    ("scriptpubkeyresult-commitamt", "The ticket commitment value if the script is for a staking commitment"),
    ("scriptpubkeyresult-hex", "Hex-encoded bytes of the script"),
    ("scriptpubkeyresult-reqSigs", "The number of required signatures"),
    ("scriptpubkeyresult-type", "The type of the script (e.g. 'pubkeyhash')"),
    ("scriptpubkeyresult-version", "The script version"),
    ("scriptsig-asm", "Disassembly of the script"),
    ("scriptsig-hex", "Hex-encoded bytes of the script"),
    ("sendrawmixmessage--synopsis", "Submit a mixing message to the mixpool and broadcast it to the network and all peers"),
    ("sendrawmixmessage-command", "The wire command name of the message type"),
    ("sendrawmixmessage-message", "Mixing message serialized and encoded as hex"),
    ("sendrawtransaction--result0", "The hash of the transaction"),
    ("sendrawtransaction--synopsis", "Submits the serialized, hex-encoded transaction to the local peer and relays it to the network."),
    ("sendrawtransaction-allowhighfees", "Whether or not to allow insanely high fees (dcrd does not yet implement this parameter, so it has no effect)"),
    ("sendrawtransaction-hextx", "Serialized, hex-encoded signed transaction"),
    ("session--synopsis", "Return details regarding a websocket client's current connection session."),
    ("sessionresult-sessionid", "The unique session ID for a client's websocket connection."),
    ("setgenerate--synopsis", "Set the server to generate coins (mine) or not."),
    ("setgenerate-generate", "Use true to enable generation, false to disable it"),
    ("setgenerate-genproclimit", "The number of processors (cores) to limit generation to or -1 for default"),
    ("sstxcommitout-addr", "Address to send sstx commit"),
    ("sstxcommitout-changeaddr", "Address for change"),
    ("sstxcommitout-changeamt", "Amount for change in atoms"),
    ("sstxcommitout-commitamt", "Amount to commit in atoms"),
    ("sstxinput-amt", "Amount of utxo in atoms"),
    ("sstxinput-tree", "Which tree utxo is located"),
    ("sstxinput-txid", "Unspent tx output hash"),
    ("sstxinput-vout", "Index of the output being redeemed"),
    ("stakeversions-blockversion", "The block version"),
    ("stakeversions-hash", "Hash of the block."),
    ("stakeversions-height", "Height of the block."),
    ("stakeversions-stakeversion", "The stake version of the block"),
    ("stakeversions-votes", "The version and bits of each vote in the block"),
    ("startprofiler--synopsis", "Starts the HTTP profile server listening on a given address."),
    ("startprofiler-addr", "The interface/port to listen for profile server connections (e.g. 127.0.0.1:6060)"),
    ("startprofiler-allownonloopback", "Whether or not to allow listening on non loopback addresses"),
    ("startprofilerresult-listeners", "List of normalized listening addresses the profile server is listening on"),
    ("stop--result0", "The string 'dcrd stopping.'"),
    ("stop--synopsis", "Shutdown dcrd."),
    ("stopnotifyblocks--synopsis", "Cancel registered notifications for whenever a block is connected or disconnected from the main (best) chain."),
    ("stopnotifymixmessages--synopsis", "Cancel registered notifications for whenever mixing messages are accepted to the mixpool."),
    ("stopnotifynewtransactions--synopsis", "Stop sending either a txaccepted or a txacceptedverbose notification when a new transaction is accepted into the mempool."),
    ("stopnotifytspend--synopsis", "Cancel registered notifications for whenever a new tspend arrives in the mempool."),
    ("stopnotifywork--synopsis", "Cancel registered notifications for whenever a new block template is generated."),
    ("stopprofiler--result0", "The string 'profile server stopped'"),
    ("stopprofiler--synopsis", "Stops the running HTTP profile server."),
    ("submitblock--condition0", "Block successfully submitted"),
    ("submitblock--condition1", "Block rejected"),
    ("submitblock--result1", "The reason the block was rejected"),
    ("submitblock--synopsis", "Attempts to submit a new serialized, hex-encoded block to the network."),
    ("submitblock-hexblock", "Serialized, hex-encoded block"),
    ("submitblock-options", "This parameter is currently ignored"),
    ("submitblockoptions-workid", "This parameter is currently ignored"),
    ("ticket-hash", "Hash of the ticket."),
    ("ticket-owner", "Address owning the ticket."),
    ("ticketbucket-number", "Bucket number."),
    ("ticketbucket-tickets", "Number of tickets in bucket."),
    ("ticketbuckets--synopsis", "Request for the number of tickets currently in each bucket of the ticket database."),
    ("ticketfeeinfo--synopsis", "Get various information about ticket fees from the mempool, blocks, and difficulty windows (units: DCR/kB)"),
    ("ticketfeeinfo-blocks", "The number of blocks, starting from the chain tip and descending, to return fee information about"),
    ("ticketfeeinfo-windows", "The number of difficulty windows to return ticket fee information about"),
    ("ticketfeeinforesult-feeinfoblocks", "Ticket fee information for a given list of blocks descending from the chain tip (units: DCR/kB)"),
    ("ticketfeeinforesult-feeinfomempool", "Ticket fee information for all tickets in the mempool (units: DCR/kB)"),
    ("ticketfeeinforesult-feeinfowindows", "Ticket fee information for a window period where the stake difficulty was the same (units: DCR/kB)"),
    ("ticketsforaddress--synopsis", "Request all the tickets for an address."),
    ("ticketsforaddress-address", "Address to look for."),
    ("ticketsforaddressresult-tickets", "Tickets owned by the specified address."),
    ("ticketsforbucket--synopsis", "Request all the tickets and owners in a given bucket."),
    ("ticketsforbucket-bucket", "Bucket to look for."),
    ("ticketsforbucketresult-tickets", "Result for the ticketsfor bucket command."),
    ("ticketvwap--result0", "The volume weighted average price"),
    ("ticketvwap--synopsis", "Calculate the volume weighted average price of tickets for a range of blocks (default: full PoS difficulty adjustment depth)"),
    ("ticketvwap-end", "The end height to begin calculating the VWAP from"),
    ("ticketvwap-start", "The start height to begin calculating the VWAP from"),
    ("transactioninput-amount", "The previous output amount in coins"),
    ("transactioninput-tree", "The tree that the transaction input is located"),
    ("transactioninput-txid", "The hash of the input transaction"),
    ("transactioninput-vout", "The specific output of the input transaction to redeem"),
    ("treasuryspendvotes-expiry", "The block height when the tspend expires"),
    ("treasuryspendvotes-hash", "The hash of the tspend transaction"),
    ("treasuryspendvotes-novotes", "The number of no votes the tspend received"),
    ("treasuryspendvotes-voteend", "The block height when voting for the tspend ends"),
    ("treasuryspendvotes-votestart", "The block height when voting for the tspend starts"),
    ("treasuryspendvotes-yesvotes", "The number of yes votes the tspend received"),
    ("txfeeinfo--synopsis", "Get various information about regular transaction fees from the mempool, blocks, and difficulty windows"),
    ("txfeeinfo-blocks", "The number of blocks to calculate transaction fees for, starting from the end of the tip moving backwards"),
    ("txfeeinfo-rangeend", "The end height of the block range to calculate transaction fees for"),
    ("txfeeinfo-rangestart", "The start height of the block range to calculate transaction fees for"),
    ("txfeeinforesult-feeinfoblocks", "Transaction fee information for a given list of blocks descending from the chain tip"),
    ("txfeeinforesult-feeinfomempool", "Transaction fee information for all regular transactions in the mempool"),
    ("txfeeinforesult-feeinforange", "Transaction fee information for a window period where the stake difficulty was the same"),
    ("txrawdecoderesult-expiry", "The transaction expiry"),
    ("txrawdecoderesult-locktime", "The transaction lock time"),
    ("txrawdecoderesult-txid", "The hash of the transaction"),
    ("txrawdecoderesult-version", "The transaction version"),
    ("txrawdecoderesult-vin", "The transaction inputs as JSON objects"),
    ("txrawdecoderesult-vout", "The transaction outputs as JSON objects"),
    ("txrawresult-blockhash", "The hash of the block that contains the transaction"),
    ("txrawresult-blockheight", "The height of the block that contains the transaction"),
    ("txrawresult-blockindex", "The index within the array of transactions contained by the block"),
    ("txrawresult-blocktime", "Block time in seconds since the 1 Jan 1970 GMT"),
    ("txrawresult-confirmations", "Number of confirmations of the block"),
    ("txrawresult-expiry", "The transacion expiry"),
    ("txrawresult-hex", "Hex-encoded transaction"),
    ("txrawresult-locktime", "The transaction lock time"),
    ("txrawresult-time", "Transaction time in seconds since 1 Jan 1970 GMT"),
    ("txrawresult-txid", "The hash of the transaction"),
    ("txrawresult-version", "The transaction version"),
    ("txrawresult-vin", "The transaction inputs as JSON objects"),
    ("txrawresult-vout", "The transaction outputs as JSON objects"),
    ("validateaddress--synopsis", "Verify an address is valid."),
    ("validateaddress-address", "Decred address to validate"),
    ("validateaddresschainresult-address", "The Decred address (only when isvalid is true)"),
    ("validateaddresschainresult-isvalid", "Whether or not the address is valid"),
    ("verifychain--result0", "Whether or not the chain verified"),
    ("verifychain--synopsis", "Verifies the block chain database.\nThe actual checks performed by the checklevel parameter are implementation specific.\nFor dcrd this is:\nchecklevel=0 - Look up each block and ensure it can be loaded from the database.\nchecklevel=1 - Perform basic context-free sanity checks on each block."),
    ("verifychain-checkdepth", "The number of blocks to check"),
    ("verifychain-checklevel", "How thorough the block verification is"),
    ("verifymessage--result0", "Whether or not the signature verified"),
    ("verifymessage--synopsis", "Verify a signed message."),
    ("verifymessage-address", "The Decred address to use for the signature"),
    ("verifymessage-message", "The signed message"),
    ("verifymessage-signature", "The base-64 encoded signature provided by the signer"),
    ("version--result0--desc", "Version objects keyed by the program or API name"),
    ("version--result0--key", "Program or API name"),
    ("version--result0--value", "Object containing the semantic version"),
    ("version--synopsis", "Returns the JSON-RPC API version (semver)"),
    ("versionbits-bits", "The bits assigned by the vote."),
    ("versionbits-version", "The version of the vote."),
    ("versioncount-count", "Number of votes."),
    ("versioncount-version", "Version of the vote."),
    ("versioninterval-endheight", "End of the interval."),
    ("versioninterval-posversions", "Tally of the stake versions."),
    ("versioninterval-startheight", "Start of the interval."),
    ("versioninterval-voteversions", "Tally of all vote versions."),
    ("vin-amountin", "The amount in"),
    ("vin-blockheight", "The block height of the origin transaction"),
    ("vin-blockindex", "The block idx of the origin transaction"),
    ("vin-coinbase", "The hex-encoded bytes of the signature script (coinbase txns only)"),
    ("vin-scriptSig", "The signature script used to redeem the origin transaction as a JSON object (non-coinbase txns only)"),
    ("vin-sequence", "The script sequence number"),
    ("vin-stakebase", "The hex-encoded bytes of the signature script (vote txns only)"),
    ("vin-treasurybase", "Whether or not the input is a treasury base (treasurybase txns only)"),
    ("vin-treasuryspend", "The hex-encoded bytes of the signature script (treasury spend txns only)"),
    ("vin-tree", "The tree of the transaction"),
    ("vin-txid", "The hash of the origin transaction (non-coinbase txns only)"),
    ("vin-vout", "The index of the output being redeemed from the origin transaction (non-coinbase txns only)"),
    ("vinprevout-amountin", "The amount in for this transaction input, in coins"),
    ("vinprevout-blockheight", "The height of the block that includes the origin transaction (non-coinbase txns only)"),
    ("vinprevout-blockindex", "The merkle tree index of the origin transaction (non-coinbase txns only)"),
    ("vinprevout-coinbase", "The hex-encoded bytes of the signature script (coinbase txns only)"),
    ("vinprevout-prevOut", "Data from the origin transaction output with index vout."),
    ("vinprevout-scriptSig", "The signature script used to redeem the origin transaction as a JSON object (non-coinbase txns only)"),
    ("vinprevout-sequence", "The script sequence number"),
    ("vinprevout-stakebase", "The hex-encoded bytes of the signature script (vote txns only)"),
    ("vinprevout-treasurybase", "Whether or not the input is a treasury base (treasurybase txns only)"),
    ("vinprevout-treasuryspend", "The hex-encoded bytes of the signature script (treasury spend txns only)"),
    ("vinprevout-tree", "The transaction tree of the origin transaction (non-coinbase txns only)"),
    ("vinprevout-txid", "The hash of the origin transaction (non-coinbase txns only)"),
    ("vinprevout-vout", "The index of the output being redeemed from the origin transaction (non-coinbase txns only)"),
    ("vout-n", "The index of this transaction output"),
    ("vout-scriptPubKey", "The public key script used to pay coins as a JSON object"),
    ("vout-value", "The amount in DCR"),
    ("vout-version", "The version of the public key script"),
];
