// SPDX-License-Identifier: ISC
//! Replay of frozen dcrjson vectors generated by an in-package dump
//! test running inside dcrd's dcrjson package at release-v2.1.5.
//!
//! The dump registers a battery of dx-prefixed test commands and pins
//! the marshalled request/response bytes, error strings, one-line
//! usage text, and full generated help output.  The replay rebuilds
//! the same type descriptors and compares byte for byte.

// The battery tables mirror the Go dump rows one to one, including a
// nine-field command and literal float values such as 3.14.
#![allow(clippy::too_many_arguments)]
#![allow(clippy::approx_constant)]
#![allow(clippy::type_complexity)]

use std::collections::HashMap;

use dcroxide_dcrjson::{
    Arg, CmdInstance, GoType, GoValue, Method, RPCError, Registry, RpcId, StructField,
    UF_NOTIFICATION, UF_WEBSOCKET_ONLY, UsageFlag, decode_concatenated_hashes,
    encode_concatenated_hashes, err_rpc_internal, err_rpc_invalid_params, err_rpc_invalid_request,
    err_rpc_method_not_found, err_rpc_parse, gojson, marshal_cmd, marshal_request,
    marshal_response, new_cmd, new_request, parse_params,
};
use dcroxide_testutil::unhex;

const VECTORS: &str = include_str!("data/dcrjson_vectors.txt");

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).expect("utf8 payload")
}

// ---------------------------------------------------------------------
// Type descriptors mirroring the dump's Go test types.
// ---------------------------------------------------------------------

fn f(name: &str, typ: GoType) -> StructField {
    StructField::new(name, typ)
}

fn dx_sub() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxSub",
        vec![
            f("A", GoType::Int),
            f("B", GoType::String),
            f("C", GoType::Float64),
        ],
    )
}

fn dx_basic() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxBasicCmd",
        vec![
            f("IntF", GoType::Int),
            f("Int8F", GoType::Int8),
            f("Uint16F", GoType::Uint16),
            f("Int64F", GoType::Int64),
            f("Uint64F", GoType::Uint64),
            f("F32", GoType::Float32),
            f("F64", GoType::Float64),
            f("BoolF", GoType::Bool),
            f("StrF", GoType::String),
        ],
    )
}

fn dx_get_block() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxGetBlockCmd",
        vec![
            f("Hash", GoType::String),
            f("Verbose", GoType::Bool.ptr()).with_default("true"),
            f("VerboseTx", GoType::Bool.ptr()),
        ],
    )
}

fn dx_count() -> GoType {
    GoType::strukt("dcrjson", "dxCountCmd", vec![])
}

fn dx_opts() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxOptsCmd",
        vec![
            f("Req", GoType::String),
            f("OptInt", GoType::Int.ptr()).with_default("3"),
            f("OptStr", GoType::String.ptr()).with_default("\"def\""),
            f("OptF64", GoType::Float64.ptr()).with_default("0.1"),
            f("OptBool", GoType::Bool.ptr()),
        ],
    )
}

fn dx_nested() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxNestedCmd",
        vec![
            f("Name", GoType::String),
            f("Sub", dx_sub()),
            f("Subs", dx_sub().slice()),
            f(
                "Data",
                GoType::Map(Box::new(GoType::String), Box::new(GoType::Float64)),
            ),
            f("Arr", GoType::Array(2, Box::new(GoType::String))),
            f("Names", GoType::String.slice()),
            f("Entries", GoType::String.slice()),
            f("Addresses", GoType::String.slice()),
            f("Caps", dx_sub().ptr()).with_default("{\"a\":7,\"b\":\"x\",\"c\":2.5}"),
        ],
    )
}

fn dx_usage() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxUsageCmd",
        vec![
            f("Filter", GoType::String).with_usage("\"filter\""),
            f("Ids", GoType::Int.slice()),
            f("Verbose", GoType::Bool.ptr()).with_usage("verbose?"),
        ],
    )
}

fn dx_bytes() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxBytesCmd",
        vec![f("Data", GoType::Uint8.slice())],
    )
}

fn dx_named() -> GoType {
    GoType::strukt("dcrjson", "dxNamedCmd", vec![f("Tag", GoType::String)])
}

fn conv_cmd(name: &str, field_type: GoType) -> GoType {
    GoType::strukt("dcrjson", name, vec![f("V", field_type)])
}

fn dx_dup() -> GoType {
    GoType::strukt("dcrjson", "dxDupCmd", vec![f("A", GoType::Int)])
}

fn dx_bad_default() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxBadDefault",
        vec![f("A", GoType::Int).with_default("1")],
    )
}

fn dx_inner_result() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxInnerResult",
        vec![
            f("X", GoType::Int32).with_json_tag("x"),
            f("Y", GoType::String).with_json_tag("y"),
        ],
    )
}

fn dx_item_result() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxItemResult",
        vec![
            f("Key", GoType::String).with_json_tag("key"),
            f("Count", GoType::Int64).with_json_tag("count"),
            f("Inner", dx_inner_result()).with_json_tag("inner"),
            f("Ratio", GoType::Float64),
        ],
    )
}

fn dx_help_result() -> GoType {
    GoType::strukt(
        "dcrjson",
        "dxHelpResult",
        vec![
            f("Total", GoType::Int64).with_json_tag("total"),
            f("Flag", GoType::Bool).with_json_tag("flag"),
            f("Name", GoType::String).with_json_tag("name"),
            f("Rate", GoType::Float64).with_json_tag("rate"),
            f("Items", dx_item_result().slice()).with_json_tag("items"),
            f("Tags", GoType::String.slice()).with_json_tag("tags"),
            f("Info", dx_item_result()).with_json_tag("info"),
            f(
                "Data",
                GoType::Map(Box::new(GoType::String), Box::new(GoType::Float64)),
            )
            .with_json_tag("data"),
            f("MaybeI", GoType::Int64.ptr()).with_json_tag("maybei"),
        ],
    )
}

// Values used across marshal rows.

fn sub_value(a: i64, b: &str, c: f64) -> GoValue {
    GoValue::Struct(vec![
        GoValue::Int(a),
        GoValue::String(b.to_string()),
        GoValue::Float64(c),
    ])
}

fn basic_value(
    int_f: i64,
    i8f: i64,
    u16f: u64,
    i64f: i64,
    u64f: u64,
    f32v: f32,
    f64v: f64,
    boolf: bool,
    strf: &str,
) -> CmdInstance {
    CmdInstance::new(
        dx_basic().ptr(),
        vec![
            GoValue::Int(int_f),
            GoValue::Int(i8f),
            GoValue::Uint(u16f),
            GoValue::Int(i64f),
            GoValue::Uint(u64f),
            GoValue::Float32(f32v),
            GoValue::Float64(f64v),
            GoValue::Bool(boolf),
            GoValue::String(strf.to_string()),
        ],
    )
}

/// The register battery in dump order: label, method, params type,
/// flags.
fn register_battery() -> Vec<(&'static str, Method, GoType, UsageFlag)> {
    let m = Method::plain;
    vec![
        ("basic", m("dxbasic"), dx_basic().ptr(), UsageFlag(0)),
        (
            "getblock",
            m("dxgetblock"),
            dx_get_block().ptr(),
            UsageFlag(0),
        ),
        ("count", m("dxcount"), dx_count().ptr(), UsageFlag(0)),
        ("opts", m("dxopts"), dx_opts().ptr(), UsageFlag(0)),
        ("nested", m("dxnested"), dx_nested().ptr(), UsageFlag(0)),
        ("usage", m("dxusage"), dx_usage().ptr(), UF_WEBSOCKET_ONLY),
        ("bytes", m("dxbytes"), dx_bytes().ptr(), UF_NOTIFICATION),
        (
            "convi8",
            m("dxconvi8"),
            conv_cmd("dxConvI8Cmd", GoType::Int8).ptr(),
            UsageFlag(0),
        ),
        (
            "convi16",
            m("dxconvi16"),
            conv_cmd("dxConvI16Cmd", GoType::Int16).ptr(),
            UsageFlag(0),
        ),
        (
            "convu8",
            m("dxconvu8"),
            conv_cmd("dxConvU8Cmd", GoType::Uint8).ptr(),
            UsageFlag(0),
        ),
        (
            "convi64",
            m("dxconvi64"),
            conv_cmd("dxConvI64Cmd", GoType::Int64).ptr(),
            UsageFlag(0),
        ),
        (
            "convu64",
            m("dxconvu64"),
            conv_cmd("dxConvU64Cmd", GoType::Uint64).ptr(),
            UsageFlag(0),
        ),
        (
            "convf32",
            m("dxconvf32"),
            conv_cmd("dxConvF32Cmd", GoType::Float32).ptr(),
            UsageFlag(0),
        ),
        (
            "convf64",
            m("dxconvf64"),
            conv_cmd("dxConvF64Cmd", GoType::Float64).ptr(),
            UsageFlag(0),
        ),
        (
            "convbool",
            m("dxconvbool"),
            conv_cmd("dxConvBoolCmd", GoType::Bool).ptr(),
            UsageFlag(0),
        ),
        (
            "convstr",
            m("dxconvstr"),
            conv_cmd("dxConvStrCmd", GoType::String).ptr(),
            UsageFlag(0),
        ),
        (
            "convarr",
            m("dxconvarr"),
            conv_cmd("dxConvArrCmd", GoType::Array(2, Box::new(GoType::String))).ptr(),
            UsageFlag(0),
        ),
        (
            "convslice",
            m("dxconvslice"),
            conv_cmd("dxConvSliceCmd", GoType::String.slice()).ptr(),
            UsageFlag(0),
        ),
        (
            "convstruct",
            m("dxconvstruct"),
            conv_cmd("dxConvStructCmd", dx_sub()).ptr(),
            UsageFlag(0),
        ),
        (
            "convmap",
            m("dxconvmap"),
            conv_cmd(
                "dxConvMapCmd",
                GoType::Map(Box::new(GoType::String), Box::new(GoType::Float64)),
            )
            .ptr(),
            UsageFlag(0),
        ),
        (
            "convptri8",
            m("dxconvptri8"),
            conv_cmd("dxConvPtrI8Cmd", GoType::Int8.ptr()).ptr(),
            UsageFlag(0),
        ),
        (
            "named",
            Method::typed("dcrjson.dxMethod", "dxnamed"),
            dx_named().ptr(),
            UsageFlag(0),
        ),
        ("dup-setup", m("dxdup"), dx_dup().ptr(), UsageFlag(0)),
        (
            "dupmethod",
            m("dxdup"),
            dx_bad_default().ptr(),
            UsageFlag(0),
        ),
        ("duptype", m("dxdup2"), dx_dup().ptr(), UsageFlag(0)),
        (
            "badflags",
            m("dxbadflags"),
            dx_bad_default().ptr(),
            UsageFlag(1 << 3),
        ),
        (
            "badflags2",
            m("dxbadflags"),
            dx_bad_default().ptr(),
            UsageFlag(0xffffffff),
        ),
        ("nonptr", m("dxnonptr"), GoType::Int, UsageFlag(0)),
        (
            "ptrnonstruct",
            m("dxptrnonstruct"),
            GoType::Int.ptr(),
            UsageFlag(0),
        ),
        (
            "embedded",
            m("dxembedded"),
            GoType::strukt(
                "dcrjson",
                "dxEmbedded",
                vec![f("dxSub", dx_sub()).embedded()],
            )
            .ptr(),
            UsageFlag(0),
        ),
        (
            "unexported",
            m("dxunexported"),
            GoType::strukt(
                "dcrjson",
                "dxUnexported",
                vec![f("a", GoType::Int).private()],
            )
            .ptr(),
            UsageFlag(0),
        ),
        (
            "chanfield",
            m("dxchanfield"),
            GoType::strukt(
                "dcrjson",
                "dxChanField",
                vec![f("C", GoType::Chan(Box::new(GoType::Int)))],
            )
            .ptr(),
            UsageFlag(0),
        ),
        (
            "ptrptr",
            m("dxptrptr"),
            GoType::strukt("dcrjson", "dxPtrPtr", vec![f("P", GoType::Int.ptr().ptr())]).ptr(),
            UsageFlag(0),
        ),
        (
            "iface",
            m("dxiface"),
            GoType::strukt("dcrjson", "dxIfaceField", vec![f("I", GoType::Interface)]).ptr(),
            UsageFlag(0),
        ),
        (
            "funcfield",
            m("dxfuncfield"),
            GoType::strukt("dcrjson", "dxFuncField", vec![f("F", GoType::Func)]).ptr(),
            UsageFlag(0),
        ),
        (
            "complex",
            m("dxcomplex"),
            GoType::strukt("dcrjson", "dxC64", vec![f("C", GoType::Complex64)]).ptr(),
            UsageFlag(0),
        ),
        (
            "nonopt",
            m("dxnonopt"),
            GoType::strukt(
                "dcrjson",
                "dxNonOpt",
                vec![f("A", GoType::Int.ptr()), f("B", GoType::Int)],
            )
            .ptr(),
            UsageFlag(0),
        ),
        (
            "baddefault",
            m("dxbaddefault"),
            dx_bad_default().ptr(),
            UsageFlag(0),
        ),
        (
            "wrongdefault",
            m("dxwrongdefault"),
            GoType::strukt(
                "dcrjson",
                "dxWrongDefault",
                vec![f("A", GoType::Int.ptr()).with_default("1.7")],
            )
            .ptr(),
            UsageFlag(0),
        ),
    ]
}

/// The marshalcmd battery: label, id, command instance.
fn marshalcmd_battery() -> Vec<(&'static str, RpcId, CmdInstance)> {
    vec![
        (
            "basic-full",
            RpcId::Int(1),
            basic_value(
                -1,
                -128,
                65535,
                9223372036854775807,
                18446744073709551615,
                3.14,
                0.1,
                true,
                "héllo<&>\n",
            ),
        ),
        (
            "basic-floats",
            RpcId::Str("fid".to_string()),
            basic_value(0, 0, 0, 0, 0, 1e21, 1e-7, false, ""),
        ),
        (
            "basic-floats2",
            RpcId::Float(1.5),
            basic_value(0, 0, 0, 0, 0, 16777217.0, 1e20, false, ""),
        ),
        (
            "basic-floats3",
            RpcId::Int(1),
            basic_value(0, 0, 0, 0, 0, 1.5e-8, 1234567.0, false, ""),
        ),
        (
            "getblock-full",
            RpcId::Int(1),
            CmdInstance::new(
                dx_get_block().ptr(),
                vec![
                    GoValue::String("h".to_string()),
                    GoValue::Bool(false),
                    GoValue::Bool(true),
                ],
            ),
        ),
        (
            "getblock-cut",
            RpcId::Int(1),
            CmdInstance::new(
                dx_get_block().ptr(),
                vec![
                    GoValue::String("h".to_string()),
                    GoValue::Bool(true),
                    GoValue::Null,
                ],
            ),
        ),
        (
            "getblock-min",
            RpcId::Null,
            CmdInstance::new(
                dx_get_block().ptr(),
                vec![
                    GoValue::String("h".to_string()),
                    GoValue::Null,
                    GoValue::Null,
                ],
            ),
        ),
        (
            "count",
            RpcId::Uint(18446744073709551615),
            CmdInstance::new(dx_count().ptr(), vec![]),
        ),
        (
            "nested",
            RpcId::Int(1),
            CmdInstance::new(
                dx_nested().ptr(),
                vec![
                    GoValue::String("n".to_string()),
                    sub_value(1, "b", 2.5),
                    GoValue::Array(vec![sub_value(2, "x", 0.0), sub_value(-3, "", 1e21)]),
                    GoValue::Map(vec![
                        ("zeta".to_string(), GoValue::Float64(1.5)),
                        ("Alpha".to_string(), GoValue::Float64(-2.0)),
                        ("10".to_string(), GoValue::Float64(3.0)),
                        ("2".to_string(), GoValue::Float64(4.0)),
                    ]),
                    GoValue::Array(vec![
                        GoValue::String("p".to_string()),
                        GoValue::String("q".to_string()),
                    ]),
                    GoValue::Array(vec![
                        GoValue::String("n1".to_string()),
                        GoValue::String("n2".to_string()),
                    ]),
                    GoValue::Array(vec![]),
                    GoValue::Null,
                    sub_value(9, "cap", -0.5),
                ],
            ),
        ),
        (
            "bytes",
            RpcId::Int(1),
            CmdInstance::new(
                dx_bytes().ptr(),
                vec![GoValue::Array(vec![
                    GoValue::Uint(0),
                    GoValue::Uint(1),
                    GoValue::Uint(2),
                    GoValue::Uint(250),
                    GoValue::Uint(255),
                ])],
            ),
        ),
        (
            "bytes-empty",
            RpcId::Int(1),
            CmdInstance::new(dx_bytes().ptr(), vec![GoValue::Null]),
        ),
        (
            "named",
            RpcId::Int(1),
            CmdInstance::new(dx_named().ptr(), vec![GoValue::String("t".to_string())]),
        ),
        (
            "unregistered",
            RpcId::Int(1),
            CmdInstance::nil_of(GoType::Int.ptr()),
        ),
        (
            "nilcmd",
            RpcId::Int(1),
            CmdInstance::nil_of(dx_get_block().ptr()),
        ),
        (
            "badid",
            RpcId::Invalid("[]int".to_string()),
            CmdInstance::new(dx_count().ptr(), vec![]),
        ),
    ]
}

/// The newcmd battery: label, method, args.
fn newcmd_battery() -> Vec<(&'static str, &'static str, Vec<Arg>)> {
    let i8t = |v: i64| Arg::typed(GoType::Int8, GoValue::Int(v));
    let i16t = |v: i64| Arg::typed(GoType::Int16, GoValue::Int(v));
    let u16t = |v: u64| Arg::typed(GoType::Uint16, GoValue::Uint(v));
    let uintt = |v: u64| Arg::typed(GoType::Uint, GoValue::Uint(v));
    let u64t = |v: u64| Arg::typed(GoType::Uint64, GoValue::Uint(v));
    let f32t = |v: f32| Arg::typed(GoType::Float32, GoValue::Float32(v));
    vec![
        ("same", "dxconvi8", vec![i8t(100)]),
        (
            "srcptr",
            "dxconvi8",
            vec![Arg::typed(GoType::Int8.ptr(), GoValue::Int(100))],
        ),
        ("destptr", "dxconvptri8", vec![i8t(100)]),
        (
            "convsrcptr",
            "dxconvi16",
            vec![Arg::typed(GoType::Int8.ptr(), GoValue::Int(100))],
        ),
        (
            "bothptr",
            "dxconvptri8",
            vec![Arg::typed(GoType::Int16.ptr(), GoValue::Int(100))],
        ),
        ("i16-i8", "dxconvi8", vec![i16t(100)]),
        ("i16-u8", "dxconvu8", vec![i16t(100)]),
        ("u16-i8", "dxconvi8", vec![u16t(100)]),
        ("u16-u8", "dxconvu8", vec![u16t(100)]),
        ("f32-f64", "dxconvf64", vec![f32t(1.5)]),
        ("f64-f32", "dxconvf32", vec![Arg::f64(1.5)]),
        ("str-bool", "dxconvbool", vec![Arg::str("true")]),
        ("str-i8", "dxconvi8", vec![Arg::str("100")]),
        ("str-i8-hex", "dxconvi8", vec![Arg::str("0x14")]),
        ("str-u8", "dxconvu8", vec![Arg::str("100")]),
        ("str-f32", "dxconvf32", vec![Arg::str("1.5")]),
        (
            "namedstr-str",
            "dxconvstr",
            vec![Arg::typed(
                GoType::Named(
                    "dcrjson".to_string(),
                    "dxFoo".to_string(),
                    Box::new(GoType::String),
                ),
                GoValue::String("foo".to_string()),
            )],
        ),
        (
            "str-arr",
            "dxconvarr",
            vec![Arg::str("[\"test\",\"test2\"]")],
        ),
        (
            "str-slice",
            "dxconvslice",
            vec![Arg::str("[\"test\",\"test2\"]")],
        ),
        (
            "str-struct",
            "dxconvstruct",
            vec![Arg::str("{\"A\":100,\"B\":\"z\",\"C\":1.5}")],
        ),
        ("str-map", "dxconvmap", vec![Arg::str("{\"1Address\":1.5}")]),
        ("err-int-str", "dxconvstr", vec![Arg::int(0)]),
        ("err-ovf-int", "dxconvi8", vec![Arg::int(128)]),
        ("err-ovf-int-uint", "dxconvu8", vec![Arg::int(256)]),
        ("err-neg-uint", "dxconvu8", vec![Arg::int(-1)]),
        ("err-int-float", "dxconvf32", vec![Arg::int(256)]),
        ("err-ovf-u64-i64", "dxconvi64", vec![u64t(1u64 << 63)]),
        ("err-ovf-uint-int", "dxconvi8", vec![uintt(128)]),
        ("err-ovf-uint-uint", "dxconvu8", vec![uintt(256)]),
        ("err-uint-float", "dxconvf32", vec![uintt(256)]),
        ("err-float-int", "dxconvi64", vec![f32t(1.0)]),
        (
            "err-ovf-f64-f32",
            "dxconvf32",
            vec![Arg::f64(1.7976931348623157e+308)],
        ),
        ("err-str-bool", "dxconvbool", vec![Arg::str("foo")]),
        ("err-str-int", "dxconvi8", vec![Arg::str("foo")]),
        ("err-ovf-str-int", "dxconvi8", vec![Arg::str("128")]),
        ("err-str-uint", "dxconvu8", vec![Arg::str("foo")]),
        ("err-neg-str-uint", "dxconvu8", vec![Arg::str("-1")]),
        ("err-ovf-str-uint", "dxconvu8", vec![Arg::str("256")]),
        ("err-str-float", "dxconvf32", vec![Arg::str("foo")]),
        (
            "err-ovf-str-float",
            "dxconvf32",
            vec![Arg::str("1.7976931348623157e+308")],
        ),
        ("err-str-arr", "dxconvarr", vec![Arg::str("foo")]),
        ("err-str-slice", "dxconvslice", vec![Arg::str("foo")]),
        ("err-str-struct", "dxconvstruct", vec![Arg::str("foo")]),
        ("err-str-map", "dxconvmap", vec![Arg::str("foo")]),
        ("err-bool-int", "dxconvi8", vec![Arg::bool(true)]),
        ("err-unregistered", "dxbogus", vec![]),
        ("err-toofew", "dxgetblock", vec![]),
        ("err-toomany", "dxcount", vec![Arg::str("123")]),
        ("optional-tail", "dxgetblock", vec![Arg::str("h")]),
        (
            "optional-mid",
            "dxgetblock",
            vec![Arg::str("h"), Arg::bool(false)],
        ),
    ]
}

/// The parseparams battery: label, method, raw params.
fn parseparams_battery() -> Vec<(&'static str, &'static str, Vec<&'static str>)> {
    vec![
        ("getblock-defaults", "dxgetblock", vec![r#""h""#]),
        (
            "getblock-full",
            "dxgetblock",
            vec![r#""h""#, "false", "true"],
        ),
        ("getblock-null-opt", "dxgetblock", vec![r#""h""#, "null"]),
        ("opts-defaults", "dxopts", vec![r#""r""#]),
        ("opts-partial", "dxopts", vec![r#""r""#, "9"]),
        (
            "basic-full",
            "dxbasic",
            vec![
                "-1",
                "-128",
                "65535",
                "42",
                "18446744073709551615",
                "3.14",
                "1e-7",
                "true",
                r#""s""#,
            ],
        ),
        (
            "basic-null-req",
            "dxbasic",
            vec!["null", "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "nested",
            "dxnested",
            vec![
                r#""n""#,
                r#"{"a":1,"b":"b","c":2.5}"#,
                r#"[{"a":2}]"#,
                r#"{"k":1}"#,
                r#"["p","q","extra"]"#,
                r#"["n1"]"#,
                "[]",
                "null",
                r#"{"a":9,"b":"cap","c":-0.5}"#,
            ],
        ),
        (
            "nested-default-struct",
            "dxnested",
            vec![r#""n""#, r#"{"a":1}"#, "[]", "{}", "[]", "[]", "[]", "[]"],
        ),
        (
            "err-str-int",
            "dxbasic",
            vec![r#""x""#, "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-bool-int",
            "dxbasic",
            vec!["true", "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-frac-int",
            "dxbasic",
            vec!["3.14", "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-exp-int",
            "dxbasic",
            vec!["1e2", "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-ovf-i8",
            "dxbasic",
            vec!["1", "128", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-neg-u16",
            "dxbasic",
            vec!["1", "1", "-1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-ovf-u16",
            "dxbasic",
            vec!["1", "1", "70000", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-ovf-f32",
            "dxbasic",
            vec!["1", "1", "1", "1", "1", "1e39", "1", "true", r#""s""#],
        ),
        (
            "err-num-str",
            "dxbasic",
            vec!["1", "1", "1", "1", "1", "1", "1", "true", "1"],
        ),
        (
            "err-num-bool",
            "dxbasic",
            vec!["1", "1", "1", "1", "1", "1", "1", "1", r#""s""#],
        ),
        (
            "err-obj-int",
            "dxbasic",
            vec![r#"{"a":1}"#, "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-arr-int",
            "dxbasic",
            vec!["[1]", "1", "1", "1", "1", "1", "1", "true", r#""s""#],
        ),
        (
            "err-leaf",
            "dxnested",
            vec![r#""n""#, r#"{"a":"x"}"#, "[]", "{}", "[]", "[]", "[]", "[]"],
        ),
        (
            "err-leaf-slice",
            "dxnested",
            vec![
                r#""n""#,
                "{}",
                r#"[{"a":1,"c":"x"}]"#,
                "{}",
                "[]",
                "[]",
                "[]",
                "[]",
            ],
        ),
        (
            "err-leaf-map",
            "dxnested",
            vec![r#""n""#, "{}", "[]", r#"{"k":"x"}"#, "[]", "[]", "[]", "[]"],
        ),
        ("err-syntax-eof", "dxgetblock", vec![r#""1"#]),
        (
            "err-syntax-arr",
            "dxnested",
            vec![r#""n""#, r#"{"a":1}"#, "[1,]", "{}", "[]", "[]", "[]", "[]"],
        ),
        (
            "err-syntax-objval",
            "dxnested",
            vec![r#""n""#, r#"{"a":}"#, "[]", "{}", "[]", "[]", "[]", "[]"],
        ),
        ("err-syntax-lit", "dxgetblock", vec![r#""h""#, "falze"]),
        ("err-syntax-begin", "dxgetblock", vec!["x"]),
        ("err-syntax-trailing", "dxgetblock", vec![r#""h" 2"#]),
        ("err-count-many", "dxcount", vec!["1"]),
        ("err-count-few", "dxgetblock", vec![]),
        (
            "err-count-range",
            "dxopts",
            vec![r#""r""#, "1", r#""s""#, "0.5", "true", "9"],
        ),
        ("err-unregistered", "dxbogus", vec![]),
    ]
}

type HelpRow = (
    &'static str,
    Method,
    Vec<(&'static str, &'static str)>,
    Vec<Option<GoType>>,
);

/// The genhelp battery: label, method, descriptions, result types.
fn genhelp_battery() -> Vec<HelpRow> {
    let m = Method::plain;
    vec![
        (
            "count-noresults",
            m("dxcount"),
            vec![("dxcount--synopsis", "Counts things.")],
            vec![],
        ),
        (
            "count-two-strings",
            m("dxcount"),
            vec![
                ("dxcount--synopsis", "Counts things."),
                ("dxcount--condition0", "no command provided"),
                ("dxcount--condition1", "command specified"),
                ("dxcount--result0", "List of commands"),
                ("dxcount--result1", "Help for command"),
            ],
            vec![Some(GoType::String.ptr()), Some(GoType::String.ptr())],
        ),
        (
            "getblock-result",
            m("dxgetblock"),
            vec![
                ("dxgetblock--synopsis", "Returns a block."),
                ("dxgetblock-hash", "The hash of the block"),
                ("dxgetblock-verbose", "Whether to be verbose"),
                ("dxgetblock-verbosetx", "Whether tx are verbose"),
                ("dxhelpresult-total", "The total"),
                ("dxhelpresult-flag", "The flag"),
                ("dxhelpresult-name", "The name"),
                ("dxhelpresult-rate", "The rate"),
                ("dxhelpresult-items", "The items"),
                ("dxhelpresult-tags", "The tags"),
                ("dxhelpresult-info", "The info"),
                ("dxhelpresult-data", "The data map"),
                ("dxhelpresult-data--key", "name"),
                ("dxhelpresult-data--value", "n.nnn"),
                ("dxhelpresult-data--desc", "The rate for name"),
                ("dxhelpresult-maybei", "Maybe an int"),
                ("dxitemresult-key", "The key"),
                ("dxitemresult-count", "The count"),
                ("dxitemresult-inner", "The inner"),
                ("dxitemresult-ratio", "The ratio"),
                ("dxinnerresult-x", "The x"),
                ("dxinnerresult-y", "The y"),
            ],
            vec![Some(dx_help_result().ptr())],
        ),
        (
            "getblock-missing",
            m("dxgetblock"),
            vec![
                ("dxgetblock--synopsis", "Returns a block."),
                ("dxgetblock-hash", "The hash of the block"),
            ],
            vec![Some(GoType::Bool.ptr())],
        ),
        (
            "nested-nothing",
            m("dxnested"),
            vec![
                ("dxnested--synopsis", "Nested args."),
                ("dxnested-name", "The name"),
                ("dxnested-sub", "The sub"),
                ("dxnested-subs", "The subs"),
                ("dxnested-data", "The data"),
                ("dxnested-data--key", "key"),
                ("dxnested-data--value", "n.nnn"),
                ("dxnested-data--desc", "The value for key"),
                ("dxnested-arr", "The arr"),
                ("dxnested-names", "The names"),
                ("dxnested-entries", "The entries"),
                ("dxnested-addresses", "The addresses"),
                ("dxnested-caps", "The caps"),
                ("dxsub-a", "The a"),
                ("dxsub-b", "The b"),
                ("dxsub-c", "The c"),
            ],
            vec![None],
        ),
        (
            "opts-defaults",
            m("dxopts"),
            vec![
                ("dxopts--synopsis", "Options."),
                ("dxopts-req", "Required string"),
                ("dxopts-optint", "Optional int"),
                ("dxopts-optstr", "Optional string"),
                ("dxopts-optf64", "Optional float"),
                ("dxopts-optbool", "Optional bool"),
            ],
            vec![Some(GoType::Bool.ptr())],
        ),
        (
            "usage-tags",
            m("dxusage"),
            vec![
                ("dxusage--synopsis", "Usage tags."),
                ("dxusage-filter", "The filter"),
                ("dxusage-ids", "The ids"),
                ("dxusage-verbose", "Verbose flag"),
            ],
            vec![Some(GoType::Int64.ptr())],
        ),
        (
            "bytes-result",
            m("dxbytes"),
            vec![
                ("dxbytes--synopsis", "Bytes."),
                ("dxbytes-data", "The data"),
            ],
            vec![Some(GoType::String.slice().ptr())],
        ),
        (
            "mapresult",
            m("dxcount"),
            vec![
                ("dxcount--synopsis", "Counts things."),
                ("dxcount--result0--key", "thing"),
                ("dxcount--result0--value", "n"),
                ("dxcount--result0--desc", "The count for thing"),
            ],
            vec![Some(
                GoType::Map(Box::new(GoType::String), Box::new(GoType::Int64)).ptr(),
            )],
        ),
        (
            "err-nonptr",
            m("dxcount"),
            vec![],
            vec![Some(GoType::String)],
        ),
        (
            "err-badelem",
            m("dxcount"),
            vec![],
            vec![Some(GoType::Chan(Box::new(GoType::Int)).ptr())],
        ),
        ("err-unregistered", m("dxbogus"), vec![], vec![]),
    ]
}

/// The reqjson battery: label, version, id, marshalled params.
fn reqjson_battery() -> Vec<(&'static str, &'static str, RpcId, Vec<String>)> {
    vec![
        (
            "v1-int",
            "1.0",
            RpcId::Int(1),
            vec!["true".to_string(), "\"x\"".to_string(), "3".to_string()],
        ),
        ("v2-int64", "2.0", RpcId::Int(-5), vec![]),
        ("junkver", "junk", RpcId::Int(1), vec![]),
        ("uintmax", "1.0", RpcId::Uint(18446744073709551615), vec![]),
        ("floatid", "1.0", RpcId::Float(1.5), vec![]),
        ("strid", "1.0", RpcId::Str("abc<&>".to_string()), vec![]),
        ("nilid", "1.0", RpcId::Null, vec!["\"only\"".to_string()]),
        (
            "badid-slice",
            "1.0",
            RpcId::Invalid("[]int".to_string()),
            vec![],
        ),
        (
            "badid-map",
            "1.0",
            RpcId::Invalid("map[string]int".to_string()),
            vec![],
        ),
    ]
}

/// The respjson battery: label, version, id, marshalled result, error.
fn respjson_battery() -> Vec<(
    &'static str,
    &'static str,
    RpcId,
    Option<String>,
    Option<RPCError>,
)> {
    let item = gojson::encode(
        &dx_item_result(),
        &GoValue::Struct(vec![
            GoValue::String("k".to_string()),
            GoValue::Int(-7),
            GoValue::Struct(vec![GoValue::Int(5), GoValue::String("y".to_string())]),
            GoValue::Float64(0.25),
        ]),
    );
    let map = gojson::encode(
        &GoType::Map(Box::new(GoType::String), Box::new(GoType::Int)),
        &GoValue::Map(vec![
            ("zeta".to_string(), GoValue::Int(1)),
            ("Alpha".to_string(), GoValue::Int(2)),
            ("10".to_string(), GoValue::Int(3)),
        ]),
    );
    let hello = gojson::encode(&GoType::String, &GoValue::String("hello<&>".to_string()));
    vec![
        ("nilresult", "1.0", RpcId::Int(1), None, None),
        ("strresult", "1.0", RpcId::Int(1), Some(hello), None),
        (
            "floatresult",
            "2.0",
            RpcId::Str("abc".to_string()),
            Some(gojson::encode(&GoType::Float64, &GoValue::Float64(3.14))),
            None,
        ),
        ("structresult", "1.0", RpcId::Int(2), Some(item), None),
        ("mapresult", "1.0", RpcId::Null, Some(map), None),
        (
            "rpcerr",
            "1.0",
            RpcId::Int(1),
            None,
            Some(err_rpc_invalid_request()),
        ),
        (
            "rpcerr-custom",
            "1.0",
            RpcId::Int(1),
            None,
            Some(RPCError::new(-8, "custom <msg>")),
        ),
        (
            "rpcerr-zero",
            "1.0",
            RpcId::Int(1),
            None,
            Some(RPCError::new(0, "")),
        ),
        (
            "rpcerr-codeonly",
            "1.0",
            RpcId::Int(1),
            None,
            Some(RPCError::new(-5, "")),
        ),
        (
            "badid",
            "1.0",
            RpcId::Invalid("[]int".to_string()),
            None,
            None,
        ),
        (
            "junkver",
            "x",
            RpcId::Int(1),
            Some("\"r\"".to_string()),
            None,
        ),
    ]
}

fn check_err(
    line: &str,
    parts: &[&str],
    result: Result<impl core::fmt::Debug, dcroxide_dcrjson::DcrjsonError>,
) {
    match result {
        Ok(v) => panic!("{line}: expected error, got {v:?}"),
        Err(e) => {
            assert_eq!(e.kind.kind_name(), parts[0], "kind for {line}");
            assert_eq!(e.description, utf8(parts[1]), "description for {line}");
        }
    }
}

#[test]
fn dcrjson_vectors() {
    let mut registry = Registry::new();
    let registers = register_battery();
    let marshals = marshalcmd_battery();
    let newcmds = newcmd_battery();
    let parses = parseparams_battery();
    let helps = genhelp_battery();
    let reqs = reqjson_battery();
    let resps = respjson_battery();

    let mut counts: HashMap<&str, usize> = HashMap::new();
    let mut reg_idx = 0usize;
    let mut cmd_idx = 0usize;
    let mut new_idx = 0usize;
    let mut pp_idx = 0usize;
    let mut help_idx = 0usize;
    let mut req_idx = 0usize;
    let mut resp_idx = 0usize;

    for line in VECTORS.lines() {
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('|').collect();
        *counts.entry(parts[0]).or_insert(0) += 1;
        match parts[0] {
            "usageflag" => {
                let fl: u32 = parts[1].parse().unwrap();
                // The rendered flags contain '|' separators themselves.
                let want = parts[2..].join("|");
                assert_eq!(format!("{}", UsageFlag(fl)), want, "usageflag {fl}");
            }
            "register" => {
                let (label, method, typ, flags) = &registers[reg_idx];
                reg_idx += 1;
                assert_eq!(*label, parts[1], "register order for {line}");
                let result = registry.register(method, typ, *flags);
                if parts[2] == "ok" {
                    result.unwrap_or_else(|e| panic!("{line}: {e}"));
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "regmethods" => {
                let type_name = match parts[1] {
                    "string" => "string",
                    "dxMethod" => "dcrjson.dxMethod",
                    other => panic!("unknown method type {other}"),
                };
                let methods = registry.registered_methods(type_name);
                assert_eq!(methods.join(","), parts[2], "regmethods {line}");
            }
            "reqjson" => {
                let (label, version, id, params) = &reqs[req_idx];
                req_idx += 1;
                assert_eq!(*label, parts[1], "reqjson order for {line}");
                let result = new_request(version, id, params.clone());
                if parts[2] == "ok" {
                    let req = result.unwrap_or_else(|e| panic!("{line}: {e}"));
                    assert_eq!(marshal_request(&req, "dxmethod"), utf8(parts[3]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "respjson" => {
                let (label, version, id, result_json, rpc_err) = &resps[resp_idx];
                resp_idx += 1;
                assert_eq!(*label, parts[1], "respjson order for {line}");
                let result =
                    marshal_response(version, id, result_json.as_deref(), rpc_err.as_ref());
                if parts[2] == "ok" {
                    let resp = result.unwrap_or_else(|e| panic!("{line}: {e}"));
                    assert_eq!(resp, utf8(parts[3]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "rpcerrstr" => {
                let code: i32 = parts[1].parse().unwrap();
                let message = utf8(parts[2]);
                let err = match code {
                    -32600 => err_rpc_invalid_request(),
                    -32601 => err_rpc_method_not_found(),
                    -32602 => err_rpc_invalid_params(),
                    -32603 => err_rpc_internal(),
                    -32700 => err_rpc_parse(),
                    other => panic!("unknown std error code {other}"),
                };
                assert_eq!(err.code, code, "{line}");
                assert_eq!(err.message, message, "{line}");
                assert_eq!(format!("{err}"), utf8(parts[3]), "{line}");
            }
            "marshalcmd" => {
                let (label, id, cmd) = &marshals[cmd_idx];
                cmd_idx += 1;
                assert_eq!(*label, parts[1], "marshalcmd order for {line}");
                let result = marshal_cmd(&registry, "1.0", id, cmd);
                if parts[2] == "ok" {
                    assert_eq!(result.unwrap(), utf8(parts[3]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "newcmd" => {
                let (label, method, args) = &newcmds[new_idx];
                new_idx += 1;
                assert_eq!(*label, parts[1], "newcmd order for {line}");
                let result = new_cmd(&registry, &Method::plain(method), args)
                    .and_then(|cmd| marshal_cmd(&registry, "1.0", &RpcId::Int(1), &cmd));
                if parts[2] == "ok" {
                    assert_eq!(result.unwrap(), utf8(parts[3]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "parseparams" => {
                let (label, method, params) = &parses[pp_idx];
                pp_idx += 1;
                assert_eq!(*label, parts[1], "parseparams order for {line}");
                let result = parse_params(&registry, &Method::plain(method), params)
                    .and_then(|cmd| marshal_cmd(&registry, "1.0", &RpcId::Int(1), &cmd));
                if parts[2] == "ok" {
                    assert_eq!(result.unwrap(), utf8(parts[3]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "usagetext" => {
                let result = registry.method_usage_text(&Method::plain(parts[1]));
                if parts.len() == 3 {
                    assert_eq!(result.unwrap(), utf8(parts[2]), "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "cmdmethod" => {
                if parts[2] == "ok" {
                    let method = registry.cmd_method(&dx_get_block().ptr()).unwrap();
                    assert_eq!(method, parts[3], "{line}");
                } else {
                    check_err(line, &parts[3..], registry.cmd_method(&GoType::Int.ptr()));
                }
            }
            "methodflags" => {
                let method = match parts[1] {
                    "dxnamed" => Method::typed("dcrjson.dxMethod", "dxnamed"),
                    "dxnamed-plainstring" => Method::plain("dxnamed"),
                    other => Method::plain(other),
                };
                let result = registry.method_usage_flags(&method);
                if parts[2] == "ok" {
                    let want: u32 = parts[3].parse().unwrap();
                    assert_eq!(result.unwrap().0, want, "{line}");
                } else {
                    check_err(line, &parts[3..], result);
                }
            }
            "genhelp" => {
                let (label, method, descs, results) = &helps[help_idx];
                help_idx += 1;
                assert_eq!(*label, parts[1], "genhelp order for {line}");
                let descs: HashMap<String, String> = descs
                    .iter()
                    .map(|(k, v)| (k.to_string(), v.to_string()))
                    .collect();
                let (help, err) = registry.generate_help(method, &descs, results);
                if parts[2] == "ok" {
                    assert!(err.is_none(), "{line}: unexpected error {err:?}");
                    assert_eq!(help, utf8(parts[3]), "{line}");
                } else {
                    // "partial": the help text (possibly empty) plus
                    // the error kind and description.
                    let err = err.unwrap_or_else(|| panic!("{line}: expected error"));
                    assert_eq!(help, utf8(parts[3]), "{line}");
                    assert_eq!(err.kind.kind_name(), parts[4], "{line}");
                    assert_eq!(err.description, utf8(parts[5]), "{line}");
                }
            }
            "concat" => {
                replay_concat(line, &parts);
            }
            other => panic!("unknown vector op {other}"),
        }
    }

    // Every battery must be fully consumed and the frozen row counts
    // must match.
    assert_eq!(reg_idx, registers.len());
    assert_eq!(cmd_idx, marshals.len());
    assert_eq!(new_idx, newcmds.len());
    assert_eq!(pp_idx, parses.len());
    assert_eq!(help_idx, helps.len());
    assert_eq!(req_idx, reqs.len());
    assert_eq!(resp_idx, resps.len());
    let expected: &[(&str, usize)] = &[
        ("usageflag", 12),
        ("register", 39),
        ("regmethods", 2),
        ("reqjson", 9),
        ("respjson", 11),
        ("rpcerrstr", 5),
        ("marshalcmd", 15),
        ("newcmd", 50),
        ("parseparams", 34),
        ("usagetext", 13),
        ("cmdmethod", 2),
        ("methodflags", 3),
        ("genhelp", 12),
        ("concat", 10),
    ];
    for (op, want) in expected {
        assert_eq!(counts.get(op), Some(want), "row count for {op}");
    }
}

fn mkhash(seed: u8) -> dcroxide_chainhash::Hash {
    let mut h = [0u8; 32];
    for (i, b) in h.iter_mut().enumerate() {
        *b = seed.wrapping_add(i as u8);
    }
    dcroxide_chainhash::Hash(h)
}

fn replay_concat(line: &str, parts: &[&str]) {
    let h1 = mkhash(0);
    let h2 = mkhash(0x40);
    let h3 = mkhash(0x80);
    let enc = |hashes: &[dcroxide_chainhash::Hash]| encode_concatenated_hashes(hashes);
    match parts[1] {
        "enc0" => assert_eq!(enc(&[]), parts[2], "{line}"),
        "enc1" => assert_eq!(enc(&[h1]), parts[2], "{line}"),
        "enc3" => assert_eq!(enc(&[h1, h2, h3]), parts[2], "{line}"),
        label => {
            let input = match label {
                "dec-empty" => String::new(),
                "dec-one" => enc(&[h1]),
                "dec-three" => enc(&[h3, h1, h2]),
                "dec-upper" => enc(&[h2]).to_uppercase(),
                "dec-odd" => "abcd12".to_string(),
                "dec-badhex" => "zz".repeat(32),
                "dec-badhex-second" => format!("{}{}", enc(&[h1]), "zz".repeat(32)),
                other => panic!("unknown concat label {other}"),
            };
            match decode_concatenated_hashes(&input) {
                Ok(hashes) => {
                    assert_eq!(parts[2], "ok", "{line}");
                    let joined: Vec<String> = hashes
                        .iter()
                        .map(|h| h.as_bytes().iter().map(|b| format!("{b:02x}")).collect())
                        .collect();
                    assert_eq!(joined.join(","), parts[3], "{line}");
                }
                Err(rpc_err) => {
                    assert_eq!(parts[2], "err", "{line}");
                    let code: i32 = parts[3].parse().unwrap();
                    assert_eq!(rpc_err.code, code, "{line}");
                    assert_eq!(rpc_err.message, utf8(parts[4]), "{line}");
                }
            }
        }
    }
}
