// SPDX-License-Identifier: ISC
//! The stake node's expiry accessors against dcrd, step by step.
//!
//! Under DCP0009 a block must revoke exactly the tickets its parent's
//! `ExpiringNextBlock` names, so that set is a consensus input, and the
//! frozen `ticketnode_vectors` replay compared everything else about the
//! node but not it.  This replays the same 120 connects and 30
//! disconnects and compares, after every step, `ExpiringNextBlock` in
//! full, `ExistsExpiredTicket` over every missed and revoked ticket (as
//! a count and a BLAKE-256 digest of the expired ones, since that set
//! only grows), and `SpentByBlock`, `MissedByBlock` and `ExpiredByBlock`.
//!
//! `data/review_ticketnode_expiring.txt` was generated by a Go test
//! placed in a copy of dcrd's `blockchain/stake` package at the parity
//! pin (b9634e01), replaying `data/ticketnode_vectors.txt` through
//! `genesisNode`, `ConnectNode` and `DisconnectNode` with the same
//! parameters.  One row per step:
//!
//! `xs <height> <expiring> <expired count>:<digest> <spent> <missed> <expired by block>`
//!
//! The replay reaches 111 non-empty expiring sets, and in 14 of them a
//! next-block winner sits at the expiring height and has to be left out.

// Test-harness arithmetic over bounded lengths.
#![allow(clippy::arithmetic_side_effects)]

use dcroxide_chainhash::{Hash, hash_b};
use dcroxide_stake::ticketnode::{Node, StakeNodeParams};
use dcroxide_testutil::unhex;

const PARAMS: StakeNodeParams = StakeNodeParams {
    votes_per_block: 5,
    stake_validation_begin_height: 24,
    stake_enable_height: 8,
    ticket_expiry_blocks: 40,
};

fn parse_hash(s: &str) -> Hash {
    let bytes = unhex(s);
    let mut h = [0u8; 32];
    h.copy_from_slice(&bytes);
    Hash(h)
}

fn parse_hashes(s: &str) -> Vec<Hash> {
    if s == "-" {
        return Vec::new();
    }
    s.split(',').map(parse_hash).collect()
}

fn raw_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Every missed, then every revoked, ticket that `exists_expired_ticket`
/// reports, as `<count>:<digest of the concatenated hashes>`.
fn expired_digest(node: &Node) -> String {
    let expired: Vec<Hash> = node
        .missed_tickets()
        .into_iter()
        .chain(node.revoked_tickets())
        .filter(|h| node.exists_expired_ticket(h))
        .collect();
    let mut buf = Vec::with_capacity(expired.len() * 32);
    for h in &expired {
        buf.extend_from_slice(&h.0);
    }
    format!("{}:{}", expired.len(), raw_hex(&hash_b(&buf)))
}

fn check_expiry(node: &Node, row: &str, step: &str) {
    let f: Vec<&str> = row.split(' ').collect();
    assert_eq!(f.len(), 7, "{step}: malformed row {row}");
    assert_eq!(f[0], "xs", "{step}: expected an xs row");
    let height: u32 = f[1].parse().expect("height");
    assert_eq!(node.height(), height, "{step}: height");

    let expiring = node.expiring_next_block();
    assert_eq!(expiring, parse_hashes(f[2]), "{step}: ExpiringNextBlock");
    for h in &expiring {
        assert!(
            node.exists_live_ticket(h) && !node.exists_expired_ticket(h),
            "{step}: an expiring ticket is live and not yet expired"
        );
    }
    assert_eq!(expired_digest(node), f[3], "{step}: ExistsExpiredTicket");
    assert_eq!(
        node.spent_by_block(),
        parse_hashes(f[4]),
        "{step}: SpentByBlock"
    );
    assert_eq!(
        node.missed_by_block(),
        parse_hashes(f[5]),
        "{step}: MissedByBlock"
    );
    assert_eq!(
        node.expired_by_block(),
        parse_hashes(f[6]),
        "{step}: ExpiredByBlock"
    );
}

#[test]
fn ticketnode_expiry_accessors_match_dcrd() {
    let steps = include_str!("data/ticketnode_vectors.txt");
    let mut expiry_rows = include_str!("data/review_ticketnode_expiring.txt").lines();

    let mut node = Node::genesis(PARAMS);
    let mut ivs: Vec<Hash> = vec![Hash([0u8; 32])];
    let mut news: Vec<Vec<Hash>> = vec![Vec::new()];
    let mut nodes: Vec<Node> = vec![node.clone()];

    let mut counts = [0usize; 2];
    for line in steps.lines() {
        let f: Vec<&str> = line.split(' ').collect();
        match f[0] {
            "blk" => {
                let iv = parse_hash(f[2]);
                let new_tickets = parse_hashes(f[5]);
                node = node
                    .connect(iv, &parse_hashes(f[3]), &parse_hashes(f[4]), &new_tickets)
                    .unwrap_or_else(|e| panic!("blk {}: connect failed: {e:?}", f[1]));
                ivs.push(iv);
                news.push(new_tickets);
                nodes.push(node.clone());
                let row = expiry_rows.next().expect("an xs row per connect");
                check_expiry(&node, row, &format!("blk {}", f[1]));
                counts[0] += 1;
            }
            "undo" => {
                let h: usize = f[1].parse().expect("height");
                node = node
                    .disconnect(ivs[h - 1], nodes[h - 1].undo_data(), &news[h - 1])
                    .unwrap_or_else(|e| panic!("undo {h}: disconnect failed: {e:?}"));
                ivs.truncate(h);
                news.truncate(h);
                nodes.truncate(h);
                let row = expiry_rows.next().expect("an xs row per disconnect");
                check_expiry(&node, row, &format!("undo {h}"));
                counts[1] += 1;
            }
            // State rows belong to the frozen replay; error rows leave
            // the node unchanged.
            "state" | "err" => {}
            other => panic!("unknown row tag {other}"),
        }
    }
    assert!(expiry_rows.next().is_none(), "unconsumed xs rows");
    assert_eq!(counts, [120, 30], "step counts");
}
