// SPDX-License-Identifier: ISC
//! Merkle tree inclusion proofs (dcrd blockchain/standalone
//! `inclusionproof.go`).

use alloc::vec::Vec;

use dcroxide_chainhash::{HASH_SIZE, Hash, hash_h};

/// Masks used to calculate floor(log2(x)) of a u32 in five constant
/// steps, derived from `(2^(2^x) - 1) * (2^(2^x))` for x in 4..0 (dcrd
/// `log2FloorMasks`).
const LOG2_FLOOR_MASKS: [u32; 5] = [0xffff_0000, 0xff00, 0xf0, 0xc, 0x2];

/// ceil(log2(n)) in a constant five steps (dcrd `fastLog2Ceil`).
fn fast_log2_ceil(mut n: u32) -> u8 {
    // The final answer will be one more when the input is greater than
    // one and not a power of two.
    let mut rv: u8 = 0;
    if n & n.wrapping_sub(1) != 0 {
        rv += 1;
    }
    let mut exponent: u8 = 16;
    for mask in LOG2_FLOOR_MASKS {
        if n & mask != 0 {
            rv += exponent;
            n >>= exponent;
        }
        exponent >>= 1;
    }
    rv
}

/// Generate a merkle tree inclusion proof for the leaf at the given
/// index: the ceil(log2(x)) intermediate sibling hashes along the path
/// from the leaf to the root (dcrd `GenerateInclusionProof`).  An empty
/// tree or out-of-range index yields an empty proof.
pub fn generate_inclusion_proof(leaves: &[Hash], mut leaf_index: u32) -> Vec<Hash> {
    if leaves.is_empty() {
        return Vec::new();
    }

    if leaf_index as usize >= leaves.len() {
        return Vec::new();
    }

    // Copy the leaves so they can be safely mutated by the in-place
    // reduction below.
    let mut leaves_buf: Vec<Hash> = Vec::with_capacity(leaves.len() + (leaves.len() & 1));
    leaves_buf.extend_from_slice(leaves);
    let mut leaves = leaves_buf;

    // The reduction works exactly like the in-place merkle root
    // calculation while additionally saving the sibling hash opposite
    // the branch containing the leaf index at each level.
    let mut buf = [0u8; 2 * HASH_SIZE];
    let proof_size = fast_log2_ceil(leaves.len() as u32);
    let mut proof: Vec<Hash> = Vec::with_capacity(proof_size as usize);
    let mut len = leaves.len();
    while len > 1 {
        // When there is no right child, the parent is generated by
        // hashing the concatenation of the left child with itself.
        if len & 1 != 0 {
            let last = leaves[len - 1];
            if leaves.len() > len {
                leaves[len] = last;
            } else {
                leaves.push(last);
            }
            len += 1;
        }

        // Hash each pair into its parent while saving the sibling hash
        // needed to prove inclusion of the provided leaf index.  The
        // sibling is on the left when the index is odd at this level and
        // on the right otherwise.
        let half_leaf_index = leaf_index >> 1;
        for i in 0..(len >> 1) as u32 {
            let left_leaf = leaves[(i << 1) as usize];
            let right_leaf = leaves[((i << 1) + 1) as usize];
            if i == half_leaf_index {
                if leaf_index & 1 != 0 {
                    proof.push(left_leaf);
                } else {
                    proof.push(right_leaf);
                }
            }
            buf[..HASH_SIZE].copy_from_slice(&left_leaf.0);
            buf[HASH_SIZE..].copy_from_slice(&right_leaf.0);
            leaves[i as usize] = hash_h(&buf);
        }
        len >>= 1;
        leaf_index = half_leaf_index;
    }

    proof
}

/// Whether the given leaf hash, original leaf index, and inclusion proof
/// recalculate a merkle root matching the provided root (dcrd
/// `VerifyInclusionProof`).
pub fn verify_inclusion_proof(
    root: &Hash,
    leaf: &Hash,
    mut leaf_index: u32,
    proof: &[Hash],
) -> bool {
    // Ensure the leaf index to prove is within the possible range per
    // the proof: the proof is a log2(x) construction, so the max
    // possible 0-based leaf index is 2^len(proof) - 1.
    let proof_len = proof.len();
    if proof_len > 32 {
        return false;
    }
    let max_leaf_index = (1u64 << proof_len as u8).wrapping_sub(1) as u32;
    if leaf_index > max_leaf_index {
        return false;
    }

    // Treat each proof entry as the sibling opposite the known value at
    // each level, hashing upward and finally comparing to the root.
    let mut buf = [0u8; 2 * HASH_SIZE];
    let mut intermediate = *leaf;
    for sibling in proof {
        // The sibling is on the left when the index at this level is
        // odd; otherwise it's on the right.
        if leaf_index & 1 != 0 {
            buf[..HASH_SIZE].copy_from_slice(&sibling.0);
            buf[HASH_SIZE..].copy_from_slice(&intermediate.0);
        } else {
            buf[..HASH_SIZE].copy_from_slice(&intermediate.0);
            buf[HASH_SIZE..].copy_from_slice(&sibling.0);
        }
        intermediate = hash_h(&buf);

        leaf_index >>= 1;
    }

    *root == intermediate
}
