// SPDX-License-Identifier: ISC
//! Merkle root calculations (dcrd blockchain/standalone `merkle.go`).

use alloc::vec::Vec;

use dcroxide_chainhash::{HASH_SIZE, Hash, hash_h};
use dcroxide_wire::MsgTx;

/// In-place version of [`calc_merkle_root`] that mutates the provided
/// buffer to avoid extra allocations (dcrd `CalcMerkleRootInPlace`).
///
/// The algorithm replaces the leftmost entries with the hashes of each
/// subsequent pair and halves the slice each level; an unbalanced level
/// duplicates its final node so it is concatenated with itself.
pub fn calc_merkle_root_in_place(leaves: &mut Vec<Hash>) -> Hash {
    if leaves.is_empty() {
        // All zero.
        return Hash::ZERO;
    }

    let mut buf = [0u8; 2 * HASH_SIZE];
    let mut len = leaves.len();
    while len > 1 {
        // When there is no right child, the parent is generated by
        // hashing the concatenation of the left child with itself.
        if len & 1 != 0 {
            let last = leaves[len - 1];
            if leaves.len() > len {
                leaves[len] = last;
            } else {
                leaves.push(last);
            }
            len += 1;
        }

        // Set the parent node to the hash of the concatenation of the
        // left and right children.
        for i in 0..len / 2 {
            buf[..HASH_SIZE].copy_from_slice(&leaves[i * 2].0);
            buf[HASH_SIZE..].copy_from_slice(&leaves[i * 2 + 1].0);
            leaves[i] = hash_h(&buf);
        }
        len /= 2;
    }
    leaves[0]
}

/// Treat the provided hashes as merkle tree leaves and return the root
/// (dcrd `CalcMerkleRoot`); an empty slice yields the zero hash.
pub fn calc_merkle_root(leaves: &[Hash]) -> Hash {
    if leaves.is_empty() {
        // All zero.
        return Hash::ZERO;
    }

    let mut dup: Vec<Hash> = Vec::with_capacity(leaves.len() + (leaves.len() & 1));
    dup.extend_from_slice(leaves);
    calc_merkle_root_in_place(&mut dup)
}

/// The merkle root over the full (witness-including) hashes of the
/// provided transactions (dcrd `CalcTxTreeMerkleRoot`).
pub fn calc_tx_tree_merkle_root(transactions: &[MsgTx]) -> Hash {
    if transactions.is_empty() {
        // All zero.
        return Hash::ZERO;
    }

    let mut leaves: Vec<Hash> = Vec::with_capacity(transactions.len() + (transactions.len() & 1));
    leaves.extend(transactions.iter().map(MsgTx::tx_hash_full));
    calc_merkle_root_in_place(&mut leaves)
}

/// The DCP0005 combined merkle root of the regular and stake transaction
/// trees: the hash of the concatenation of the two individual roots
/// (dcrd `CalcCombinedTxTreeMerkleRoot`).
pub fn calc_combined_tx_tree_merkle_root(regular_txns: &[MsgTx], stake_txns: &[MsgTx]) -> Hash {
    let regular_root = calc_tx_tree_merkle_root(regular_txns);
    let stake_root = calc_tx_tree_merkle_root(stake_txns);

    // Return the hash of the concatenation of the individual merkle
    // roots; a two-leaf merkle tree reduces to exactly this.
    let mut both = [0u8; HASH_SIZE * 2];
    both[..HASH_SIZE].copy_from_slice(&regular_root.0);
    both[HASH_SIZE..].copy_from_slice(&stake_root.0);
    hash_h(&both)
}
