// SPDX-License-Identifier: ISC
//! Replay of frozen peer vectors generated by an in-package dump test
//! running inside dcrd's peer package at release-v2.1.5.
//!
//! Negotiation rows script the remote side with the exact framed
//! bytes dcrd's fake remote sent and compare the verdict, the peer
//! state, and the local version message dcrd produced (nonce and
//! timestamp normalized, since dcrd cannot inject its randomness).

use dcroxide_chainhash::Hash;
use dcroxide_peer::{
    Config, MsgTransport, Peer, PeerAddr, PeerEnv, PeerGlobals, maybe_add_deadline, new_net_address,
};
use dcroxide_testutil::unhex;
use dcroxide_wire::{
    CurrencyNet, Message, MsgPing, MsgPong, MsgVersion, NetAddress, PROTOCOL_VERSION, ServiceFlag,
};
use std::collections::HashMap;

const VECTORS: &str = include_str!("data/peer_vectors.txt");

const NET: CurrencyNet = CurrencyNet::TEST_NET3;

fn utf8(hex: &str) -> String {
    String::from_utf8(unhex(hex)).expect("utf8 payload")
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

struct FixedEnv;

impl PeerEnv for FixedEnv {
    fn now_nanos(&mut self) -> i64 {
        1_700_000_000 * 1_000_000_000
    }

    fn rand_u64(&mut self) -> u64 {
        0x1234_5678_9abc_def0
    }

    fn shuffle_addrs(&mut self, _addrs: &mut [NetAddress]) {}
}

/// A scripted transport feeding the dump's framed remote bytes and
/// capturing everything written.
struct Scripted {
    remote: Vec<Message>,
    written: Vec<Message>,
}

impl Scripted {
    fn new(remote_frames: &[u8]) -> Scripted {
        let mut remote = Vec::new();
        let mut pos = 0usize;
        while pos < remote_frames.len() {
            let (msg, consumed) =
                dcroxide_wire::read_message(&remote_frames[pos..], PROTOCOL_VERSION, NET)
                    .expect("dump frame decodes");
            remote.push(msg);
            pos = pos.checked_add(consumed).expect("bounded");
        }
        remote.reverse();
        Scripted {
            remote,
            written: Vec::new(),
        }
    }
}

impl MsgTransport for Scripted {
    fn read_message(&mut self) -> Result<Message, String> {
        self.remote.pop().ok_or_else(|| "EOF".to_string())
    }

    fn write_message(&mut self, msg: &Message) -> Result<(), String> {
        self.written.push(msg.clone());
        Ok(())
    }
}

fn base_cfg() -> Config {
    Config {
        user_agent_name: "peertest".to_string(),
        user_agent_version: "1.2.3".to_string(),
        services: ServiceFlag::NODE_NETWORK,
        newest_block: Some(Box::new(|| Ok((Hash::ZERO, 12345)))),
        net: NET,
        ..Config::default()
    }
}

fn na_10123() -> NetAddress {
    let mut ip = [0u8; 16];
    ip[10] = 0xff;
    ip[11] = 0xff;
    ip[12..16].copy_from_slice(&[10, 1, 2, 3]);
    NetAddress {
        timestamp: 0,
        services: ServiceFlag(0),
        ip,
        port: 19108,
    }
}

/// The peer and inbound flag for a negotiation row label, mirroring
/// the dump's configuration battery.
fn peer_for(label: &str) -> (Peer, bool) {
    let localhost = || {
        let mut ip = [0u8; 16];
        ip[10] = 0xff;
        ip[11] = 0xff;
        ip[12..16].copy_from_slice(&[127, 0, 0, 1]);
        NetAddress {
            timestamp: 0,
            services: ServiceFlag(0),
            ip,
            port: 9050,
        }
    };
    match label {
        "in-basic" | "in-nonversion" | "in-selfconn" | "in-too-old" | "in-lower-remote" => {
            let mut p = Peer::new_inbound(base_cfg());
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (p, true)
        }
        "out-basic" => {
            let mut p = Peer::new_inbound(base_cfg());
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (make_outbound_like(p), false)
        }
        "out-pver-capped" => {
            let mut cfg = base_cfg();
            cfg.protocol_version = 10;
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (make_outbound_like(p), false)
        }
        "in-proxy-match" => {
            let mut cfg = base_cfg();
            cfg.proxy = "127.0.0.1:9050".to_string();
            let mut p = Peer::new_inbound(cfg);
            p.associate("127.0.0.1:9050", localhost(), 0);
            (p, true)
        }
        "in-proxy-invalid" => {
            let mut cfg = base_cfg();
            cfg.proxy = "not a proxy".to_string();
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (p, true)
        }
        "in-proxy-nomatch" => {
            let mut cfg = base_cfg();
            cfg.proxy = "127.0.0.1:9050".to_string();
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (p, true)
        }
        "in-ua-comments" => {
            let mut cfg = base_cfg();
            cfg.user_agent_comments = vec!["comment1".to_string(), "comment2".to_string()];
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (p, true)
        }
        "in-ua-overlong" => {
            let mut cfg = base_cfg();
            cfg.user_agent_comments = vec!["x".repeat(300)];
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (p, true)
        }
        "out-newestblock-err" => {
            let mut cfg = base_cfg();
            cfg.newest_block = Some(Box::new(|| Err("newest block unavailable".to_string())));
            let mut p = Peer::new_inbound(cfg);
            p.associate("10.1.2.3:19108", na_10123(), 0);
            (make_outbound_like(p), false)
        }
        other => panic!("unknown negotiation label {other}"),
    }
}

/// The dump builds outbound peers through newPeerBase directly; the
/// inbound/outbound flag only matters for the negotiation order here.
fn make_outbound_like(p: Peer) -> Peer {
    // The core only distinguishes the two through which negotiate
    // method runs, so the peer value is reusable as-is.
    p
}

/// The state summary in the dump's format.
fn state_string(p: &Peer) -> String {
    format!(
        "pver={}|advertised={}|known={}|handshake={}|services={}|lastblock={}|startheight={}|ua={}",
        p.protocol_version(),
        advertised(p),
        p.version_known(),
        p.handshake_done(),
        p.services().0,
        p.last_block(),
        p.starting_height(),
        p.user_agent(),
    )
}

/// The advertised protocol version is observable through the
/// negotiated minimum and the known flag; the core records it, and
/// the accessor here mirrors dcrd's unexported field read.
fn advertised(p: &Peer) -> u32 {
    p.advertised_proto_ver()
}

/// Frame a version message with its nonce and timestamp normalized.
fn normalize_version_frame(msg: &MsgVersion) -> Vec<u8> {
    let mut msg = msg.clone();
    msg.nonce = 0;
    msg.timestamp = 0;
    dcroxide_wire::write_message(&Message::Version(msg), PROTOCOL_VERSION, NET)
        .expect("version frames")
}

#[test]
fn peer_vectors() {
    let mut globals = PeerGlobals::new();
    let mut env = FixedEnv;
    let mut counts: HashMap<&str, usize> = HashMap::new();

    // Stateful sequences reused across rows.
    let mut push_peer = Peer::new_inbound(base_cfg());
    let hash_a = Hash({
        let mut h = [0u8; 32];
        h[0] = 0x0a;
        h
    });
    let hash_b = Hash({
        let mut h = [0u8; 32];
        h[0] = 0x0b;
        h
    });
    let stop1 = Hash({
        let mut h = [0u8; 32];
        h[0] = 0x51;
        h
    });
    let stop2 = Hash({
        let mut h = [0u8; 32];
        h[0] = 0x52;
        h
    });

    for line in VECTORS.lines() {
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('|').collect();
        *counts.entry(parts[0]).or_insert(0) += 1;
        match parts[0] {
            "neg" => {
                let label = parts[1];
                if label == "in-selfconn" {
                    globals.put_sent_nonce(777);
                }
                let (mut peer, inbound) = peer_for(label);
                let mut transport = Scripted::new(&unhex(parts[3]));
                let result = if inbound {
                    peer.negotiate_inbound_protocol(&mut transport, &mut env, &mut globals)
                } else {
                    peer.negotiate_outbound_protocol(&mut transport, &mut env, &mut globals)
                };
                match &result {
                    Ok(_) => assert_eq!(parts[2], "ok", "{label}"),
                    Err(e) => {
                        assert_eq!(parts[2], "err", "{label}");
                        assert_eq!(e.message, utf8(parts[5]), "{label}");
                    }
                }
                // The sent local version, when one was written.
                let sent = transport.written.iter().find_map(|m| match m {
                    Message::Version(v) => Some(normalize_version_frame(v)),
                    _ => None,
                });
                let want_sent = parts[4];
                match sent {
                    Some(frame) => assert_eq!(hex(&frame), want_sent, "sent for {label}"),
                    None => assert!(want_sent.is_empty(), "expected no send for {label}"),
                }
                // The peer state summary.
                let want_state = parts[6..].join("|");
                assert_eq!(state_string(&peer), want_state, "state for {label}");
            }
            "push" => {
                let label = parts[1];
                let msg = match label {
                    "getblocks-first" | "getblocks-dup" => {
                        push_peer.push_get_blocks_msg(&[hash_a, hash_b], &stop1)
                    }
                    "getblocks-newstop" => push_peer.push_get_blocks_msg(&[hash_a, hash_b], &stop2),
                    "getblocks-nolocator" | "getblocks-nolocator-again" => {
                        push_peer.push_get_blocks_msg(&[], &stop2)
                    }
                    "getheaders-first" | "getheaders-dup" => {
                        push_peer.push_get_headers_msg(&[hash_b], &stop1)
                    }
                    other => panic!("unknown push label {other}"),
                };
                match msg {
                    Some(msg) => {
                        assert_eq!(parts[2], "sent", "{label}");
                        let framed = dcroxide_wire::write_message(&msg, PROTOCOL_VERSION, NET)
                            .expect("frames");
                        assert_eq!(hex(&framed), parts[3], "{label}");
                    }
                    None => assert_eq!(parts[2], "filtered", "{label}"),
                }
            }
            "pushaddr" => {
                let label = parts[1];
                match label {
                    "small" => {
                        let addrs = vec![
                            NetAddress {
                                timestamp: 1_700_000_000,
                                services: ServiceFlag(5),
                                ip: v4(&[1, 2, 3, 4]),
                                port: 9108,
                            },
                            NetAddress {
                                timestamp: 1_700_000_100,
                                services: ServiceFlag(9),
                                ip: {
                                    let mut ip = [0u8; 16];
                                    ip[0] = 0x20;
                                    ip[1] = 0x01;
                                    ip[2] = 0x0d;
                                    ip[3] = 0xb8;
                                    ip[15] = 0x07;
                                    ip
                                },
                                port: 19108,
                            },
                        ];
                        let (msg, sent) = push_peer.push_addr_msg(&mut env, &addrs).expect("sends");
                        assert_eq!(sent.len().to_string(), parts[2], "{label}");
                        let framed = dcroxide_wire::write_message(&msg, PROTOCOL_VERSION, NET)
                            .expect("frames");
                        assert_eq!(hex(&framed), parts[3], "{label}");
                    }
                    "big" => {
                        let addrs: Vec<NetAddress> = (0..1500u32)
                            .map(|i| NetAddress {
                                timestamp: 1_700_000_000,
                                services: ServiceFlag(i as u64),
                                ip: v4(&[1, 2, 3, 4]),
                                port: i as u16,
                            })
                            .collect();
                        let (msg, sent) = push_peer.push_addr_msg(&mut env, &addrs).expect("sends");
                        assert_eq!(sent.len().to_string(), parts[2], "{label}");
                        let count = match msg {
                            Message::Addr(a) => a.addr_list.len(),
                            _ => panic!("expected addr"),
                        };
                        assert_eq!(count.to_string(), parts[3], "{label}");
                    }
                    other => panic!("unknown pushaddr label {other}"),
                }
            }
            "ping" => {
                let reply = push_peer.handle_ping_msg(&MsgPing { nonce: 97 });
                let framed =
                    dcroxide_wire::write_message(&reply, PROTOCOL_VERSION, NET).expect("frames");
                assert_eq!(hex(&framed), parts[2], "{line}");
            }
            "pong" => {
                match parts[1] {
                    "mismatch" => {
                        push_peer.record_sent_ping(&mut env, &MsgPing { nonce: 7 });
                        push_peer.handle_pong_msg(&mut env, &MsgPong { nonce: 6 });
                    }
                    "match" => {
                        push_peer.handle_pong_msg(&mut env, &MsgPong { nonce: 7 });
                    }
                    other => panic!("unknown pong label {other}"),
                }
                assert_eq!(push_peer.last_ping_nonce().to_string(), parts[2], "{line}");
            }
            "deadline" => {
                let mut pending: HashMap<&'static str, i64> = HashMap::new();
                maybe_add_deadline(&mut pending, parts[1], 0);
                let mut keys: Vec<&str> = pending.keys().copied().collect();
                keys.sort_unstable();
                assert_eq!(keys.join(","), parts[2], "{line}");
            }
            "netaddr" => {
                let addr = match parts[1] {
                    "tcp4" => PeerAddr::Tcp {
                        ip: vec![1, 2, 3, 4],
                        port: 8333,
                    },
                    "tcp6" => PeerAddr::Tcp {
                        ip: {
                            let mut ip = vec![0u8; 16];
                            ip[0] = 0x20;
                            ip[1] = 0x01;
                            ip[2] = 0x0d;
                            ip[3] = 0xb8;
                            ip[15] = 0x09;
                            ip
                        },
                        port: 18333,
                    },
                    "fallback-ok" => PeerAddr::Other {
                        addr: "9.8.7.6:1234".to_string(),
                    },
                    "fallback-noport" => PeerAddr::Other {
                        addr: "9.8.7.6".to_string(),
                    },
                    other => panic!("unknown netaddr label {other}"),
                };
                match new_net_address(&addr, ServiceFlag(0)) {
                    Ok(na) => {
                        assert_eq!(parts[2], "ok", "{line}");
                        assert_eq!(hex(&na.ip), parts[3], "{line}");
                        assert_eq!(na.port.to_string(), parts[4], "{line}");
                    }
                    Err(e) => {
                        assert_eq!(parts[2], "err", "{line}");
                        assert_eq!(e, utf8(parts[3]), "{line}");
                    }
                }
            }
            "outbound" => {
                let cfg = match parts[1] {
                    "resolved" => {
                        let mut cfg = base_cfg();
                        cfg.host_to_net_address = Some(Box::new(|_, port, services| {
                            Ok(NetAddress {
                                timestamp: 0,
                                services,
                                ip: v4(&[9, 9, 9, 9]),
                                port,
                            })
                        }));
                        cfg
                    }
                    _ => base_cfg(),
                };
                let addr = match parts[1] {
                    "ip" => "1.2.3.4:8333",
                    "missing-port" => "1.2.3.4",
                    "bad-port" => "1.2.3.4:x",
                    "hostname" | "resolved" => "example.org:8333",
                    other => panic!("unknown outbound label {other}"),
                };
                match Peer::new_outbound(cfg, addr) {
                    Ok(p) => {
                        assert_eq!(parts[2], "ok", "{line}");
                        assert_eq!(hex(&p.na().ip), parts[3], "{line}");
                        assert_eq!(p.na().port.to_string(), parts[4], "{line}");
                    }
                    Err(e) => {
                        assert_eq!(parts[2], "err", "{line}");
                        assert_eq!(e, utf8(parts[3]), "{line}");
                    }
                }
            }
            other => panic!("unknown vector op {other}"),
        }
    }

    let expected: &[(&str, usize)] = &[
        ("neg", 13),
        ("push", 7),
        ("pushaddr", 2),
        ("ping", 1),
        ("pong", 2),
        ("deadline", 25),
        ("netaddr", 4),
        ("outbound", 5),
    ];
    for (op, want) in expected {
        assert_eq!(counts.get(op), Some(want), "row count for {op}");
    }
}

fn v4(octets: &[u8; 4]) -> [u8; 16] {
    let mut ip = [0u8; 16];
    ip[10] = 0xff;
    ip[11] = 0xff;
    ip[12..16].copy_from_slice(octets);
    ip
}

/// A `Peer` must be `Send` so the daemon can move it between the
/// per-peer input, output, and ping threads (guarded by a mutex).  This
/// is a compile-time guarantee; the body only needs to type-check.
#[test]
fn peer_is_send() {
    fn assert_send<T: Send>() {}
    assert_send::<Peer>();
}
